###### Imports and Settings

In [1]:
import pandas as pd
import numpy as np
import requests
import pickle
from collections import deque
from functools import reduce
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)

# American Community Survey 2006-2010 5 Year Estimates

In [2]:
#read in API key
with open('api_keys.pkl', 'rb') as keys_file:
        keys_dict_2 = pickle.load(keys_file)

In [3]:
#variable containing Census API key
api_key = keys_dict_2['CENSUS']

## Read In Data Guide

In [4]:
dataguide = pd.read_csv('../../Data Guides/DATA GUIDE ACS 2020 5YR.csv', dtype = str)
dataguide['ID'] = dataguide['ID'].astype(int)

In [5]:
dg1 = dataguide[dataguide['ID'].between(1, 46)]
dg2 = dataguide[dataguide['ID'].between(47, 92)]
dg3 = dataguide[dataguide['ID'].between(93, 138)]
dg4 = dataguide[dataguide['ID'].between(139, 184)]
dg5 = dataguide[dataguide['ID'].between(185, 230)]
dg6 = dataguide[dataguide['ID'].between(231, 276)]
dg7 = dataguide[dataguide['ID'].between(277, 322)]
dg8 = dataguide[dataguide['ID'].between(323, 368)]
dg9 = dataguide[dataguide['ID'].between(369, 414)]
dg10 = dataguide[dataguide['ID'].between(415, 460)]
dg11 = dataguide[dataguide['ID'].between(461, 506)]
dg12 = dataguide[dataguide['ID'].between(507, 552)]
dg13 = dataguide[dataguide['ID'].between(553, 598)]
dg14 = dataguide[dataguide['ID'].between(599, 644)]
dg15 = dataguide[dataguide['ID'].between(645, 690)]
dg16 = dataguide[dataguide['ID'].between(691, 736)]
dg17 = dataguide[dataguide['ID'].between(737, 782)]
dg18 = dataguide[dataguide['ID'].between(783, 828)]
dg19 = dataguide[dataguide['ID'].between(829, 874)]
dg20 = dataguide[dataguide['ID'].between(875, 920)]
dg21 = dataguide[dataguide['ID'].between(921, 966)]
dg22 = dataguide[dataguide['ID'].between(967, 1012)]
dg23 = dataguide[dataguide['ID'].between(1013, 1058)]
dg24 = dataguide[dataguide['ID'].between(1059, 1104)]
dg25 = dataguide[dataguide['ID'].between(1105, 1150)]
dg26 = dataguide[dataguide['ID'].between(1151, 1196)]
dg27 = dataguide[dataguide['ID'].between(1197, 1242)]
dg28 = dataguide[dataguide['ID'].between(1243, 1287)]
dg29 = dataguide[dataguide['ID'].between(1288, 1332)]
dg30 = dataguide[dataguide['ID'].between(1333, 1377)]
dg31 = dataguide[dataguide['ID'].between(1378, 1422)]
dg32 = dataguide[dataguide['ID'].between(1423, 1467)]
dg33 = dataguide[dataguide['ID'].between(1468, 1512)]
dg34 = dataguide[dataguide['ID'].between(1513, 1557)]
dg35 = dataguide[dataguide['ID'].between(1558, 1602)]
dg36 = dataguide[dataguide['ID'].between(1603, 1647)]
dg37 = dataguide[dataguide['ID'].between(1648, 1692)]
dg38 = dataguide[dataguide['ID'].between(1693, 1737)]
dg39 = dataguide[dataguide['ID'].between(1738, 1782)]
dg40 = dataguide[dataguide['ID'].between(1783, 1827)]
dg41 = dataguide[dataguide['ID'].between(1828, 1872)]
dg42 = dataguide[dataguide['ID'].between(1873, 1917)]
dg43 = dataguide[dataguide['ID'].between(1918, 1962)]
dg44 = dataguide[dataguide['ID'].between(1963, 2007)]
dg45 = dataguide[dataguide['ID'].between(2008, 2052)]
dg46 = dataguide[dataguide['ID'].between(2053, 2097)]
dg47 = dataguide[dataguide['ID'].between(2098, 2142)]
dg48 = dataguide[dataguide['ID'].between(2143, 2187)]
dg49 = dataguide[dataguide['ID'].between(2188, 2232)]
dg50 = dataguide[dataguide['ID'].between(2233, 2277)]
dg51 = dataguide[dataguide['ID'].between(2278, 2322)]
dg52 = dataguide[dataguide['ID'].between(2323, 2367)]
dg53 = dataguide[dataguide['ID'].between(2368, 2412)]
dg54 = dataguide[dataguide['ID'].between(2413, 2457)]
dg55 = dataguide[dataguide['ID'].between(2458, 2502)]
dg56 = dataguide[dataguide['ID'].between(2503, 2547)]
dg57 = dataguide[dataguide['ID'].between(2548, 2592)]
dg58 = dataguide[dataguide['ID'].between(2593, 2637)]
dg59 = dataguide[dataguide['ID'].between(2638, 2682)]
dg60 = dataguide[dataguide['ID'].between(2683, 2727)]
dg61 = dataguide[dataguide['ID'].between(2728, 2772)]
dg62 = dataguide[dataguide['ID'].between(2773, 2817)]
dg63 = dataguide[dataguide['ID'].between(2818, 2862)]
dg64 = dataguide[dataguide['ID'].between(2863, 2907)]
dg65 = dataguide[dataguide['ID'].between(2908, 2952)]
dg66 = dataguide[dataguide['ID'].between(2953, 2997)]

## One Through Thirty Seven

In [6]:
#url string and list parameters for column head and tail
url_str= 'https://api.census.gov/data/2021/acs/acs5?key='+api_key
head1 = 'NAME' 
head2 = 'GEO_ID'
tail_cols1 = 'StateFIPS'
tail_cols2 = 'CountyFIPS'
tail_cols3 = 'CensusTract'
tail_cols4 = 'BlockGroup'

In [7]:
dataguide = dg1
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [8]:
one = savename

In [9]:
dataguide = dg2
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [10]:
two = savename

In [11]:
dataguide = dg3
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [12]:
three = savename

In [13]:
dataguide = dg4
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [14]:
four = savename

In [15]:
dataguide = dg5
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [16]:
five = savename

In [17]:
dataguide = dg6
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [18]:
six = savename

In [19]:
dataguide = dg7
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [20]:
seven = savename

In [21]:
dataguide = dg8
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [22]:
eight = savename

In [23]:
dataguide = dg9
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [24]:
nine = savename

In [25]:
dataguide = dg10
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [26]:
ten = savename

In [27]:
dataguide = dg11
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [28]:
eleven = savename

In [29]:
dataguide = dg12
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [30]:
twelve = savename

In [31]:
dataguide = dg13
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [32]:
thirteen = savename

In [33]:
dataguide = dg14
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [34]:
fourteen = savename

In [35]:
dataguide = dg15
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [36]:
fifteen = savename

In [37]:
dataguide = dg16
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [38]:
sixteen = savename

In [39]:
dataguide = dg17
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [40]:
seventeen = savename

In [41]:
dataguide = dg18
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [42]:
eighteen = savename

In [43]:
dataguide = dg19
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [44]:
nineteen = savename

In [45]:
dataguide = dg20
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [46]:
twenty = savename

In [47]:
dataguide = dg21
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [48]:
twentyone = savename

In [49]:
dataguide = dg22
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [50]:
twentytwo = savename

In [51]:
dataguide = dg23
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [52]:
twentythree = savename

In [53]:
dataguide = dg24
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [54]:
twentyfour = savename

In [55]:
dataguide = dg25
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [56]:
twentyfive = savename

In [57]:
dataguide = dg26
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [58]:
twentysix = savename

In [59]:
dataguide = dg27
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [60]:
twentyseven = savename

In [61]:
dataguide = dg28
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [62]:
twentyeight = savename

In [63]:
dataguide = dg29
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [64]:
twentynine = savename

In [65]:
dataguide = dg30
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [66]:
thirty = savename

In [67]:
dataguide = dg31
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [68]:
thirtyone = savename

In [69]:
dataguide = dg32
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [70]:
thirtytwo = savename

In [71]:
dataguide = dg33
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [72]:
thirtythree = savename

In [73]:
dataguide = dg34
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [74]:
thirtyfour = savename

In [75]:
dataguide = dg35
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [76]:
thirtyfive = savename

In [77]:
dataguide = dg36
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [78]:
thirtysix = savename

In [79]:
dataguide = dg37
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [80]:
thirtyseven = savename

In [81]:
dataguide = dg38
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [82]:
thirtyeight = savename

In [83]:
dataguide = dg39
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [84]:
thirtynine = savename

In [85]:
dataguide = dg40
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [86]:
forty = savename

In [87]:
dataguide = dg41
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [88]:
fortyone = savename

In [89]:
dataguide = dg42
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [90]:
fortytwo = savename

In [91]:
dataguide = dg43
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [92]:
fortythree = savename

In [93]:
dataguide = dg44
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [94]:
fortyfour = savename

In [95]:
dataguide = dg45
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [96]:
fortyfive = savename

In [97]:
dataguide = dg46
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [98]:
fortysix = savename

In [99]:
dataguide = dg47
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [100]:
fortyseven = savename

In [101]:
dataguide = dg48
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [102]:
fortyeight = savename

In [103]:
dataguide = dg49
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [104]:
fortynine = savename

In [105]:
dataguide = dg50
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [106]:
fifty = savename

In [107]:
dataguide = dg51
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [108]:
fiftyone = savename

In [109]:
dataguide = dg52
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [110]:
fiftytwo = savename

In [111]:
dataguide = dg53
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [112]:
fiftythree = savename

In [113]:
dataguide = dg54
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [114]:
fiftyfour = savename

In [115]:
dataguide = dg55
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [116]:
fiftyfive = savename

In [117]:
dataguide = dg56
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [118]:
fiftysix = savename

In [119]:
dataguide = dg57
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [120]:
fiftyseven = savename

In [121]:
dataguide = dg58
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [122]:
fiftyeight = savename

In [123]:
dataguide = dg59
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [124]:
fiftynine = savename

In [125]:
dataguide = dg60
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [126]:
sixty = savename

In [127]:
dataguide = dg61
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [128]:
sixtyone = savename

In [129]:
dataguide = dg62
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [130]:
sixtytwo = savename

In [131]:
dataguide = dg63
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [132]:
sixtythree = savename

In [133]:
dataguide = dg64
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [134]:
sixtyfour = savename

In [135]:
dataguide = dg65
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [136]:
sixtyfive = savename

In [137]:
dataguide = dg66
var_list = list(dataguide['Variable']) #make variables list
var_list = deque(var_list)
var_list.appendleft(head2)
var_list.appendleft(head1)
col_list = list(dataguide['Column Name']) #make columns list
col_list.append(tail_cols1)
col_list.append(tail_cols2)
col_list.append(tail_cols3)
col_list.append(tail_cols4)
col_list = deque(col_list)
col_list.appendleft(head2)
col_list.appendleft(head1)
predicates= {} #block groups Tennessee
get_vars= var_list
predicates["get"]= ",". join(get_vars)
predicates["for"]= "block group:*"
predicates["in"]= "state:47, county:*, tract:*"
data = requests.get(url_str, params = predicates)
col_names = col_list
df = pd.DataFrame(columns=col_names, data=data.json()[1:], dtype=str)
savename = df
print('Okay Finished')

Okay Finished

In [138]:
sixtysix = savename

In [139]:
last = sixtysix

In [140]:
dfs = [two,three,four,five,six,seven,eight,nine,ten,eleven,twelve,thirteen, fourteen, fifteen, sixteen, seventeen, eighteen, nineteen, twenty, twentyone,
       twentytwo, twentythree, twentyfour, twentyfive, twentysix, twentyseven, twentyeight, twentynine, thirty, thirtyone, thirtytwo, thirtythree, 
       thirtyfour, thirtyfive, thirtysix, thirtyseven, thirtyeight, thirtynine, forty, fortyone, fortytwo, fortythree, fortyfour, fortyfive, 
       fortysix, fortyseven, fortyeight, fortynine, fifty, fiftyone, fiftytwo, fiftythree, fiftyfour, fiftyfive, fiftysix, fiftyseven, fiftyeight,
       fiftynine, sixty, sixtyone, sixtytwo, sixtythree, sixtyfour, sixtyfive]

In [141]:
tail_cols1 = 'StateFIPS'
tail_cols2 = 'CountyFIPS'
tail_cols3 = 'CensusTract'
tail_cols4 = 'BlockGroup'

In [142]:
for df in dfs:
    df = df.drop(columns = ['NAME','StateFIPS','CountyFIPS', 'CensusTract', 'BlockGroup'], inplace = True)

In [143]:
one = one.drop(columns = ['StateFIPS','CountyFIPS', 'CensusTract', 'BlockGroup'])
last = last.drop(columns = 'NAME')

In [144]:
df_merged = reduce(lambda  left,right: pd.merge(left,right,on=['GEO_ID'],
                                            how='outer'), dfs)

In [145]:
dfs = [one, df_merged, last]
data = reduce(lambda  left,right: pd.merge(left,right,on=['GEO_ID'],
                                            how='outer'), dfs)

In [146]:
data.head()

                                                NAME                 GEO_ID agebysex_total_series age_total_male age_m_u5 age_m_5to9 age_m_10to14  \
0  Block Group 1, Census Tract 201, Anderson Coun...  1500000US470010201001                  2003           1004      142         33            0
1  Block Group 2, Census Tract 201, Anderson Coun...  1500000US470010201002                  1436            583       66         81           20
2  Block Group 1, Census Tract 202.01, Anderson C...  1500000US470010202011                  3253           1599       73         56           99
3  Block Group 2, Census Tract 202.01, Anderson C...  1500000US470010202012                  1215            532       14         33           36
4  Block Group 1, Census Tract 202.02, Anderson C...  1500000US470010202021                  1359            695       34          0           50

  age_m_15to17 age_m_18to19 age_m_20 age_m_21 age_m_22to24 age_m_25to29 age_m_30to34 age_m_35to39 age_m_40to44 age_m_45to49 age_m_50to54  \
0           13            0        0       21           60          122          247           12           43           24           18
1           52            9        0       11            0           11           61           20           38           49            9
2           64           16       21        0           12           99          121           31          130           77          139
3           18            8        9        0           48           39            8           63           16           42           14
4          118            4        0       20            0           43            0            0           81           50           91

  age_m_55to59 age_m_60to61 age_m_62to64 age_m_65to66 age_m_67to69 age_m_70to74 age_m_75to79 age_m_80to84 age_m_85+ age_total_female age_f_u5  \
0           55           90           44           22           12           23            0           13        10              999      146
1           52            0           32           20            0           24            9           19         0              853       93
2          167          114           56           48           84          146           46            0         0             1654       49
3           45           14            0            2            5           42           31            9        36              683       15
4           10            7            9            0           18          122            0           19        19              664        0

  age_f_5to9 age_f_10to14 age_f_15to17 age_f_18to19 age_f_20 age_f_21 age_f_22to24 age_f_25to29 age_f_30to34 age_f_35to39 age_f_40to44 age_f_45to49  \
0         47          183           30           57       16       25           40           99          109           10           53           53
1         29           69           13           15       11       30           12           67           51           80           26           65
2         70          130           45           33        0       15           28           98           55           32          136          145
3         46          134           29           10        0        9           13           14           80           46           25           36
4          0           90           50           11        0        0           38            0            0           43           38          110

  age_f_50to54 age_f_55to59 age_f_60to61 age_f_62to64 age_f_65to66 age_f_67to69 age_f_70to74 age_f_75to79 age_f_80to84 age_f_85+  \
0           33           42            5            0            1            6           19            0           25         0
1           20           34           30           54           11            8           58           48           19        10
2          142          172           75           39           55          132          139           27           29         8
3            3           24            3            6            3           35           32           26           40        54
4           28           20           98           20            0           15           31            0           54        18

  raceeth_white_alone raceeth_blackafricanamerican_alone raceeth_americanindianalaskanative_alone raceeth_asian_alone  \
0                None                               None                                     None                None
1                None                               None                                     None                None
2                None                               None                                     None                None
3                None                               None                                     None                None
4                None                               None                                     None                None

  raceeth_nativehawaiianotherpacificislander_alone raceeth_someotherrace_alone raceeth_twoormoreraces_alone raceeth_whitealone_nothispanicorlatino  \
0                                             None                        None                         None                                   None
1                                             None                        None                         None                                   None
2                                             None                        None                         None                                   None
3                                             None                        None                         None                                   None
4                                             None                        None                         None                                   None

  raceeth_hispanicorlatino hhsize_avg healthcoverage_total_healthcare_series healthcoverage_total_mallhealthcare healthcoverage_mu6_all  \
0                     None       2.11                                   None                                None                   None
1                     None       2.31                                   None                                None                   None
2                     None       2.23                                   None                                None                   None
3                     None       2.40                                   None                                None                   None
4                     None       2.62                                   None                                None                   None

  healthcoverage_mu6_w healthcoverage_mu6_wo healthcoverage_m6to18_all healthcoverage_m6to18_w healthcoverage_m6to18_wo healthcoverage_m19to25_all  \
0                 None                  None                      None                    None                     None                       None
1                 None                  None                      None                    None                     None                       None
2                 None                  None                      None                    None                     None                       None
3                 None                  None                      None                    None                     None                       None
4                 None                  None                      None                    None                     None                       None

  healthcoverage_m19to25_w healthcoverage_m19to25_wo healthcoverage_m26to34_all healthcoverage_m26to34_w healthcoverage_m26to34_wo  \
0                     None                      None                       None                     None                      None
1                     None                      None                       None                     None                      None
2                     None                      None                       None                     None                      None
3                     None                      None                       None                     None                      None
4                     None                      None                       None                     None                      None

  healthcoverage_m35to44_all healthcoverage_m35to44_w healthcoverage_m35to44_wo healthcoverage_m45to54_all healthcoverage_m45to54_w  \
0                       None                     None                      None                       None                     None
1                       None                     None                      None                       None                     None
2                       None                     None                      None                       None                     None
3                       None                     None                      None                       None                     None
4                       None                     None                      None                       None                     None

  healthcoverage_m45to54_wo healthcoverage_m55to64_all healthcoverage_m55to64_w healthcoverage_m55to64_wo healthcoverage_m65to74_all  \
0                      None                       None                     None                      None                       None
1                      None                       None                     None                      None                       None
2                      None                       None                     None                      None                       None
3                      None                       None                     None                      None                       None
4                      None                       None                     None                      None                       None

  healthcoverage_m65to74_w healthcoverage_m65to74_wo healthcoverage_m75+_all healthcoverage_m75+_w healthcoverage_m75+_wo  \
0                     None                      None                    None                  None                   None
1                     None                      None                    None                  None                   None
2                     None                      None                    None                  None                   None
3                     None                      None                    None                  None                   None
4                     None                      None                    None                  None                   None

  healthcoverage_total_fallhealthcare healthcoverage_fu6_all healthcoverage_fu6_w healthcoverage_fu6_wo healthcoverage_f6to18_all  \
0                                None                   None                 None                  None                      None
1                                None                   None                 None                  None                      None
2                                None                   None                 None                  None                      None
3                                None                   None                 None                  None                      None
4                                None                   None                 None                  None                      None

  healthcoverage_f6to18_w healthcoverage_f6to18_wo healthcoverage_f19to25_all healthcoverage_f19to25_w healthcoverage_f19to25_wo  \
0                    None                     None                       None                     None                      None
1                    None                     None                       None                     None                      None
2                    None                     None                       None                     None                      None
3                    None                     None                       None                     None                      None
4                    None                     None                       None                     None                      None

  healthcoverage_f26to34_all healthcoverage_f26to34_w healthcoverage_f26to34_wo healthcoverage_f35to44_all healthcoverage_f35to44_w  \
0                       None                     None                      None                       None                     None
1                       None                     None                      None                       None                     None
2                       None                     None                      None                       None                     None
3                       None                     None                      None                       None                     None
4                       None                     None                      None                       None                     None

  healthcoverage_f35to44_wo healthcoverage_f45to54_all healthcoverage_f45to54_w healthcoverage_f45to54_wo healthcoverage_f55to64_all  \
0                      None                       None                     None                      None                       None
1                      None                       None                     None                      None                       None
2                      None                       None                     None                      None                       None
3                      None                       None                     None                      None                       None
4                      None                       None                     None                      None                       None

  healthcoverage_f55to64_w healthcoverage_f55to64_wo healthcoverage_f65to74_all healthcoverage_f65to74_w healthcoverage_f65to74_wo  \
0                     None                      None                       None                     None                      None
1                     None                      None                       None                     None                      None
2                     None                      None                       None                     None                      None
3                     None                      None                       None                     None                      None
4                     None                      None                       None                     None                      None

  healthcoverage_f75+_all healthcoverage_f75+_w healthcoverage_f75+_wo healthcoverage_total_privatehealthcare_series healthcoverage_total_mprivate  \
0                    None                  None                   None                                          None                          None
1                    None                  None                   None                                          None                          None
2                    None                  None                   None                                          None                          None
3                    None                  None                   None                                          None                          None
4                    None                  None                   None                                          None                          None

  healthcoverage_mu6_privateall healthcoverage_mu6_wprivate healthcoverage_mu6_woprivate healthcoverage_m6to18_privateall  \
0                          None                        None                         None                             None
1                          None                        None                         None                             None
2                          None                        None                         None                             None
3                          None                        None                         None                             None
4                          None                        None                         None                             None

  healthcoverage_m6to18_wprivate healthcoverage_m6to18_woprivate healthcoverage_m19to25_privateall healthcoverage_m19to25_wprivate  \
0                           None                            None                              None                            None
1                           None                            None                              None                            None
2                           None                            None                              None                            None
3                           None                            None                              None                            None
4                           None                            None                              None                            None

  healthcoverage_m19to25_woprivate healthcoverage_m26to34_privateall healthcoverage_m26to34_wprivate healthcoverage_m26to34_woprivate  \
0                             None                              None                            None                             None
1                             None                              None                            None                             None
2                             None                              None                            None                             None
3                             None                              None                            None                             None
4                             None                              None                            None                             None

  healthcoverage_m35to44_privateall healthcoverage_m35to44_wprivate healthcoverage_m35to44_woprivate healthcoverage_m45to54_privateall  \
0                              None                            None                             None                              None
1                              None                            None                             None                              None
2                              None                            None                             None                              None
3                              None                            None                             None                              None
4                              None                            None                             None                              None

  healthcoverage_m45to54_wprivate healthcoverage_m45to54_woprivate healthcoverage_m55to64_privateall healthcoverage_m55to64_wprivate  \
0                            None                             None                              None                            None
1                            None                             None                              None                            None
2                            None                             None                              None                            None
3                            None                             None                              None                            None
4                            None                             None                              None                            None

  healthcoverage_m55to64_woprivate healthcoverage_m65to74_privateall healthcoverage_m65to74_wprivate healthcoverage_m65to74_woprivate  \
0                             None                              None                            None                             None
1                             None                              None                            None                             None
2                             None                              None                            None                             None

In [148]:
data.to_csv('../../Data/ACS20215YRBG.csv', index = False)