In [2]:
import pandas as pd
import numpy as np
import requests
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)

In [155]:
import geodict
censustocommon = geodict.censustocommon
commontogeoid = geodict.commontogeoid
GNRC = geodict.GNRC
GNRCFULLFIPS = geodict.GNRCFULLFIPS
KY = geodict.KY
censusplaces = geodict.censusplaces
tnonlytocommon = geodict.tnonlytocommon

In [4]:
def percent(x, y):
    return (x/y)*100

# Selecting LEHD datasets: 

https://lehd.ces.census.gov/data/lodes/LODES7/LODESTechDoc7.5.pdf  

Pages 5 & 6 of this document outlines the file structure for Origin-Destination data. This data is limited to disaggregations by the following categories:  
+ age (29 and younger, 30 to 54, and 55 or older)  
+ earnings (1,250 a month or less, 1,251 to 3,333 a month, and greater than 3,333 a month)  
+ Goods-Producing versus Trade, Transportation & Utilities, versus All Other Services industry sectors  

The earnings breakout is kind of useless so we'll only use the age and industry sector data.  

Page 7 of this document outlines the file structure for the Residence Area Characteristics data. This shows the same totals for age and earnings listed above, but further disaggregates the industry component into 2-digit NAICS codes. It also disaggregates job counts by race, Hispanic or Latino ethnicity, sex, and educational attainment (High School or Equivalent, Some college or Associate degree, Bachelor's degree or advanced degree). 

Page 8 of this document outlines the file structure for the Workplace Area Characteristics. This shows all of the same information as the RAC but also firm age and size. 

This data package also has a geography crosswalk which will be helpful in aggregating all of these numbers to a place and county level.

## Geography Crosswalk  
What we need from the geography crosswalk:  
+ a list of block groups in the GNRC region to narrow down the WAC and RAC preliminarily (we'll only be looking at the region here, not the state, because we're simply looking at in vs out instead of flow)  
+ a way to tag county and place to WAC, RAC, and OD block codes so that we can aggregate everything available by county, place, and unincorporated areas - dictionaries for now

In [81]:
url = 'https://lehd.ces.census.gov/data/lodes/LODES7/tn/tn_xwalk.csv.gz'
geo = pd.read_csv(url, dtype = str)
print('Your file is ready.')

Your file is ready.

In [82]:
#rename and drop unneeded columns
geocols = {'tabblk2010': 'Block Code', 'st': 'StateFIPS', 'stusps': 'StateUSPS', 'stname': 'State', 'cty': 'CountyFIPS', 'ctyname': 'County', 
           'trct': 'TractCODE', 'trctname': 'Tract', 'bgrp': 'BlockgroupCODE', 'bgrpname': 'Blockgroup', 'cbsa': 'CBSACODE', 'cbsaname': 'CBSA', 
           'zcta': 'ZCTACODE', 'zctaname': 'ZCTA', 'stplc': 'PlaceCODE', 'stplcname': 'Place', 'stwib': 'WIBCODE', 'stwibname': 'WIB', 
           'blklatdd': 'Lat', 'blklondd': 'Lon'}
geo.rename(columns = geocols, inplace = True)
cols = ['ctycsub', 'ctycsubname', 'stcd116', 'stcd116name', 'stsldl', 'stsldlname', 'stsldu', 'stslduname', 'stschool',
       'stschoolname', 'stsecon', 'stseconname', 'trib', 'tribname', 'tsub', 'tsubname', 'stanrc', 'stanrcname', 'necta', 'nectaname', 'mil',
       'milname']
geo = geo.drop(columns = cols)

In [83]:
geo.head()

,Block Code,StateFIPS,StateUSPS,State,CountyFIPS,County,TractCODE,Tract,BlockgroupCODE,Blockgroup,CBSACODE,CBSA,ZCTACODE,ZCTA,PlaceCODE,Place,WIBCODE,WIB,Lat,Lon,createdate
0,470279550001069,47,TN,Tennessee,47027,"Clay County, TN",47027955000,"9550 (Clay, TN)",470279550001,"1 (Tract 9550, Clay, TN)",99999,NaN,38551,38551,9999999,NaN,47LWIA07,07 Local Workforce Investment Area,36.5522497,-85.4519031,20211018
1,470059630002096,47,TN,Tennessee,47005,"Benton County, TN",47005963000,"9630 (Benton, TN)",470059630002,"2 (Tract 9630, Benton, TN)",99999,NaN,38221,38221,9999999,NaN,47LWIA11,11 Local Workforce Investment Area,36.2107573,-88.1373529,20211018
2,470059630002091,47,TN,Tennessee,47005,"Benton County, TN",47005963000,"9630 (Benton, TN)",470059630002,"2 (Tract 9630, Benton, TN)",99999,NaN,38221,38221,9999999,NaN,47LWIA11,11 Local Workforce Investment Area,36.1901840,-88.0977486,20211018
3,470059631001043,47,TN,Tennessee,47005,"Benton County, TN",47005963100,"9631 (Benton, TN)",470059631001,"1 (Tract 9631, Benton, TN)",99999,NaN,38320,38320,9999999,NaN,47LWIA11,11 Local Workforce Investment Area,36.0788357,-88.0445962,20211018
4,470059630001061,47,TN,Tennessee,47005,"Benton County, TN",47005963000,"9630 (Benton, TN)",470059630001,"1 (Tract 9630, Benton, TN)",99999,NaN,38221,38221,9999999,NaN,47LWIA11,11 Local Workforce Investment Area,36.3057522,-88.0285893,20211018

In [84]:
#make a list of block codes in the GNRC region by listing county FIPS using geodict.py, indexing to only block codes in that list, and the creating a list of those
bg = geo.loc[geo['CountyFIPS'].isin(GNRCFULLFIPS)]
blockcodegnrcregion = list(bg['Block Code'].values)
#blockcodegnrcregion

In [85]:
#create a dictionary of county names to a list of their block codes
tncounties = list(geo['County'].unique())
c = {}
for i in tncounties:
    c['{}'.format(i)] = list(geo.loc[geo['County'] == '{}'.format(i), 'Block Code'])
#c

In [86]:
#invert that dictionary so that we can map it later
c_inverted = {}
for k,v in c.items():
    for x in v:
        c_inverted.setdefault(x,[]).append(k)
#c_inverted

In [87]:
#create a dictionary of place names to a list of their block codes
tnplace = geo[~geo['Place'].str.contains('CDP', na = True)]
tnplace = list(tnplace['Place'].unique())
p = {}
for i in tnplace:
    p['{}'.format(i)] = list(geo.loc[geo['Place'] == '{}'.format(i), 'Block Code'])
#p

In [89]:
#invert that dictionary so that we can map it later
p_inverted = {}
for k,v in p.items():
    for x in v:
        p_inverted.setdefault(x,[]).append(k)
#p_inverted

In [90]:
#create a tag for unincorporated block codes to use later per county
geo['Place'] = geo['Place'].fillna('None')
tnunincorporated = geo[(geo['Place'].str.contains('CDP'))|(geo['Place'] == 'None')]
test = list(tnunincorporated['Place'].unique())
un = {}
for i in test:
    un['{}'.format(i)] = list(geo.loc[geo['Place'] == '{}'.format(i), 'Block Code'])
#un

In [91]:
#invert that dictionary so that we can map it later
un_inverted = {}
for k,v in un.items():
    for x in v:
        un_inverted.setdefault(x,[]).append(k)
#un_inverted

## Residence Area Characteristics

In [92]:
#all primary jobs
url = 'https://lehd.ces.census.gov/data/lodes/LODES7/tn/rac/tn_rac_S000_JT01_2019.csv.gz'
rac = pd.read_csv(url)
print('Your file is ready.')

Your file is ready.

In [93]:
raccols = {'h_geocode': 'GEO_ID', 'C000': 'Total Jobs', 'CA01': 'Age:Workers 29 or Younger', 'CA02': 'Age:Workers 30 to 54', 
           'CA03': 'Age:Workers 55 Older', 'CE01': 'Earnings:1250mo or Less', 'CE02': 'Earnings:1251 to 3333mo', 
           'CE03': 'Earnings:Greater Than 3333mo', 'CNS01': 'NAICS:11Agriculture, Forestry, Fishing & Hunting', 
           'CNS02': 'NAICS:21Mining, Quarrying, Oil & Gas', 'CNS03': 'NAICS:22Utilities', 'CNS04': 'NAICS:23Construction', 'CNS05':'NAICS:31to33Manufacturing',
           'CNS06': 'NAICS:42Wholesale Trade', 'CNS07': 'NAICS:44to45Retail Trade', 'CNS08': 'NAICS:48to49Transportation & Warehousing',
           'CNS09': 'NAICS:51Information', 'CNS10': 'NAICS:52Finance & Insurance', 'CNS11': 'NAICS:53Real Estate & Rental & Leasing', 
           'CNS12': 'NAICS:54Professional, Scientific, & Technical Services', 'CNS13': 'NAICS:55Management of Companies & Enterprises', 
           'CNS14': 'NAICS:56Administrative & Support & Waste Management & Remediation Services', 'CNS15': 'NAICS:61Educational Services', 
           'CNS16': 'NAICS:62Healthcare & Social Assistance', 'CNS17': 'NAICS:71Arts, Entertainment, & Recreation', 'CNS18': 'NAICS:72Accommodation & Food Services', 
           'CNS19': 'NAICS:81Other Services (Except Public Administration)', 'CNS20': 'NAICS:92Public Administration', 
           'CR01': 'Race:White Alone', 'CR02': 'Race:Black or African American Alone', 'CR03': 'Race:American Indian or Alaska Native Alone', 
           'CR04': 'Race:Asian Alone', 'CR05': 'Race:Native Hawaiian or Other Pacific Islander Alone', 'CR07': 'Race:Two or More Races', 
           'CT01': 'Ethnicity:Not Hispanic or Latino', 'CT02': 'Ethnicity:Hispanic or Latino', 'CD01':'Ed:Less than High School', 
           'CD02': 'Ed:High School or Equivalent', 'CD03': 'Ed:Some College or Associates', 'CD04': 'Ed:Bachelors or Advanced Degree', 'CS01': 'Sex:Male', 
           'CS02': 'Sex:Female'}

In [94]:
rac.rename(columns = raccols, inplace = True)

In [95]:
rac = rac.set_index('GEO_ID')
rac = rac.add_prefix('RAC:')

In [96]:
rac.head()

,RAC:Total Jobs,RAC:Age:Workers 29 or Younger,RAC:Age:Workers 30 to 54,RAC:Age:Workers 55 Older,RAC:Earnings:1250mo or Less,RAC:Earnings:1251 to 3333mo,RAC:Earnings:Greater Than 3333mo,"RAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","RAC:NAICS:21Mining, Quarrying, Oil & Gas",RAC:NAICS:22Utilities,RAC:NAICS:23Construction,RAC:NAICS:31to33Manufacturing,RAC:NAICS:42Wholesale Trade,RAC:NAICS:44to45Retail Trade,RAC:NAICS:48to49Transportation & Warehousing,RAC:NAICS:51Information,RAC:NAICS:52Finance & Insurance,RAC:NAICS:53Real Estate & Rental & Leasing,"RAC:NAICS:54Professional, Scientific, & Technical Services",RAC:NAICS:55Management of Companies & Enterprises,RAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,RAC:NAICS:61Educational Services,RAC:NAICS:62Healthcare & Social Assistance,"RAC:NAICS:71Arts, Entertainment, & Recreation",RAC:NAICS:72Accommodation & Food Services,RAC:NAICS:81Other Services (Except Public Administration),RAC:NAICS:92Public Administration,RAC:Race:White Alone,RAC:Race:Black or African American Alone,RAC:Race:American Indian or Alaska Native Alone,RAC:Race:Asian Alone,RAC:Race:Native Hawaiian or Other Pacific Islander Alone,RAC:Race:Two or More Races,RAC:Ethnicity:Not Hispanic or Latino,RAC:Ethnicity:Hispanic or Latino,RAC:Ed:Less than High School,RAC:Ed:High School or Equivalent,RAC:Ed:Some College or Associates,RAC:Ed:Bachelors or Advanced Degree,RAC:Sex:Male,RAC:Sex:Female,RAC:createdate
GEO_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
470010201001006,76,28,39,9,15,31,30,0,0,0,3,6,2,6,1,2,5,1,9,0,9,7,12,0,9,3,1,66,7,2,1,0,0,66,10,8,17,16,7,40,36,20211018
470010201001015,125,46,61,18,26,49,50,0,0,0,1,15,4,21,1,1,4,4,13,3,11,8,14,1,18,4,2,91,15,0,14,0,5,117,8,6,27,26,20,66,59,20211018
470010201001057,8,2,5,1,1,4,3,0,0,0,0,1,0,2,1,0,0,0,1,0,1,0,0,0,0,0,2,7,1,0,0,0,0,8,0,0,2,2,2,5,3,20211018
470010201001062,95,32,41,22,18,39,38,0,0,0,3,10,5,14,1,1,3,2,11,4,11,5,10,1,11,3,0,82,6,0,5,0,2,92,3,3,17,16,27,49,46,20211018
470010201001063,80,19,44,17,16,32,32,0,0,0,1,9,1,11,2,0,4,2,6,3,5,7,8,1,14,4,2,61,8,0,8,0,3,78,2,12,13,20,16,35,45,20211018

## Workplace Area Characteristics

In [97]:
#all primary jobs
url = 'https://lehd.ces.census.gov/data/lodes/LODES7/tn/wac/tn_wac_S000_JT01_2019.csv.gz'
wac = pd.read_csv(url)
print('Your file is ready.')

Your file is ready.

In [98]:
waccols = {'w_geocode': 'GEO_ID', 'C000': 'Total Jobs', 'CA01': 'Age:Workers 29 or Younger', 'CA02': 'Age:Workers 30 to 54', 
           'CA03': 'Age:Workers 55 Older', 'CE01': 'Earnings:1250mo or Less', 'CE02': 'Earnings:1251 to 3333mo', 
           'CE03': 'Earnings:Greater Than 3333mo', 'CNS01': 'NAICS:11Agriculture, Forestry, Fishing & Hunting', 
           'CNS02': 'NAICS:21Mining, Quarrying, Oil & Gas', 'CNS03': 'NAICS:22Utilities', 'CNS04': 'NAICS:23Construction', 'CNS05':'NAICS:31to33Manufacturing',
           'CNS06': 'NAICS:42Wholesale Trade', 'CNS07': 'NAICS:44to45Retail Trade', 'CNS08': 'NAICS:48to49Transportation & Warehousing',
           'CNS09': 'NAICS:51Information', 'CNS10': 'NAICS:52Finance & Insurance', 'CNS11': 'NAICS:53Real Estate & Rental & Leasing', 
           'CNS12': 'NAICS:54Professional, Scientific, & Technical Services', 'CNS13': 'NAICS:55Management of Companies & Enterprises', 
           'CNS14': 'NAICS:56Administrative & Support & Waste Management & Remediation Services', 'CNS15': 'NAICS:61Educational Services', 
           'CNS16': 'NAICS:62Healthcare & Social Assistance', 'CNS17': 'NAICS:71Arts, Entertainment, & Recreation', 'CNS18': 'NAICS:72Accommodation & Food Services', 
           'CNS19': 'NAICS:81Other Services (Except Public Administration)', 'CNS20': 'NAICS:92Public Administration', 
           'CR01': 'Race:White Alone', 'CR02': 'Race:Black or African American Alone', 'CR03': 'Race:American Indian or Alaska Native Alone', 
           'CR04': 'Race:Asian Alone', 'CR05': 'Race:Native Hawaiian or Other Pacific Islander Alone', 'CR07': 'Race:Two or More Races', 
           'CT01': 'Ethnicity:Not Hispanic or Latino', 'CT02': 'Ethnicity:Hispanic or Latino', 'CD01':'Ed:Less than High School', 
           'CD02': 'Ed:High School or Equivalent', 'CD03': 'Ed:Some College or Associates', 'CD04': 'Ed:Bachelors or Advanced Degree', 'CS01': 'Sex:Male', 
           'CS02': 'Sex:Female', 'CFA01': 'FirmAge:0 to 1 Year', 'CFA02': 'FirmAge:2 to 3 Years', 'CFA03': 'FirmAge:4 to 5 Years', 'CFA04': 'FirmAge:6 to 10 Years',
           'CFA05': 'FirmAge:11 or More Years', 'CFS01': 'FirmSize:0 to 19 Employees', 'CFS02': 'FirmSize:20 to 49 Employees', 
           'CFS03': 'FirmSize:50 to 249 Employees', 'CFS04': 'FirmSize:250 to 499 Employees', 'CFS05': 'FirmSize:500 or More Employees'}

In [99]:
wac.rename(columns = waccols, inplace = True)

In [100]:
wac = wac.set_index('GEO_ID')
wac = wac.add_prefix('WAC:')

In [101]:
wac.head()

,WAC:Total Jobs,WAC:Age:Workers 29 or Younger,WAC:Age:Workers 30 to 54,WAC:Age:Workers 55 Older,WAC:Earnings:1250mo or Less,WAC:Earnings:1251 to 3333mo,WAC:Earnings:Greater Than 3333mo,"WAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","WAC:NAICS:21Mining, Quarrying, Oil & Gas",WAC:NAICS:22Utilities,WAC:NAICS:23Construction,WAC:NAICS:31to33Manufacturing,WAC:NAICS:42Wholesale Trade,WAC:NAICS:44to45Retail Trade,WAC:NAICS:48to49Transportation & Warehousing,WAC:NAICS:51Information,WAC:NAICS:52Finance & Insurance,WAC:NAICS:53Real Estate & Rental & Leasing,"WAC:NAICS:54Professional, Scientific, & Technical Services",WAC:NAICS:55Management of Companies & Enterprises,WAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,WAC:NAICS:61Educational Services,WAC:NAICS:62Healthcare & Social Assistance,"WAC:NAICS:71Arts, Entertainment, & Recreation",WAC:NAICS:72Accommodation & Food Services,WAC:NAICS:81Other Services (Except Public Administration),WAC:NAICS:92Public Administration,WAC:Race:White Alone,WAC:Race:Black or African American Alone,WAC:Race:American Indian or Alaska Native Alone,WAC:Race:Asian Alone,WAC:Race:Native Hawaiian or Other Pacific Islander Alone,WAC:Race:Two or More Races,WAC:Ethnicity:Not Hispanic or Latino,WAC:Ethnicity:Hispanic or Latino,WAC:Ed:Less than High School,WAC:Ed:High School or Equivalent,WAC:Ed:Some College or Associates,WAC:Ed:Bachelors or Advanced Degree,WAC:Sex:Male,WAC:Sex:Female,WAC:FirmAge:0 to 1 Year,WAC:FirmAge:2 to 3 Years,WAC:FirmAge:4 to 5 Years,WAC:FirmAge:6 to 10 Years,WAC:FirmAge:11 or More Years,WAC:FirmSize:0 to 19 Employees,WAC:FirmSize:20 to 49 Employees,WAC:FirmSize:50 to 249 Employees,WAC:FirmSize:250 to 499 Employees,WAC:FirmSize:500 or More Employees,WAC:createdate
GEO_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
470010201001000,97,35,42,20,30,48,19,0,0,0,1,0,0,11,0,0,21,0,1,0,0,0,16,11,16,20,0,91,3,0,1,0,2,93,4,7,19,23,13,29,68,0,0,0,0,0,0,0,0,0,0,20211018
470010201001005,38,7,14,17,9,23,6,0,0,0,0,0,0,5,0,0,2,0,6,0,0,0,0,0,25,0,0,30,2,1,4,0,1,38,0,2,10,12,7,8,30,0,0,0,0,0,0,0,0,0,0,20211018
470010201001006,3,0,1,2,0,3,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,3,0,0,3,0,0,0,3,0,0,0,0,0,0,0,0,0,0,20211018
470010201001009,176,39,93,44,6,94,76,0,0,0,0,0,0,0,0,0,166,0,0,0,0,0,0,0,10,0,0,161,7,0,5,0,3,169,7,12,43,44,38,44,132,0,0,0,0,0,0,0,0,0,0,20211018
470010201001010,4,1,3,0,1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,4,0,0,4,0,1,0,1,1,2,2,0,0,0,0,0,0,0,0,0,0,20211018

### Join RAC and WAC

In [102]:
#reset index to join on GEO_ID and filter both to only include the GNRC region
rac = rac.reset_index(drop = False)
rac['GEO_ID'] = rac['GEO_ID'].astype(str)
rac = rac.loc[rac['GEO_ID'].isin(blockcodegnrcregion)]
wac = wac.reset_index(drop = False)
wac['GEO_ID'] = wac['GEO_ID'].astype(str)
wac = wac.loc[wac['GEO_ID'].isin(blockcodegnrcregion)]

In [103]:
df = pd.merge(left = wac, right = rac, on = 'GEO_ID', how = 'outer')

In [104]:
df.head()

,GEO_ID,WAC:Total Jobs,WAC:Age:Workers 29 or Younger,WAC:Age:Workers 30 to 54,WAC:Age:Workers 55 Older,WAC:Earnings:1250mo or Less,WAC:Earnings:1251 to 3333mo,WAC:Earnings:Greater Than 3333mo,"WAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","WAC:NAICS:21Mining, Quarrying, Oil & Gas",WAC:NAICS:22Utilities,WAC:NAICS:23Construction,WAC:NAICS:31to33Manufacturing,WAC:NAICS:42Wholesale Trade,WAC:NAICS:44to45Retail Trade,WAC:NAICS:48to49Transportation & Warehousing,WAC:NAICS:51Information,WAC:NAICS:52Finance & Insurance,WAC:NAICS:53Real Estate & Rental & Leasing,"WAC:NAICS:54Professional, Scientific, & Technical Services",WAC:NAICS:55Management of Companies & Enterprises,WAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,WAC:NAICS:61Educational Services,WAC:NAICS:62Healthcare & Social Assistance,"WAC:NAICS:71Arts, Entertainment, & Recreation",WAC:NAICS:72Accommodation & Food Services,WAC:NAICS:81Other Services (Except Public Administration),WAC:NAICS:92Public Administration,WAC:Race:White Alone,WAC:Race:Black or African American Alone,WAC:Race:American Indian or Alaska Native Alone,WAC:Race:Asian Alone,WAC:Race:Native Hawaiian or Other Pacific Islander Alone,WAC:Race:Two or More Races,WAC:Ethnicity:Not Hispanic or Latino,WAC:Ethnicity:Hispanic or Latino,WAC:Ed:Less than High School,WAC:Ed:High School or Equivalent,WAC:Ed:Some College or Associates,WAC:Ed:Bachelors or Advanced Degree,WAC:Sex:Male,WAC:Sex:Female,WAC:FirmAge:0 to 1 Year,WAC:FirmAge:2 to 3 Years,WAC:FirmAge:4 to 5 Years,WAC:FirmAge:6 to 10 Years,WAC:FirmAge:11 or More Years,WAC:FirmSize:0 to 19 Employees,WAC:FirmSize:20 to 49 Employees,WAC:FirmSize:50 to 249 Employees,WAC:FirmSize:250 to 499 Employees,WAC:FirmSize:500 or More Employees,WAC:createdate,RAC:Total Jobs,RAC:Age:Workers 29 or Younger,RAC:Age:Workers 30 to 54,RAC:Age:Workers 55 Older,RAC:Earnings:1250mo or Less,RAC:Earnings:1251 to 3333mo,RAC:Earnings:Greater Than 3333mo,"RAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","RAC:NAICS:21Mining, Quarrying, Oil & Gas",RAC:NAICS:22Utilities,RAC:NAICS:23Construction,RAC:NAICS:31to33Manufacturing,RAC:NAICS:42Wholesale Trade,RAC:NAICS:44to45Retail Trade,RAC:NAICS:48to49Transportation & Warehousing,RAC:NAICS:51Information,RAC:NAICS:52Finance & Insurance,RAC:NAICS:53Real Estate & Rental & Leasing,"RAC:NAICS:54Professional, Scientific, & Technical Services",RAC:NAICS:55Management of Companies & Enterprises,RAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,RAC:NAICS:61Educational Services,RAC:NAICS:62Healthcare & Social Assistance,"RAC:NAICS:71Arts, Entertainment, & Recreation",RAC:NAICS:72Accommodation & Food Services,RAC:NAICS:81Other Services (Except Public Administration),RAC:NAICS:92Public Administration,RAC:Race:White Alone,RAC:Race:Black or African American Alone,RAC:Race:American Indian or Alaska Native Alone,RAC:Race:Asian Alone,RAC:Race:Native Hawaiian or Other Pacific Islander Alone,RAC:Race:Two or More Races,RAC:Ethnicity:Not Hispanic or Latino,RAC:Ethnicity:Hispanic or Latino,RAC:Ed:Less than High School,RAC:Ed:High School or Equivalent,RAC:Ed:Some College or Associates,RAC:Ed:Bachelors or Advanced Degree,RAC:Sex:Male,RAC:Sex:Female,RAC:createdate
0,470210701021001,7.0,1.0,2.0,4.0,1.0,4.0,2.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,1.0,0.0,0.0,0.0,0.0,7.0,0.0,1.0,4.0,0.0,1.0,6.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20211018.0,34.0,11.0,15.0,8.0,3.0,17.0,14.0,0.0,0.0,1.0,1.0,6.0,0.0,7.0,0.0,1.0,0.0,0.0,2.0,0.0,2.0,2.0,7.0,1.0,3.0,0.0,1.0,32.0,1.0,0.0,0.0,1.0,0.0,34.0,0.0,7.0,4.0,7.0,5.0,20.0,14.0,20211018.0
1,470210701021002,67.0,12.0,38.0,17.0,8.0,33.0,26.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,62.0,0.0,0.0,0.0,5.0,57.0,6.0,3.0,0.0,0.0,1.0,64.0,3.0,5.0,18.0,16.0,16.0,11.0,56.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20211018.0,89.0,23.0,41.0,25.0,18.0,26.0,45.0,0.0,0.0,0.0,10.0,10.0,2.0,10.0,3.0,3.0,4.0,1.0,3.0,2.0,8.0,4.0,17.0,1.0,6.0,1.0,4.0,84.0,1.0,0.0,2.0,0.0,2.0,88.0,1.0,7.0,20.0,20.0,19.0,55.0,34.0,20211018.0
2,470210701021006,5.0,0.0,4.0,1.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,1.0,2.0,2.0,0.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20211018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,470210701021008,16.0,5.0,8.0,3.0,2.0,3.0,11.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,0.0,0.0,0.0,0.0,0.0,16.0,0.0,2.0,1.0,4.0,4.0,12.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20211018.0,150.0,25.0,88.0,37.0,29.0,42.0,79.0,0.0,0.0,1.0,14.0,19.0,8.0,13.0,5.0,3.0,6.0,0.0,10.0,1.0,10.0,18.0,16.0,0.0,9.0,6.0,11.0,142.0,2.0,0.0,0.0,0.0,6.0,146.0,4.0,14.0,37.0,38.0,36.0,77.0,73.0,20211018.0
4,470210701021018,2.0,0.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20211018.0,32.0,9.0,18.0,5.0,4.0,10.0,18.0,0.0,0.0,1.0,2.0,3.0,1.0,4.0,3.0,0.0,0.0,0.0,3.0,0.0,2.0,2.0,2.0,0.0,3.0,1.0,5.0,31.0,1.0,0.0,0.0,0.0,0.0,31.0,1.0,3.0,7.0,8.0,5.0,16.0,16.0,20211018.0

In [135]:
#make dataframes to be grouped by both county and place to concatenate later
county = df
place = df

In [136]:
#add columns with county name and place name respectively
county['County'] = county['GEO_ID'].map(c_inverted)
county['Incorporated'] = county['GEO_ID'].map(un_inverted)
place['Place'] = place['GEO_ID'].map(p_inverted)

In [137]:
county['County'] = county['County'].str.get(0)
county['Incorporated'] = county['Incorporated'].str.get(0)
place['Place'] = place['Place'].str.get(0)

In [138]:
county = county.drop(columns = ['GEO_ID'])
place = place.drop(columns = ['GEO_ID'])

In [139]:
countywacrac = county.groupby('County').sum()

In [140]:
placewacrac = place.groupby('Place').sum()

In [141]:
unwacrac = county.groupby(['Incorporated', 'County']).sum()

In [142]:
unwacrac = unwacrac.groupby('County').sum()

In [143]:
unwacrac = unwacrac.transpose()

In [144]:
#unwacrac = unwacrac.rename(columns = tnonlytocommon)

In [145]:
unwacrac = unwacrac.transpose()

In [146]:
wacrac = countywacrac.append(placewacrac)
#wacrac = wacrac.rename(columns = tnonlytocommon)
data = wacrac.append(unwacrac)

C:\Users\jmccall\AppData\Local\Temp\ipykernel_17468\769542372.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  wacrac = countywacrac.append(placewacrac)
C:\Users\jmccall\AppData\Local\Temp\ipykernel_17468\769542372.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = wacrac.append(unwacrac)

In [154]:
data.head(20)

,WAC:Total Jobs,WAC:Age:Workers 29 or Younger,WAC:Age:Workers 30 to 54,WAC:Age:Workers 55 Older,WAC:Earnings:1250mo or Less,WAC:Earnings:1251 to 3333mo,WAC:Earnings:Greater Than 3333mo,"WAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","WAC:NAICS:21Mining, Quarrying, Oil & Gas",WAC:NAICS:22Utilities,WAC:NAICS:23Construction,WAC:NAICS:31to33Manufacturing,WAC:NAICS:42Wholesale Trade,WAC:NAICS:44to45Retail Trade,WAC:NAICS:48to49Transportation & Warehousing,WAC:NAICS:51Information,WAC:NAICS:52Finance & Insurance,WAC:NAICS:53Real Estate & Rental & Leasing,"WAC:NAICS:54Professional, Scientific, & Technical Services",WAC:NAICS:55Management of Companies & Enterprises,WAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,WAC:NAICS:61Educational Services,WAC:NAICS:62Healthcare & Social Assistance,"WAC:NAICS:71Arts, Entertainment, & Recreation",WAC:NAICS:72Accommodation & Food Services,WAC:NAICS:81Other Services (Except Public Administration),WAC:NAICS:92Public Administration,WAC:Race:White Alone,WAC:Race:Black or African American Alone,WAC:Race:American Indian or Alaska Native Alone,WAC:Race:Asian Alone,WAC:Race:Native Hawaiian or Other Pacific Islander Alone,WAC:Race:Two or More Races,WAC:Ethnicity:Not Hispanic or Latino,WAC:Ethnicity:Hispanic or Latino,WAC:Ed:Less than High School,WAC:Ed:High School or Equivalent,WAC:Ed:Some College or Associates,WAC:Ed:Bachelors or Advanced Degree,WAC:Sex:Male,WAC:Sex:Female,WAC:FirmAge:0 to 1 Year,WAC:FirmAge:2 to 3 Years,WAC:FirmAge:4 to 5 Years,WAC:FirmAge:6 to 10 Years,WAC:FirmAge:11 or More Years,WAC:FirmSize:0 to 19 Employees,WAC:FirmSize:20 to 49 Employees,WAC:FirmSize:50 to 249 Employees,WAC:FirmSize:250 to 499 Employees,WAC:FirmSize:500 or More Employees,WAC:createdate,RAC:Total Jobs,RAC:Age:Workers 29 or Younger,RAC:Age:Workers 30 to 54,RAC:Age:Workers 55 Older,RAC:Earnings:1250mo or Less,RAC:Earnings:1251 to 3333mo,RAC:Earnings:Greater Than 3333mo,"RAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","RAC:NAICS:21Mining, Quarrying, Oil & Gas",RAC:NAICS:22Utilities,RAC:NAICS:23Construction,RAC:NAICS:31to33Manufacturing,RAC:NAICS:42Wholesale Trade,RAC:NAICS:44to45Retail Trade,RAC:NAICS:48to49Transportation & Warehousing,RAC:NAICS:51Information,RAC:NAICS:52Finance & Insurance,RAC:NAICS:53Real Estate & Rental & Leasing,"RAC:NAICS:54Professional, Scientific, & Technical Services",RAC:NAICS:55Management of Companies & Enterprises,RAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,RAC:NAICS:61Educational Services,RAC:NAICS:62Healthcare & Social Assistance,"RAC:NAICS:71Arts, Entertainment, & Recreation",RAC:NAICS:72Accommodation & Food Services,RAC:NAICS:81Other Services (Except Public Administration),RAC:NAICS:92Public Administration,RAC:Race:White Alone,RAC:Race:Black or African American Alone,RAC:Race:American Indian or Alaska Native Alone,RAC:Race:Asian Alone,RAC:Race:Native Hawaiian or Other Pacific Islander Alone,RAC:Race:Two or More Races,RAC:Ethnicity:Not Hispanic or Latino,RAC:Ethnicity:Hispanic or Latino,RAC:Ed:Less than High School,RAC:Ed:High School or Equivalent,RAC:Ed:Some College or Associates,RAC:Ed:Bachelors or Advanced Degree,RAC:Sex:Male,RAC:Sex:Female,RAC:createdate
"Cheatham County, TN",7918.0,1949.0,4255.0,1714.0,1433.0,2789.0,3696.0,4.0,0.0,44.0,784.0,2290.0,76.0,820.0,382.0,20.0,165.0,69.0,263.0,2.0,393.0,960.0,447.0,62.0,600.0,172.0,365.0,7053.0,638.0,30.0,103.0,13.0,81.0,7482.0,436.0,784.0,1981.0,1833.0,1371.0,4295.0,3623.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.396342e+09,19706.0,4446.0,10549.0,4711.0,3016.0,6117.0,10573.0,25.0,11.0,133.0,1584.0,1888.0,951.0,2087.0,999.0,405.0,781.0,312.0,1245.0,388.0,1186.0,1545.0,2556.0,269.0,1518.0,605.0,1218.0,18645.0,599.0,67.0,162.0,11.0,222.0,19050.0,656.0,1601.0,4477.0,4908.0,4274.0,10195.0,9511.0,1.402645e+10
"Davidson County, TN",502956.0,122426.0,272971.0,107559.0,75893.0,147811.0,279252.0,261.0,182.0,1465.0,23603.0,21374.0,24395.0,42556.0,26896.0,14044.0,23276.0,10106.0,39811.0,10440.0,42852.0,35732.0,79295.0,9913.0,48083.0,16092.0,32580.0,379502.0,98611.0,1672.0,15302.0,378.0,7491.0,478049.0,24907.0,44391.0,102707.0,120150.0,113282.0,254052.0,248904.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.330982e+10,320699.0,89080.0,166883.0,64736.0,53939.0,101707.0,165053.0,274.0,114.0,619.0,11347.0,17313.0,12571.0,29901.0,15791.0,9440.0,15869.0,6404.0,25659.0,9120.0,27696.0,24984.0,47647.0,6292.0,34436.0,10274.0,14948.0,217362.0,84986.0,1035.0,11809.0,239.0,5268.0,301251.0,19448.0,29154.0,63582.0,72691.0,66192.0,157008.0,163691.0,1.530580e+11
"Dickson County, TN",16461.0,4195.0,8556.0,3710.0,3524.0,6460.0,6477.0,26.0,21.0,236.0,1022.0,3763.0,733.0,2226.0,178.0,105.0,441.0,85.0,246.0,130.0,1076.0,1017.0,2395.0,64.0,1574.0,367.0,756.0,14622.0,1379.0,58.0,206.0,10.0,186.0,15922.0,539.0,1554.0,4400.0,3842.0,2470.0,8593.0,7868.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.448206e+09,23414.0,5599.0,12454.0,5361.0,4159.0,7975.0,11280.0,32.0,35.0,269.0,1905.0,3320.0,1018.0,2709.0,818.0,343.0,795.0,284.0,1153.0,367.0,1354.0,1511.0,3198.0,235.0,2118.0,639.0,1311.0,21510.0,1319.0,60.0,231.0,17.0,277.0,22660.0,754.0,1999.0,5609.0,5802.0,4405.0,12065.0,11349.0,3.199404e+10
"Houston County, TN",1272.0,274.0,669.0,329.0,316.0,524.0,432.0,5.0,0.0,5.0,101.0,170.0,0.0,154.0,4.0,10.0,42.0,3.0,27.0,0.0,2.0,221.0,313.0,0.0,90.0,13.0,112.0,1171.0,63.0,2.0,21.0,1.0,14.0,1249.0,23.0,95.0,360.0,338.0,205.0,502.0,770.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.152028e+09,2915.0,690.0,1555.0,670.0,531.0,1161.0,1223.0,5.0,18.0,21.0,274.0,630.0,73.0,320.0,69.0,35.0,79.0,34.0,83.0,22.0,115.0,285.0,415.0,11.0,220.0,49.0,157.0,2734.0,109.0,8.0,27.0,1.0,36.0,2851.0,64.0,239.0,802.0,731.0,453.0,1490.0,1425.0,7.882297e+09
"Humphreys County, TN",5620.0,1225.0,2919.0,1476.0,1112.0,1828.0,2680.0,8.0,31.0,32.0,538.0,1566.0,88.0,627.0,336.0,16.0,94.0,6.0,85.0,0.0,162.0,577.0,512.0,14.0,490.0,184.0,254.0,5139.0,363.0,23.0,34.0,8.0,53.0,5500.0,120.0,447.0,1628.0,1416.0,904.0,3286.0,2334.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.294396e+09,6743.0,1571.0,3559.0,1613.0,1233.0,2646.0,2864.0,17.0,28.0,35.0,493.0,1651.0,188.0,816.0,262.0,62.0,181.0,36.0,178.0,49.0,285.0,639.0,794.0,26.0,486.0,140.0,377.0,6363.0,248.0,25.0,38.0,7.0,62.0,6597.0,146.0,587.0,1840.0,1680.0,1065.0,3566.0,3177.0,1.505721e+10
"Maury County, TN",34897.0,8468.0,17996.0,8433.0,6152.0,12745.0,16000.0,53.0,12.0,240.0,1190.0,7182.0,1212.0,3986.0,789.0,403.0,1917.0,2314.0,793.0,205.0,1822.0,2185.0,5297.0,211.0,3041.0,703.0,1342.0,29095.0,4789.0,125.0,453.0,17.0,418.0,33621.0,1276.0,2995.0,8292.0,9003.0,6139.0,18089.0,16808.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.257125e+10,42582.0,10548.0,22185.0,9849.0,7628.0,14723.0,20231.0,93.0,26.0,307.0,2140.0,6107.0,1573.0,5229.0,1436.0,701.0,2178.0,1218.0,2229.0,831.0,2760.0,2822.0,5765.0,421.0,3849.0,1012.0,1885.0,35530.0,5883.0,155.0,475.0,20.0,519.0,40605.0,1977.0,3796.0,9619.0,10477.0,8142.0,21734.0,20848.0,4.373664e+10
"Montgomery County, TN",50425.0,15037.0,25907.0,9481.0,11817.0,19279.0,19329.0,18.0,315.0,675.0,2110.0,6120.0,1716.0,7797.0,682.0,895.0,1236.0,827.0,1481.0,344.0,2897.0,6270.0,6232.0,343.0,6979.0,1218.0,2270.0,38466.0,9250.0,225.0,1083.0,130.0,1271.0,47451.0,2974.0,4624.0,11306.0,11788.0,7670.0,23561.0,26864.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.521890e+10,66793.0,18510.0,35926.0,12357.0,13633.0,24253.0,28907.0,77.0,252.0,570.0,3113.0,8435.0,2491.0,8013.0,2820.0,1091.0,1934.0,1017.0,2982.0,744.0,4839.0,6691.0,8445.0,559.0,7495.0,1681.0,3544.0,47960.0,15089.0,332.0,1443.0,206.0,1763.0,62223.0,4570.0,6356.0,15147.0,15900.0,10880.0,32857.0,33936.0,4.064436e+10
"Robertson County, TN",21889.0,5482.0,11271.0,5136.0,4127.0,9271.0,8491.0,166.0,25.0,194.0,1332.0,5393.0,1181.0,2913.0,2068.0,55.0,660.0,160.0,386.0,236.0,1045.0,1488.0,1702.0,95.0,1581.0,438.0,771.0,17877.0,3270.0,75.0,374.0,17.0,276.0,20487.0,1402.0,2392.0,5654.0,5193.0,3168.0,11252.0,10637.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.367361e+09,33293.0,7856.0,17638.0,7799.0,5624.0,10987.0,16682.0,108.0,38.0,249.0,2502.0,4419.0,1687.0,4000.0,1923.0,476.0,1200.0,490.0,1657.0,603.0,1849.0,2495.0,3860.0,371.0,2677.0,807.0,1882.0,29356.0,3112.0,124.0,338.0,29.0,334.0,31675.0,1618.0,3099.0,7842.0,8185.0,6311.0,16952.0,16341.0,2.657749e+10
"Rutherford County, TN",128291.0,33868.0,68599.0,25824.0,22602.0,39945.0,65744.0,77.0,45.0,641.0,5044.0,26957.0,5203.0,15595.0,8956.0,3201.0,3336.0,1518.0,3454.0,1301.0,9756.0,10722.0,14369.0,901.0,11233.0,2633.0,3349.0,100467.0,20945.0,441.0,4412.0,99.0,1927.0,121563.0,6728.0,11433.0,28705.0,30427.0,23858.0,69013.0,59278.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.574884e+10,148178.0,37498.0,81919.0,28761.0,23979.0,44699.0,79500.0,141.0,83.0,647.0,6592.0,18529.0,6833.0,15921.0,9290.0,3439.0,6662.0,2385.0,8313.0,3324.0,11625.0,12412.0,17826.0,1671.0,13014.0,3668.0,5803.0,113433.0,26566.0,496.0,5301.0,129.0,2253.0,139508.0,8670.0,13278.0,31773.0,35489.0,30140.0,75756.0,72422.0,6.590813e+10
"Stewart County, TN",2399.0,575.0,1251.0,573.0,538.0,884.0,977.0,2.0,0.0,24.0,366.0,599.0,27.0,274.0,17.0,5.0,43.0,3.0,80.0,12.0,12.0,398.0,146.0,15.0,172.0,39.0,165.0,2257.0,85.0,13.0,22.0,1.0,21.0,2340.0,59.0,203.0,688.0,565.0,368.0,1249.0,1150.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.041313e+09,4483.0,1063.0,2371.0,1049.0,877.0,1674.0,1932.0,3.0,27.0,53.0,317.0,636.0,146.0,586.0,148.0,60.0,118.0,37.0,181.0,27.0,216.0,563.0,568.0,29.0,373.0,101.0,294.0,4275.0,102.0,15.0,38.0,1.0,52.0,4387.0,96.0,348.0,1134.0,1132.0,806.0,2249.0,2234.0,1.190429e+10
"Sumner County, TN",52371.0,13158.0,26983.0,12230.0,10372.0,18664.0,23335.0,48.0,20.0,140.0,3697.0,7753.0,2287.0,7070.0,1887.0,530.0,1489.0,631.0,3037.0,573.0,2489.0,5869.0,6111.0,668.0,4548.0,1385.0,2139.0,45181.0,5519.0,172.0,818.0,45.0,636.0,50018.0,2353.0,4554.0,12476.0,12873.0,9310.0,25477.0,26894.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.837182e+10,84887.0,19117.0,45837.0,19933.0,13908.0,25978.0,45001.0,92.0,43.0,432.0,5007.0,8756.0,4442.0,9490.0,4668.0,1449.0,3362.0,1387.0,5500.0,1998.0,4997.0,7460.0,10801.0,1196.0,7208.0,2257.0,4342.0,74197.0,8109.0,237.0,1245.0,76.0,1023.0,81489.0,3398.0,7199.0,19323.0,21425.0,17823.0,43030.0,41857.0,4.887024e+10
"Trousdale County, TN",1563.0,403.0,749.0,411.0,337.0,598.0,628.0,10.0,0.0,23.0,45.0,261.0,2.0,143.0,27.0,8.0,70.0,3.0,71.0,1.0,158.0,253.0,194.0,0.0,109.0,60.0,125.0,1394.0,133.0,6.0,20.0,0.0,10.0,1537.0,26.0,122.0,418.0,362.0,258.0,716.0,847.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.152028e+09,4149.0,1056.0,2109.0,984.0,731.0,1544.0,1874.0,15.0,6.0,35.0,242.0,615.0,222.0,484.0,275.0,59.0,144.0,32.0,171.0,69.0,249.0,337.0,543.0,32.0,299.0,102.0,218.0,3611.0,445.0,16.0,27.0,2.0,48.0,4044.0,105.0,338.0,1044.0,1043.0,668.0,2056.0,2093.0,4.850644e+09
"Williamson County, TN",134978.0,33688.0,74697.0,26593.0,22090.0,35712.0,77176.0,175.0,24.0,245.0,7089.0,3933.0,4316.0,14919.0,1494.0,4720.0,12439.0,2339.0,17893.0,12142.0,10072.0,9312.0,13836.0,2262.0,11110.0,3635.0,3023.0,112670.0,16075.0,404.0,3980.0,96.0,1753.0,128309.0,6669.0,10226.0,25350.0,31856.0,33858.0,64113.0,70865.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.888154e+10,100500.0,19258.0,57583.0,23659.0,15997.0,19910.0,64593.0,128.0,40.0,273.0,3823.0,5854.0,4377.0,9638.0,3166.0,3202.0,6652.0,1933.0,10846.0,4195.0,6072.0,9731.0,13661.0,1836.0,8230.0,2985.0,3858.0,88334.0,5860.0,268.0,4823.0,52.0,1163.0,96282.0,4218.0,7684.0,20003.0,24769.0,28786.0,53069.0,47431.0,5.311456e+10
"Wilson County, TN",45494.0,12447.0,23297.0,9750.0,9369.0,16333.0,19792.0,5.0,77.0,245.0,2144.0,4246.0,3034.0,5932.0,7751.0,349.0,1470.0,505.0,1683.0,915.0,1703.0,3841.0,3903.0,523.0,4391.0,1233.0,1544.0,37924.0,5762.0,166.0,1025.0,31.0,586.0,43486.0,2008.0,3962.0,10528.0,10758.0,7799.0,23378.0,22116.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.580502e+10,64214.0,13668.0,35317.0,15229.0,10489.0,17648.0,36077.0,54.0,94.0,343.0,3474.0,5423.0,3529.0,6802.0,4287.0,1447.0,2913.0,1095.0,4413.0,1486.0,4228.0,5151.0,8031.0,921.0,5497.0,1734.0,3292.0,56354.0,5502.0,223.0,1315.0,38.0,782.0,61867.0,2347.0,5149.0,14488.0,16222.0,14687.0,32785.0,31429.0,4.066457e+10
"Adams city, TN",46.0,13.0,25.0,8.0,28.0,13.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,12.0,0.0,9.0,0.0,2.0,41.0,2.0,1.0,1.0,0.0,1.0,45.0,1.0,3.0,14.0,13.0,3.0,10.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.010551e+08,321.0,71.0,169.0,81.0,55.0,104.0,162.0,3.0,0.0,7.0,23.0,37.0,15.0,35.0,15.0,4.0,8.0,6.0,11.0,9.0,21.0,20.0,41.0,3.0,25.0,11.0,27.0,291.0,17.0,8.0,3.0,1.0,1.0,309.0,12.0,27.0,78.0,88.0,57.0,161.0,160.0,6.265416e+08
"Ashland City town, TN",4691.0,1001.0,2611.0,1079.0,651.0,1536.0,2504.0,0.0,0.0,15.0,121.0,1920.0,1.0,495.0,258.0,8.0,74.0,21.0,69.0,0.0,129.0,873.0,99.0,5.0,269.0,18.0,316.0,4107.0,449.0,16.0,70.0,3.0,46.0,4432.0,259.0,447.0,1266.0,1121.0,856.0,2519.0,2172.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.084407e+08,2035.0,490.0,1093.0,452.0,344.0,768.0,923.0,0.0,3.0,8.0,134.0,244.0,97.0,225.0,116.0,44.0,66.0,36.0,104.0,36.0,130.0,127.0,255.0,26.0,187.0,74.0,123.0,1834.0,130.0,10.0,29.0,0.0,32.0,1929.0,106.0,175.0,471.0,502.0,397.0,1075.0,960.0,1.434982e+09
"Belle Meade city, TN",1068.0,343.0,449.0,276.0,275.0,446.0,347.0,3.0,0.0,0.0,17.0,28.0,12.0,131.0,0.0,8.0,17.0,8.0,2.0,4.0,20.0,12.0,27.0,218.0,385.0,150.0,26.0,880.0,147.0,4.0,18.0,0.0,19.0,986.0,82.0,93.0,191.0,224.0,217.0,515.0,553.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.903399e+08,1063.0,180.0,533.0,350.0,144.0,162.0,757.0,1.0,2.0,2.0,36.0,41.0,51.0,82.0,41.0,27.0,74.0,39.0,106.0,31.0,66.0,80.0,212.0,33.0,83.0,32.0,24.0,1032.0,9.0,2.0,14.0,1.0,5.0,1041.0,22.0,64.0,208.0,258.0,353.0,642.0,421.0,1.232872e+09
"Berry Hill city, TN",29304.0,4780.0,17376.0,7148.0,2841.0,7886.0,18577.0,0.0,0.0,0.0,772.0,519.0,1138.0,700.0,747.0,117.0,71.0,163.0,449.0,51.0,1014.0,12567.0,133.0,231.0,498.0,183.0,9951.0,20709.0,7757.0,69.0,359.0,15.0,395.0,28121.0,1183.0,2409.0,6368.0,7885.0,7862.0,13368.0,15936.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.275966e+08,455.0,161.0,222.0,72.0,81.0,121.0,253.0,0.0,0.0,3.0,20.0,14.0,25.0,33.0,19.0,17.0,18.0,13.0,48.0,10.0,31.0,45.0,83.0,11.0,39.0,14.0,12.0,388.0,27.0,1.0,31.0,0.0,8.0,434.0,21.0,31.0,67.0,104.0,92.0,222.0,233.0,4.446424e+08
"Brentwood city, TN",46420.0,10444.0,26887.0,9089.0,5949.0,10863.0,29608.0,3.0,0.0,2.0,1700.0,487.0,1435.0,3423.0,637.0,2193.0,4426.0,881.0,8024.0,7836.0,5296.0,484.0,4860.0,641.0,2471.0,1254.0,367.0,37463.0,6622.0,150.0,1565.0,28.0,592.0,44320.0,2100.0,3354.0,8444.0,11483.0,12695.0,21416.0,25004.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.416553e+09,18954.0,3353.0,10663.0,4938.0,2929.0,3072.0,12953.0,23.0,6.0,35.0,617.0,1027.0,908.0,1685.0,636.0,655.0,1226.0,347.0,2244.0,828.0,1206.0,1607.0,2919.0,332.0,1394.0,570.0,689.0,16220.0,935.0,41.0,1512.0,6.0,240.0,18367.0,587.0,1375.0,3680.0,4652.0,5894.0,10438.0,8516.0,7.316389e+09
"Burns town, TN",172.0,28.0,100.0,44.0,31.0,62.0,79.0,0.0,0.0,0.0,12.0,0.0,8.0,18.0,0.0,0.0,8.0,0.0,2.0,0.0,1.0,95.0,7.0,0.0,9.0,4.0,8.0,165.0,4.0,0.0,2.0,0.0,1.0,168.0,4.0,12.0,33.0,52.0,47.0,57.0,115.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.425322e+08,711.0,143.0,408.0,160.0,108.0,200.0,403.0,1.0,1.0,9.0,55.0,114.0,35.0,71.0,21.0,16.0,26.0,14.0,32.0,14.0,32.0,40.0,90.0,13.0,63.0,24.0,40.0,687.0,18.0,0.0,3.0,1.0,2.0,691.0,20.0,64.0,168.0,189.0,147.0,383.0,328.0,1.172239e+09

In [149]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 81 entries, Cheatham County, TN to Wilson County, TN
Data columns (total 94 columns):
 #   Column                                                                          Non-Null Count  Dtype
---  ------                                                                          --------------  -----
 0   WAC:Total Jobs                                                                  81 non-null     float64
 1   WAC:Age:Workers 29 or Younger                                                   81 non-null     float64
 2   WAC:Age:Workers 30 to 54                                                        81 non-null     float64
 3   WAC:Age:Workers 55 Older                                                        81 non-null     float64
 4   WAC:Earnings:1250mo or Less                                                     81 non-null     float64
 5   WAC:Earnings:1251 to 3333mo                                                     81 non-null     float64
 6   WAC:Earnings:Greater Than 3333mo                                                81 non-null     float64
 7   WAC:NAICS:11Agriculture, Forestry, Fishing & Hunting                            81 non-null     float64
 8   WAC:NAICS:21Mining, Quarrying, Oil & Gas                                        81 non-null     float64
 9   WAC:NAICS:22Utilities                                                           81 non-null     float64
 10  WAC:NAICS:23Construction                                                        81 non-null     float64
 11  WAC:NAICS:31to33Manufacturing                                                   81 non-null     float64
 12  WAC:NAICS:42Wholesale Trade                                                     81 non-null     float64
 13  WAC:NAICS:44to45Retail Trade                                                    81 non-null     float64
 14  WAC:NAICS:48to49Transportation & Warehousing                                    81 non-null     float64
 15  WAC:NAICS:51Information                                                         81 non-null     float64
 16  WAC:NAICS:52Finance & Insurance                                                 81 non-null     float64
 17  WAC:NAICS:53Real Estate & Rental & Leasing                                      81 non-null     float64
 18  WAC:NAICS:54Professional, Scientific, & Technical Services                      81 non-null     float64
 19  WAC:NAICS:55Management of Companies & Enterprises                               81 non-null     float64
 20  WAC:NAICS:56Administrative & Support & Waste Management & Remediation Services  81 non-null     float64
 21  WAC:NAICS:61Educational Services                                                81 non-null     float64
 22  WAC:NAICS:62Healthcare & Social Assistance                                      81 non-null     float64
 23  WAC:NAICS:71Arts, Entertainment, & Recreation                                   81 non-null     float64
 24  WAC:NAICS:72Accommodation & Food Services                                       81 non-null     float64
 25  WAC:NAICS:81Other Services (Except Public Administration)                       81 non-null     float64
 26  WAC:NAICS:92Public Administration                                               81 non-null     float64
 27  WAC:Race:White Alone                                                            81 non-null     float64
 28  WAC:Race:Black or African American Alone                                        81 non-null     float64
 29  WAC:Race:American Indian or Alaska Native Alone                                 81 non-null     float64
 30  WAC:Race:Asian Alone                                                            81 non-null     float64
 31  WAC:Race:Native Hawaiian or Other Pacific Islander Alone                        81 non-null     float64
 32  WAC:Race:Two or More Races                                                      81 non-null     float64
 33  WAC:Ethnicity:Not Hispanic or Latino                                            81 non-null     float64
 34  WAC:Ethnicity:Hispanic or Latino                                                81 non-null     float64
 35  WAC:Ed:Less than High School                                                    81 non-null     float64
 36  WAC:Ed:High School or Equivalent                                                81 non-null     float64
 37  WAC:Ed:Some College or Associates                                               81 non-null     float64
 38  WAC:Ed:Bachelors or Advanced Degree                                             81 non-null     float64
 39  WAC:Sex:Male                                                                    81 non-null     float64
 40  WAC:Sex:Female                                                                  81 non-null     float64
 41  WAC:FirmAge:0 to 1 Year                                                         81 non-null     float64
 42  WAC:FirmAge:2 to 3 Years                                                        81 non-null     float64
 43  WAC:FirmAge:4 to 5 Years                                                        81 non-null     float64
 44  WAC:FirmAge:6 to 10 Years                                                       81 non-null     float64
 45  WAC:FirmAge:11 or More Years                                                    81 non-null     float64
 46  WAC:FirmSize:0 to 19 Employees                                                  81 non-null     float64
 47  WAC:FirmSize:20 to 49 Employees                                                 81 non-null     float64
 48  WAC:FirmSize:50 to 249 Employees                                                81 non-null     float64
 49  WAC:FirmSize:250 to 499 Employees                                               81 non-null     float64
 50  WAC:FirmSize:500 or More Employees                                              81 non-null     float64
 51  WAC:createdate                                                                  81 non-null     float64
 52  RAC:Total Jobs                                                                  81 non-null     float64
 53  RAC:Age:Workers 29 or Younger                                                   81 non-null     float64
 54  RAC:Age:Workers 30 to 54                                                        81 non-null     float64
 55  RAC:Age:Workers 55 Older                                                        81 non-null     float64
 56  RAC:Earnings:1250mo or Less                                                     81 non-null     float64
 57  RAC:Earnings:1251 to 3333mo                                                     81 non-null     float64
 58  RAC:Earnings:Greater Than 3333mo                                                81 non-null     float64
 59  RAC:NAICS:11Agriculture, Forestry, Fishing & Hunting                            81 non-null     float64
 60  RAC:NAICS:21Mining, Quarrying, Oil & Gas                                        81 non-null     float64
 61  RAC:NAICS:22Utilities                                                           81 non-null     float64
 62  RAC:NAICS:23Construction                                                        81 non-null     float64
 63  RAC:NAICS:31to33Manufacturing                                                   81 non-null     float64
 64  RAC:NAICS:42Wholesale Trade                                                     81 non-null     float64
 65  RAC:NAICS:44to45Retail Trade                                                    81 non-null     float64
 66  RAC:NAICS:48to49Transportation & Warehousing                                    81 non-null     float64
 67  RAC:NAICS:51Information                                                         81 non-null     float64
 68  RAC:NAICS:52Finance & Insurance                                                 81 non-null     float64
 69  RAC:NAICS:53Real Estate & Rental & Leasing                                      81 non-null     float64
 70  RAC:NAICS:54Professional, Scientific, & Technical Services                      81 non-null     float64
 71  RAC:NAICS:55Management of Companies & Enterprises                               81 non-null     float64
 72  RAC:NAICS:56Administrative & Support & Waste Management & Remediation Services  81 non-null     float64
 73  RAC:NAICS:61Educational Services                                                81 non-null     float64
 74  RAC:NAICS:62Healthcare & Social Assistance                                      81 non-null     float64
 75  RAC:NAICS:71Arts, Entertainment, & Recreation                                   81 non-null     float64
 76  RAC:NAICS:72Accommodation & Food Services                                       81 non-null     float64
 77  RAC:NAICS:81Other Services (Except Public Administration)                       81 non-null     float64
 78  RAC:NAICS:92Public Administration                                               81 non-null     float64
 79  RAC:Race:White Alone                                                            81 non-null     float64
 80  RAC:Race:Black or African American Alone                                        81 non-null     float64
 81  RAC:Race:American Indian or Alaska Native Alone                                 81 non-null     float64
 82  RAC:Race:Asian Alone                                                            81 non-null     float64
 83  RAC:Race:Native Hawaiian or Other Pacific Islander Alone                        81 non-null     float64
 84  RAC:Race:Two or More Races                                                      81 non-null     float64
 85  RAC:Ethnicity:Not Hispanic or Latino                                            81 non-null     float64
 86  RAC:Ethnicity:Hispanic or Latino                                                81 non-null     float64
 87  RAC:Ed:Less than High School                                                    81 non-null     float64
 88  RAC:Ed:High School or Equivalent                                                81 non-null     float64
 89  RAC:Ed:Some College or Associates                                               81 non-null     float64
 90  RAC:Ed:Bachelors or Advanced Degree                                             81 non-null     float64
 91  RAC:Sex:Male                                                                    81 non-null     float64
 92  RAC:Sex:Female                                                                  81 non-null     float64
 93  RAC:createdate                                                                  81 non-null     float64
dtypes: float64(94)
memory usage: 60.1+ KB

In [156]:
data = data.transpose().rename(columns = tnonlytocommon)
data = data.transpose().reset_index(drop = False)

In [160]:
data.rename(columns = {'index': 'NAME'}, inplace = True)

In [161]:
wacrac = data

In [162]:
wacrac = wacrac.drop(columns = ['RAC:createdate', 'WAC:createdate'])

In [163]:
wacrac.head()

,NAME,WAC:Total Jobs,WAC:Age:Workers 29 or Younger,WAC:Age:Workers 30 to 54,WAC:Age:Workers 55 Older,WAC:Earnings:1250mo or Less,WAC:Earnings:1251 to 3333mo,WAC:Earnings:Greater Than 3333mo,"WAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","WAC:NAICS:21Mining, Quarrying, Oil & Gas",WAC:NAICS:22Utilities,WAC:NAICS:23Construction,WAC:NAICS:31to33Manufacturing,WAC:NAICS:42Wholesale Trade,WAC:NAICS:44to45Retail Trade,WAC:NAICS:48to49Transportation & Warehousing,WAC:NAICS:51Information,WAC:NAICS:52Finance & Insurance,WAC:NAICS:53Real Estate & Rental & Leasing,"WAC:NAICS:54Professional, Scientific, & Technical Services",WAC:NAICS:55Management of Companies & Enterprises,WAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,WAC:NAICS:61Educational Services,WAC:NAICS:62Healthcare & Social Assistance,"WAC:NAICS:71Arts, Entertainment, & Recreation",WAC:NAICS:72Accommodation & Food Services,WAC:NAICS:81Other Services (Except Public Administration),WAC:NAICS:92Public Administration,WAC:Race:White Alone,WAC:Race:Black or African American Alone,WAC:Race:American Indian or Alaska Native Alone,WAC:Race:Asian Alone,WAC:Race:Native Hawaiian or Other Pacific Islander Alone,WAC:Race:Two or More Races,WAC:Ethnicity:Not Hispanic or Latino,WAC:Ethnicity:Hispanic or Latino,WAC:Ed:Less than High School,WAC:Ed:High School or Equivalent,WAC:Ed:Some College or Associates,WAC:Ed:Bachelors or Advanced Degree,WAC:Sex:Male,WAC:Sex:Female,WAC:FirmAge:0 to 1 Year,WAC:FirmAge:2 to 3 Years,WAC:FirmAge:4 to 5 Years,WAC:FirmAge:6 to 10 Years,WAC:FirmAge:11 or More Years,WAC:FirmSize:0 to 19 Employees,WAC:FirmSize:20 to 49 Employees,WAC:FirmSize:50 to 249 Employees,WAC:FirmSize:250 to 499 Employees,WAC:FirmSize:500 or More Employees,RAC:Total Jobs,RAC:Age:Workers 29 or Younger,RAC:Age:Workers 30 to 54,RAC:Age:Workers 55 Older,RAC:Earnings:1250mo or Less,RAC:Earnings:1251 to 3333mo,RAC:Earnings:Greater Than 3333mo,"RAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","RAC:NAICS:21Mining, Quarrying, Oil & Gas",RAC:NAICS:22Utilities,RAC:NAICS:23Construction,RAC:NAICS:31to33Manufacturing,RAC:NAICS:42Wholesale Trade,RAC:NAICS:44to45Retail Trade,RAC:NAICS:48to49Transportation & Warehousing,RAC:NAICS:51Information,RAC:NAICS:52Finance & Insurance,RAC:NAICS:53Real Estate & Rental & Leasing,"RAC:NAICS:54Professional, Scientific, & Technical Services",RAC:NAICS:55Management of Companies & Enterprises,RAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,RAC:NAICS:61Educational Services,RAC:NAICS:62Healthcare & Social Assistance,"RAC:NAICS:71Arts, Entertainment, & Recreation",RAC:NAICS:72Accommodation & Food Services,RAC:NAICS:81Other Services (Except Public Administration),RAC:NAICS:92Public Administration,RAC:Race:White Alone,RAC:Race:Black or African American Alone,RAC:Race:American Indian or Alaska Native Alone,RAC:Race:Asian Alone,RAC:Race:Native Hawaiian or Other Pacific Islander Alone,RAC:Race:Two or More Races,RAC:Ethnicity:Not Hispanic or Latino,RAC:Ethnicity:Hispanic or Latino,RAC:Ed:Less than High School,RAC:Ed:High School or Equivalent,RAC:Ed:Some College or Associates,RAC:Ed:Bachelors or Advanced Degree,RAC:Sex:Male,RAC:Sex:Female
0,Cheatham County,7918.0,1949.0,4255.0,1714.0,1433.0,2789.0,3696.0,4.0,0.0,44.0,784.0,2290.0,76.0,820.0,382.0,20.0,165.0,69.0,263.0,2.0,393.0,960.0,447.0,62.0,600.0,172.0,365.0,7053.0,638.0,30.0,103.0,13.0,81.0,7482.0,436.0,784.0,1981.0,1833.0,1371.0,4295.0,3623.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19706.0,4446.0,10549.0,4711.0,3016.0,6117.0,10573.0,25.0,11.0,133.0,1584.0,1888.0,951.0,2087.0,999.0,405.0,781.0,312.0,1245.0,388.0,1186.0,1545.0,2556.0,269.0,1518.0,605.0,1218.0,18645.0,599.0,67.0,162.0,11.0,222.0,19050.0,656.0,1601.0,4477.0,4908.0,4274.0,10195.0,9511.0
1,Davidson County,502956.0,122426.0,272971.0,107559.0,75893.0,147811.0,279252.0,261.0,182.0,1465.0,23603.0,21374.0,24395.0,42556.0,26896.0,14044.0,23276.0,10106.0,39811.0,10440.0,42852.0,35732.0,79295.0,9913.0,48083.0,16092.0,32580.0,379502.0,98611.0,1672.0,15302.0,378.0,7491.0,478049.0,24907.0,44391.0,102707.0,120150.0,113282.0,254052.0,248904.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,320699.0,89080.0,166883.0,64736.0,53939.0,101707.0,165053.0,274.0,114.0,619.0,11347.0,17313.0,12571.0,29901.0,15791.0,9440.0,15869.0,6404.0,25659.0,9120.0,27696.0,24984.0,47647.0,6292.0,34436.0,10274.0,14948.0,217362.0,84986.0,1035.0,11809.0,239.0,5268.0,301251.0,19448.0,29154.0,63582.0,72691.0,66192.0,157008.0,163691.0
2,Dickson County,16461.0,4195.0,8556.0,3710.0,3524.0,6460.0,6477.0,26.0,21.0,236.0,1022.0,3763.0,733.0,2226.0,178.0,105.0,441.0,85.0,246.0,130.0,1076.0,1017.0,2395.0,64.0,1574.0,367.0,756.0,14622.0,1379.0,58.0,206.0,10.0,186.0,15922.0,539.0,1554.0,4400.0,3842.0,2470.0,8593.0,7868.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23414.0,5599.0,12454.0,5361.0,4159.0,7975.0,11280.0,32.0,35.0,269.0,1905.0,3320.0,1018.0,2709.0,818.0,343.0,795.0,284.0,1153.0,367.0,1354.0,1511.0,3198.0,235.0,2118.0,639.0,1311.0,21510.0,1319.0,60.0,231.0,17.0,277.0,22660.0,754.0,1999.0,5609.0,5802.0,4405.0,12065.0,11349.0
3,Houston County,1272.0,274.0,669.0,329.0,316.0,524.0,432.0,5.0,0.0,5.0,101.0,170.0,0.0,154.0,4.0,10.0,42.0,3.0,27.0,0.0,2.0,221.0,313.0,0.0,90.0,13.0,112.0,1171.0,63.0,2.0,21.0,1.0,14.0,1249.0,23.0,95.0,360.0,338.0,205.0,502.0,770.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2915.0,690.0,1555.0,670.0,531.0,1161.0,1223.0,5.0,18.0,21.0,274.0,630.0,73.0,320.0,69.0,35.0,79.0,34.0,83.0,22.0,115.0,285.0,415.0,11.0,220.0,49.0,157.0,2734.0,109.0,8.0,27.0,1.0,36.0,2851.0,64.0,239.0,802.0,731.0,453.0,1490.0,1425.0
4,Humphreys County,5620.0,1225.0,2919.0,1476.0,1112.0,1828.0,2680.0,8.0,31.0,32.0,538.0,1566.0,88.0,627.0,336.0,16.0,94.0,6.0,85.0,0.0,162.0,577.0,512.0,14.0,490.0,184.0,254.0,5139.0,363.0,23.0,34.0,8.0,53.0,5500.0,120.0,447.0,1628.0,1416.0,904.0,3286.0,2334.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6743.0,1571.0,3559.0,1613.0,1233.0,2646.0,2864.0,17.0,28.0,35.0,493.0,1651.0,188.0,816.0,262.0,62.0,181.0,36.0,178.0,49.0,285.0,639.0,794.0,26.0,486.0,140.0,377.0,6363.0,248.0,25.0,38.0,7.0,62.0,6597.0,146.0,587.0,1840.0,1680.0,1065.0,3566.0,3177.0

In [164]:
wacrac['WAC:Age%:Workers 29 or Younger'] = percent(wacrac['WAC:Age:Workers 29 or Younger'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Age%:Workers 30 to 54'] = percent(wacrac['WAC:Age:Workers 30 to 54'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Age%:Workers 55 Older'] = percent(wacrac['WAC:Age:Workers 55 Older'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Earnings%:1250mo or Less'] = percent(wacrac['WAC:Earnings:1250mo or Less'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Earnings%:1251 to 3333mo'] = percent(wacrac['WAC:Earnings:1251 to 3333mo'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Earnings%:Greater Than 3333mo'] = percent(wacrac['WAC:Earnings:Greater Than 3333mo'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:11Agriculture, Forestry, Fishing & Hunting'] = percent(wacrac['WAC:NAICS:11Agriculture, Forestry, Fishing & Hunting'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:21Mining, Quarrying, Oil & Gas'] = percent(wacrac['WAC:NAICS:21Mining, Quarrying, Oil & Gas'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:22Utilities'] = percent(wacrac['WAC:NAICS:22Utilities'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:23Construction'] = percent(wacrac['WAC:NAICS:23Construction'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:31to33Manufacturing'] = percent(wacrac['WAC:NAICS:31to33Manufacturing'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:42Wholesale Trade'] = percent(wacrac['WAC:NAICS:42Wholesale Trade'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:44to45Retail Trade'] = percent(wacrac['WAC:NAICS:44to45Retail Trade'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:48to49Transportation & Warehousing'] = percent(wacrac['WAC:NAICS:48to49Transportation & Warehousing'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:51Information'] = percent(wacrac['WAC:NAICS:51Information'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:52Finance & Insurance'] = percent(wacrac['WAC:NAICS:52Finance & Insurance'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:48to49Transportation & Warehousing'] = percent(wacrac['WAC:NAICS:48to49Transportation & Warehousing'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:51Information'] = percent(wacrac['WAC:NAICS:51Information'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:52Finance & Insurance'] = percent(wacrac['WAC:NAICS:52Finance & Insurance'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:53Real Estate & Rental & Leasing'] = percent(wacrac['WAC:NAICS:53Real Estate & Rental & Leasing'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:54Professional, Scientific, & Technical Services'] = percent(wacrac['WAC:NAICS:54Professional, Scientific, & Technical Services'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:55Management of Companies & Enterprises'] = percent(wacrac['WAC:NAICS:55Management of Companies & Enterprises'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:56Administrative & Support & Waste Management & Remediation Services'] = percent(wacrac['WAC:NAICS:56Administrative & Support & Waste Management & Remediation Services'], 
                                                                                             wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:61Educational Services'] = percent(wacrac['WAC:NAICS:61Educational Services'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:62Healthcare & Social Assistance'] = percent(wacrac['WAC:NAICS:62Healthcare & Social Assistance'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:71Arts, Entertainment, & Recreation'] = percent(wacrac['WAC:NAICS:71Arts, Entertainment, & Recreation'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:72Accommodation & Food Services'] = percent(wacrac['WAC:NAICS:72Accommodation & Food Services'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:81Other Services (Except Public Administration)'] = percent(wacrac['WAC:NAICS:81Other Services (Except Public Administration)'], 
                                                                               wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:92Public Administration'] = percent(wacrac['WAC:NAICS:92Public Administration'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Race%:White Alone'] = percent(wacrac['WAC:Race:White Alone'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Race%:Black or African American Alone'] = percent(wacrac['WAC:Race:Black or African American Alone'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Race%:American Indian or Alaska Native Alone'] = percent(wacrac['WAC:Race:American Indian or Alaska Native Alone'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Race%:Asian Alone'] = percent(wacrac['WAC:Race:Asian Alone'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Race%:Native Hawaiian or Other Pacific Islander Alone'] = percent(wacrac['WAC:Race:Native Hawaiian or Other Pacific Islander Alone'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Race%:Two or More Races'] = percent(wacrac['WAC:Race:Two or More Races'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Ethnicity%:Not Hispanic or Latino'] = percent(wacrac['WAC:Ethnicity:Not Hispanic or Latino'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Ethnicity%:Hispanic or Latino'] = percent(wacrac['WAC:Ethnicity:Hispanic or Latino'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Ed%:Less than High School'] = percent(wacrac['WAC:Ed:Less than High School'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Ed%:High School or Equivalent'] = percent(wacrac['WAC:Ed:High School or Equivalent'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Ed%:Some College or Associates'] = percent(wacrac['WAC:Ed:Some College or Associates'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Ed%:Bachelors or Advanced Degree'] = percent(wacrac['WAC:Ed:Bachelors or Advanced Degree'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Sex%:Male'] = percent(wacrac['WAC:Sex:Male'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Sex%:Female'] = percent(wacrac['WAC:Sex:Female'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmAge%:0 to 1 Year'] = percent(wacrac['WAC:FirmAge:0 to 1 Year'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmAge%:2 to 3 Years'] = percent(wacrac['WAC:FirmAge:2 to 3 Years'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmAge%:4 to 5 Years'] = percent(wacrac['WAC:FirmAge:4 to 5 Years'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmAge%:6 to 10 Years'] = percent(wacrac['WAC:FirmAge:6 to 10 Years'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmAge%:11 or More Years'] = percent(wacrac['WAC:FirmAge:11 or More Years'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmSize%:0 to 19 Employees'] = percent(wacrac['WAC:FirmSize:0 to 19 Employees'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmSize%:20 to 49 Employees'] = percent(wacrac['WAC:FirmSize:20 to 49 Employees'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmSize%:50 to 249 Employees'] = percent(wacrac['WAC:FirmSize:50 to 249 Employees'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmSize%:250 to 499 Employees'] = percent(wacrac['WAC:FirmSize:250 to 499 Employees'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmSize%:500 or More Employees'] = percent(wacrac['WAC:FirmSize:500 or More Employees'], wacrac['WAC:Total Jobs'])

In [165]:
wacrac['RAC:Age%:Workers 29 or Younger'] = percent(wacrac['RAC:Age:Workers 29 or Younger'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Age%:Workers 30 to 54'] = percent(wacrac['RAC:Age:Workers 30 to 54'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Age%:Workers 55 Older'] = percent(wacrac['RAC:Age:Workers 55 Older'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Earnings%:1250mo or Less'] = percent(wacrac['RAC:Earnings:1250mo or Less'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Earnings%:1251 to 3333mo'] = percent(wacrac['RAC:Earnings:1251 to 3333mo'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Earnings%:Greater Than 3333mo'] = percent(wacrac['RAC:Earnings:Greater Than 3333mo'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:11Agriculture, Forestry, Fishing & Hunting'] = percent(wacrac['RAC:NAICS:11Agriculture, Forestry, Fishing & Hunting'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:21Mining, Quarrying, Oil & Gas'] = percent(wacrac['RAC:NAICS:21Mining, Quarrying, Oil & Gas'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:22Utilities'] = percent(wacrac['RAC:NAICS:22Utilities'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:23Construction'] = percent(wacrac['RAC:NAICS:23Construction'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:31to33Manufacturing'] = percent(wacrac['RAC:NAICS:31to33Manufacturing'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:42Wholesale Trade'] = percent(wacrac['RAC:NAICS:42Wholesale Trade'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:44to45Retail Trade'] = percent(wacrac['RAC:NAICS:44to45Retail Trade'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:48to49Transportation & Warehousing'] = percent(wacrac['RAC:NAICS:48to49Transportation & Warehousing'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:51Information'] = percent(wacrac['RAC:NAICS:51Information'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:52Finance & Insurance'] = percent(wacrac['RAC:NAICS:52Finance & Insurance'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:48to49Transportation & Warehousing'] = percent(wacrac['RAC:NAICS:48to49Transportation & Warehousing'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:51Information'] = percent(wacrac['RAC:NAICS:51Information'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:52Finance & Insurance'] = percent(wacrac['RAC:NAICS:52Finance & Insurance'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:53Real Estate & Rental & Leasing'] = percent(wacrac['RAC:NAICS:53Real Estate & Rental & Leasing'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:54Professional, Scientific, & Technical Services'] = percent(wacrac['RAC:NAICS:54Professional, Scientific, & Technical Services'], 
                                                                                wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:55Management of Companies & Enterprises'] = percent(wacrac['RAC:NAICS:55Management of Companies & Enterprises'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:56Administrative & Support & Waste Management & Remediation Services'] = percent(wacrac['RAC:NAICS:56Administrative & Support & Waste Management & Remediation Services'], 
                                                                                             wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:61Educational Services'] = percent(wacrac['RAC:NAICS:61Educational Services'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:62Healthcare & Social Assistance'] = percent(wacrac['RAC:NAICS:62Healthcare & Social Assistance'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:71Arts, Entertainment, & Recreation'] = percent(wacrac['RAC:NAICS:71Arts, Entertainment, & Recreation'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:72Accommodation & Food Services'] = percent(wacrac['RAC:NAICS:72Accommodation & Food Services'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:81Other Services (Except Public Administration)'] = percent(wacrac['RAC:NAICS:81Other Services (Except Public Administration)'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:92Public Administration'] = percent(wacrac['RAC:NAICS:92Public Administration'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Race%:White Alone'] = percent(wacrac['RAC:Race:White Alone'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Race%:Black or African American Alone'] = percent(wacrac['RAC:Race:Black or African American Alone'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Race%:American Indian or Alaska Native Alone'] = percent(wacrac['RAC:Race:American Indian or Alaska Native Alone'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Race%:Asian Alone'] = percent(wacrac['RAC:Race:Asian Alone'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Race%:Native Hawaiian or Other Pacific Islander Alone'] = percent(wacrac['RAC:Race:Native Hawaiian or Other Pacific Islander Alone'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Race%:Two or More Races'] = percent(wacrac['RAC:Race:Two or More Races'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Ethnicity%:Not Hispanic or Latino'] = percent(wacrac['RAC:Ethnicity:Not Hispanic or Latino'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Ethnicity%:Hispanic or Latino'] = percent(wacrac['RAC:Ethnicity:Hispanic or Latino'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Ed%:Less than High School'] = percent(wacrac['RAC:Ed:Less than High School'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Ed%:High School or Equivalent'] = percent(wacrac['RAC:Ed:High School or Equivalent'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Ed%:Some College or Associates'] = percent(wacrac['RAC:Ed:Some College or Associates'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Ed%:Bachelors or Advanced Degree'] = percent(wacrac['RAC:Ed:Bachelors or Advanced Degree'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Sex%:Male'] = percent(wacrac['RAC:Sex:Male'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Sex%:Female'] = percent(wacrac['RAC:Sex:Female'], wacrac['RAC:Total Jobs'])

In [166]:
wacrac.head()

,NAME,WAC:Total Jobs,WAC:Age:Workers 29 or Younger,WAC:Age:Workers 30 to 54,WAC:Age:Workers 55 Older,WAC:Earnings:1250mo or Less,WAC:Earnings:1251 to 3333mo,WAC:Earnings:Greater Than 3333mo,"WAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","WAC:NAICS:21Mining, Quarrying, Oil & Gas",WAC:NAICS:22Utilities,WAC:NAICS:23Construction,WAC:NAICS:31to33Manufacturing,WAC:NAICS:42Wholesale Trade,WAC:NAICS:44to45Retail Trade,WAC:NAICS:48to49Transportation & Warehousing,WAC:NAICS:51Information,WAC:NAICS:52Finance & Insurance,WAC:NAICS:53Real Estate & Rental & Leasing,"WAC:NAICS:54Professional, Scientific, & Technical Services",WAC:NAICS:55Management of Companies & Enterprises,WAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,WAC:NAICS:61Educational Services,WAC:NAICS:62Healthcare & Social Assistance,"WAC:NAICS:71Arts, Entertainment, & Recreation",WAC:NAICS:72Accommodation & Food Services,WAC:NAICS:81Other Services (Except Public Administration),WAC:NAICS:92Public Administration,WAC:Race:White Alone,WAC:Race:Black or African American Alone,WAC:Race:American Indian or Alaska Native Alone,WAC:Race:Asian Alone,WAC:Race:Native Hawaiian or Other Pacific Islander Alone,WAC:Race:Two or More Races,WAC:Ethnicity:Not Hispanic or Latino,WAC:Ethnicity:Hispanic or Latino,WAC:Ed:Less than High School,WAC:Ed:High School or Equivalent,WAC:Ed:Some College or Associates,WAC:Ed:Bachelors or Advanced Degree,WAC:Sex:Male,WAC:Sex:Female,WAC:FirmAge:0 to 1 Year,WAC:FirmAge:2 to 3 Years,WAC:FirmAge:4 to 5 Years,WAC:FirmAge:6 to 10 Years,WAC:FirmAge:11 or More Years,WAC:FirmSize:0 to 19 Employees,WAC:FirmSize:20 to 49 Employees,WAC:FirmSize:50 to 249 Employees,WAC:FirmSize:250 to 499 Employees,WAC:FirmSize:500 or More Employees,RAC:Total Jobs,RAC:Age:Workers 29 or Younger,RAC:Age:Workers 30 to 54,RAC:Age:Workers 55 Older,RAC:Earnings:1250mo or Less,RAC:Earnings:1251 to 3333mo,RAC:Earnings:Greater Than 3333mo,"RAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","RAC:NAICS:21Mining, Quarrying, Oil & Gas",RAC:NAICS:22Utilities,RAC:NAICS:23Construction,RAC:NAICS:31to33Manufacturing,RAC:NAICS:42Wholesale Trade,RAC:NAICS:44to45Retail Trade,RAC:NAICS:48to49Transportation & Warehousing,RAC:NAICS:51Information,RAC:NAICS:52Finance & Insurance,RAC:NAICS:53Real Estate & Rental & Leasing,"RAC:NAICS:54Professional, Scientific, & Technical Services",RAC:NAICS:55Management of Companies & Enterprises,RAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,RAC:NAICS:61Educational Services,RAC:NAICS:62Healthcare & Social Assistance,"RAC:NAICS:71Arts, Entertainment, & Recreation",RAC:NAICS:72Accommodation & Food Services,RAC:NAICS:81Other Services (Except Public Administration),RAC:NAICS:92Public Administration,RAC:Race:White Alone,RAC:Race:Black or African American Alone,RAC:Race:American Indian or Alaska Native Alone,RAC:Race:Asian Alone,RAC:Race:Native Hawaiian or Other Pacific Islander Alone,RAC:Race:Two or More Races,RAC:Ethnicity:Not Hispanic or Latino,RAC:Ethnicity:Hispanic or Latino,RAC:Ed:Less than High School,RAC:Ed:High School or Equivalent,RAC:Ed:Some College or Associates,RAC:Ed:Bachelors or Advanced Degree,RAC:Sex:Male,RAC:Sex:Female,WAC:Age%:Workers 29 or Younger,WAC:Age%:Workers 30 to 54,WAC:Age%:Workers 55 Older,WAC:Earnings%:1250mo or Less,WAC:Earnings%:1251 to 3333mo,WAC:Earnings%:Greater Than 3333mo,"WAC:NAICS%:11Agriculture, Forestry, Fishing & Hunting","WAC:NAICS%:21Mining, Quarrying, Oil & Gas",WAC:NAICS%:22Utilities,WAC:NAICS%:23Construction,WAC:NAICS%:31to33Manufacturing,WAC:NAICS%:42Wholesale Trade,WAC:NAICS%:44to45Retail Trade,WAC:NAICS%:48to49Transportation & Warehousing,WAC:NAICS%:51Information,WAC:NAICS%:52Finance & Insurance,WAC:NAICS%:53Real Estate & Rental & Leasing,"WAC:NAICS%:54Professional, Scientific, & Technical Services",WAC:NAICS%:55Management of Companies & Enterprises,WAC:NAICS%:56Administrative & Support & Waste Management & Remediation Services,WAC:NAICS%:61Educational Services,WAC:NAICS%:62Healthcare & Social Assistance,"WAC:NAICS%:71Arts, Entertainment, & Recreation",WAC:NAICS%:72Accommodation & Food Services,WAC:NAICS%:81Other Services (Except Public Administration),WAC:NAICS%:92Public Administration,WAC:Race%:White Alone,WAC:Race%:Black or African American Alone,WAC:Race%:American Indian or Alaska Native Alone,WAC:Race%:Asian Alone,WAC:Race%:Native Hawaiian or Other Pacific Islander Alone,WAC:Race%:Two or More Races,WAC:Ethnicity%:Not Hispanic or Latino,WAC:Ethnicity%:Hispanic or Latino,WAC:Ed%:Less than High School,WAC:Ed%:High School or Equivalent,WAC:Ed%:Some College or Associates,WAC:Ed%:Bachelors or Advanced Degree,WAC:Sex%:Male,WAC:Sex%:Female,WAC:FirmAge%:0 to 1 Year,WAC:FirmAge%:2 to 3 Years,WAC:FirmAge%:4 to 5 Years,WAC:FirmAge%:6 to 10 Years,WAC:FirmAge%:11 or More Years,WAC:FirmSize%:0 to 19 Employees,WAC:FirmSize%:20 to 49 Employees,WAC:FirmSize%:50 to 249 Employees,WAC:FirmSize%:250 to 499 Employees,WAC:FirmSize%:500 or More Employees,RAC:Age%:Workers 29 or Younger,RAC:Age%:Workers 30 to 54,RAC:Age%:Workers 55 Older,RAC:Earnings%:1250mo or Less,RAC:Earnings%:1251 to 3333mo,RAC:Earnings%:Greater Than 3333mo,"RAC:NAICS%:11Agriculture, Forestry, Fishing & Hunting","RAC:NAICS%:21Mining, Quarrying, Oil & Gas",RAC:NAICS%:22Utilities,RAC:NAICS%:23Construction,RAC:NAICS%:31to33Manufacturing,RAC:NAICS%:42Wholesale Trade,RAC:NAICS%:44to45Retail Trade,RAC:NAICS%:48to49Transportation & Warehousing,RAC:NAICS%:51Information,RAC:NAICS%:52Finance & Insurance,RAC:NAICS%:53Real Estate & Rental & Leasing,"RAC:NAICS%:54Professional, Scientific, & Technical Services",RAC:NAICS%:55Management of Companies & Enterprises,RAC:NAICS%:56Administrative & Support & Waste Management & Remediation Services,RAC:NAICS%:61Educational Services,RAC:NAICS%:62Healthcare & Social Assistance,"RAC:NAICS%:71Arts, Entertainment, & Recreation",RAC:NAICS%:72Accommodation & Food Services,RAC:NAICS%:81Other Services (Except Public Administration),RAC:NAICS%:92Public Administration,RAC:Race%:White Alone,RAC:Race%:Black or African American Alone,RAC:Race%:American Indian or Alaska Native Alone,RAC:Race%:Asian Alone,RAC:Race%:Native Hawaiian or Other Pacific Islander Alone,RAC:Race%:Two or More Races,RAC:Ethnicity%:Not Hispanic or Latino,RAC:Ethnicity%:Hispanic or Latino,RAC:Ed%:Less than High School,RAC:Ed%:High School or Equivalent,RAC:Ed%:Some College or Associates,RAC:Ed%:Bachelors or Advanced Degree,RAC:Sex%:Male,RAC:Sex%:Female
0,Cheatham County,7918.0,1949.0,4255.0,1714.0,1433.0,2789.0,3696.0,4.0,0.0,44.0,784.0,2290.0,76.0,820.0,382.0,20.0,165.0,69.0,263.0,2.0,393.0,960.0,447.0,62.0,600.0,172.0,365.0,7053.0,638.0,30.0,103.0,13.0,81.0,7482.0,436.0,784.0,1981.0,1833.0,1371.0,4295.0,3623.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19706.0,4446.0,10549.0,4711.0,3016.0,6117.0,10573.0,25.0,11.0,133.0,1584.0,1888.0,951.0,2087.0,999.0,405.0,781.0,312.0,1245.0,388.0,1186.0,1545.0,2556.0,269.0,1518.0,605.0,1218.0,18645.0,599.0,67.0,162.0,11.0,222.0,19050.0,656.0,1601.0,4477.0,4908.0,4274.0,10195.0,9511.0,24.614802,53.738318,21.646881,18.098005,35.223541,46.678454,0.050518,0.000000,0.555696,9.901490,28.921445,0.959838,10.356151,4.824451,0.252589,2.083860,0.871432,3.321546,0.025259,4.963375,12.124274,5.645365,0.783026,7.577671,2.172266,4.609750,89.075524,8.057590,0.378884,1.300834,0.164183,1.022986,94.493559,5.506441,9.901490,25.018944,23.149785,17.314979,54.243496,45.756504,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.561656,53.531919,23.906424,15.304983,31.041307,53.653710,0.126865,0.055821,0.674921,8.038161,9.580838,4.825941,10.590683,5.069522,2.055212,3.963260,1.583274,6.317873,1.968943,6.018472,7.840252,12.970669,1.365066,7.703238,3.070131,6.180859,94.615853,3.039683,0.339998,0.822085,0.055821,1.126560,96.671065,3.328935,8.124429,22.718969,24.906120,21.688826,51.735512,48.264488
1,Davidson County,502956.0,122426.0,272971.0,107559.0,75893.0,147811.0,279252.0,261.0,182.0,1465.0,23603.0,21374.0,24395.0,42556.0,26896.0,14044.0,23276.0,10106.0,39811.0,10440.0,42852.0,35732.0,79295.0,9913.0,48083.0,16092.0,32580.0,379502.0,98611.0,1672.0,15302.0,378.0,7491.0,478049.0,24907.0,44391.0,102707.0,120150.0,113282.0,254052.0,248904.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,320699.0,89080.0,166883.0,64736.0,53939.0,101707.0,165053.0,274.0,114.0,619.0,11347.0,17313.0,12571.0,29901.0,15791.0,9440.0,15869.0,6404.0,25659.0,9120.0,27696.0,24984.0,47647.0,6292.0,34436.0,10274.0,14948.0,217362.0,84986.0,1035.0,11809.0,239.0,5268.0,301251.0,19448.0,29154.0,63582.0,72691.0,66192.0,157008.0,163691.0,24.341294,54.273336,21.385370,15.089392,29.388455,55.522153,0.051893,0.036186,0.291278,4.692856,4.249676,4.850325,8.461178,5.347585,2.792292,4.627840,2.009321,7.915404,2.075728,8.520030,7.104399,15.765793,1.970948,9.560081,3.199485,6.477704,75.454314,19.606288,0.332435,3.042413,0.075156,1.489395,95.047877,4.952123,8.826021,20.420673,23.888770,22.523243,50.511774,49.488226,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.776825,52.037269,20.185906,16.819198,31.714162,51.466640,0.085438,0.035547,0.193016,3.538209,5.398520,3.919875,9.323696,4.923932,2.943570,4.948254,1.996888,8.000960,2.843788,8.636135,7.790483,14.857234,1.961964,10.737795,3.203627,4.661068,67.777573,26.500239,0.322733,3.682269,0.074525,1.642662,93.935747,6.064253,9.090767,19.826067,22.666426,20.639915,48.958057,51.041943
2,Dickson County,16461.0,4195.0,8556.0,3710.0,3524.0,6460.0,6477.0,26.0,21.0,236.0,1022.0,3763.0,733.0,2226.0,178.0,105.0,441.0,85.0,246.0,130.0,1076.0,1017.0,2395.0,64.0,1574.0,367.0,756.0,14622.0,1379.0,58.0,206.0,10.0,186.0,15922.0,539.0,1554.0,4400.0,3842.0,2470.0,8593.0,7868.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23414.0,5599.0,12454.0,5361.0,4159.0,7975.0,11280.0,32.0,35.0,269.0,1905.0,3320.0,1018.0,2709.0,818.0,343.0,795.0,284.0,1153.0,367.0,1354.0,1511.0,3198.0,235.0,2118.0,639.0,1311.0,21510.0,1319.0,60.0,231.0,17.0,277.0,22660.0,754.0,1999.0,5609.0,5802.0,4405.0,12065.0,11349.0,25.484478,51.977401,22.538120,21.408177,39.244274,39.347549,0.157949,0.127574,1.433692,6.208614,22.860094,4.452949,13.522872,1.081344,0.637871,2.679060,0.516372,1.494441,0.789745,6.536662,6.178239,14.549541,0.388798,9.561995,2.229512,4.592674,88.828139,8.377377,0.352348,1.251443,0.060750,1.129944,96.725594,3.274406,9.440496,26.729846,23.340016,15.005164,52.202175,47.797825,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.913043,53.190399,22.896558,17.762877,34.060818,48.176305,0.136670,0.149483,1.148885,8.136158,14.179551,4.347826,11.570001,3.493636,1.464936,3.395404,1.212950,4.924404,1.567438,5.782865,6.453404,13.658495,1.003673,9.045870,2.729136,5.599214,91.868113,5.633382,0.256257,0.986589,0.072606,1.183053,96.779704,3.220296,8.537627,23.955753,24.780046,18.813530,51.529000,48.471000
3,Houston County,1272.0,274.0,669.0,329.0,316.0,524.0,432.0,5.0,0.0,5.0,101.0,170.0,0.0,154.0,4.0,10.0,42.0,3.0,27.0,0.0,2.0,221.0,313.0,0.0,90.0,13.0,112.0,1171.0,63.0,2.0,21.0,1.0,14.0,1249.0,23.0,95.0,360.0,338.0,205.0,502.0,770.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2915.0,690.0,1555.0,670.0,531.0,1161.0,1223.0,5.0,18.0,21.0,274.0,630.0,73.0,320.0,69.0,35.0,79.0,34.0,83.0,22.0,115.0,285.0,415.0,11.0,220.0,49.0,157.0,2734.0,109.0,8.0,27.0,1.0,36.0,2851.0,64.0,239.0,802.0,731.0,453.0,1490.0,1425.0,21.540881,52.594340,25.864780,24.842767,41.194969,33.962264,0.393082,0.000000,0.393082,7.940252,13.364780,0.000000,12.106918,0.314465,0.786164,3.301887,0.235849,2.122642,0.000000,0.157233,17.374214,24.606918,0.000000,7.075472,1.022013,8.805031,92.059748,4.952830,0.157233,1.650943,0.078616,1.100629,98.191824,1.808176,7.468553,28.301887,26.572327,16.116352,39.465409,60.534591,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.670669,53.344768,22.984563,18.216123,39.828473,41.955403,0.171527,0.617496,0.720412,9.399657,21.612350,2.504288,10.977702,2.367067,1.200686,2.710120,1.166381,2.847341,0.754717,3.945111,9.777015,14.236707,0.377358,7.547170,1.680961,5.385935,93.790738,3.739280,0.274443,0.926244,0.034305,1.234991,97.804460,2.195540,8.198971,27.512864,25.077187,15.540309,51.114923,48.885077
4,Humphreys County,5620.0,1225.0,2919.0,1476.0,1112.0,1828.0,2680.0,8.0,31.0,32.0,538.0,1566.0,88.0,627.0,336.0,16.0,94.0,6.0,85.0,0.0,162.0,577.0,512.0,14.0,490.0,184.0,254.0,5139.0,363.0,23.0,34.0,8.0,53.0,5500.0,120.0,447.0,1628.0,1416.0,904.0,3286.0,2334.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6743.0,1571.0,3559.0,1613.0,1233.0,2646.0,2864.0,17.0,28.0,35.0,493.0,1651.0,188.0,816.0,262.0,62.0,181.0,36.0,178.0,49.0,285.0,639.0,794.0,26.0,486.0,140.0,377.0,6363.0,248.0,25.0,38.0,7.0,62.0,6597.0,146.0,587.0,1840.0,1680.0,1065.0,3566.0,3177.0,21.797153,51.939502,26.263345,19.786477,32.526690,47.686833,0.142349,0.551601,0.569395,9.572954,27.864769,1.565836,11.156584,5.978648,0.284698,1.672598,0.106762,1.512456,0.000000,2.882562,10.266904,9.110320,0.249110,8.718861,3.274021,4.519573,91.441281,6.459075,0.409253,0.604982,0.142349,0.943060,97.864769,2.135231,7.953737,28.967972,25.195730,16.085409,58.469751,41.530249,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.298235,52.780661,23.921103,18.285630,39.240694,42.473676,0.252113,0.415245,0.519057,7.311286,24.484651,2.788077,12.101439,3.885511,0.919472,2.684265,0.533887,2.639775,0.726680,4.226605,9.476494,11.775174,0.385585,7.207474,2.076227,5.590983,94.364526,3.677888,0.370755,0.563547,0.103811,0.919472,97.834792,2.165208,8.705324,27.287557,24.914726,15.794157,52.884473,47.115527

In [167]:
wacrac.NAME.unique()

array(['Cheatham County', 'Davidson County', 'Dickson County',
       'Houston County', 'Humphreys County', 'Maury County',
       'Montgomery County', 'Robertson County', 'Rutherford County',
       'Stewart County', 'Sumner County', 'Trousdale County',
       'Williamson County', 'Wilson County', 'Adams', 'Ashland City',
       'Belle Meade', 'Berry Hill', 'Brentwood', 'Burns', 'Cedar Hill',
       'Charlotte', 'Clarksville', 'Columbia', 'Coopertown',
       'Cross Plains', 'Cumberland City', 'Dickson', 'Dover',
       'Eagleville', 'Erin', 'Fairview', 'Forest Hills', 'Franklin',
       'Gallatin', 'Goodlettsville', 'Greenbrier',
       'Hartsville/Trousdale County, TN', 'Hendersonville',
       'Kingston Springs', 'La Vergne', 'Lebanon', 'McEwen',
       'Millersville', 'Mitchellville', 'Mount Juliet', 'Mount Pleasant',
       'Murfreesboro', 'Nashville', 'New Johnsonville', 'Nolensville',
       'Oak Hill', 'Orlinda city, TN', 'Pegram', 'Pleasant View',
       'Portland', 'Ridgetop', 'Slayden', 'Smyrna', 'Spring Hill',
       'Springfield', 'Tennessee Ridge', "Thompson's Station", 'Vanleer',
       'Watertown', 'Waverly', 'Westmoreland', 'White Bluff',
       'White House'], dtype=object)

In [200]:
wacrac.to_feather('../../Outputs/LEHD_WacRac')

## Origin-Destination

In [188]:
#all primary jobs
url = 'https://lehd.ces.census.gov/data/lodes/LODES7/tn/od/tn_od_main_JT01_2019.csv.gz'
od = pd.read_csv(url)
print('Your file is ready.')

Your file is ready.

In [189]:
odcols = {'h_geocode': 'HOMEGEO_ID', 'w_geocode': 'WORKGEO_ID', 'S000': 'Total Jobs', 'SA01': 'Age:Workers 29 or Younger', 'SA02': 'Age:Workers 30 to 54', 
          'SA03': 'Age:Workers 55 Older', 'SE01': 'Earnings:1250mo or Less', 'SE02': 'Earnings:1251 to 3333mo', 'SE03': 'Earnings:Greater Than 3333mo', 
          'SI01': 'Sector:Goods Producing', 'SI02': 'Sector:Trade, Transportation & Utilities', 'SI03': 'Sector:All Other Services'}

In [190]:
od.rename(columns = odcols, inplace = True)

In [192]:
od.head(2)

,WORKGEO_ID,HOMEGEO_ID,Total Jobs,Age:Workers 29 or Younger,Age:Workers 30 to 54,Age:Workers 55 Older,Earnings:1250mo or Less,Earnings:1251 to 3333mo,Earnings:Greater Than 3333mo,Sector:Goods Producing,"Sector:Trade, Transportation & Utilities",Sector:All Other Services,createdate
0,470010201001000,470010201001063,2,1,1,0,0,1,1,0,0,2,20211018
1,470010201001000,470010201002013,1,0,0,1,1,0,0,0,0,1,20211018

In [193]:
od['WORKGEO_ID'] = od['WORKGEO_ID'].astype(str)
od['HOMEGEO_ID'] = od['HOMEGEO_ID'].astype(str)

In [194]:
#add columns with county name and place name respectively
od['Home County'] = od['HOMEGEO_ID'].map(c_inverted)
od['Home Incorporated'] = od['HOMEGEO_ID'].map(un_inverted)
od['Home Place'] = od['HOMEGEO_ID'].map(p_inverted)

od['Work County'] = od['WORKGEO_ID'].map(c_inverted)
od['Work Incorporated'] = od['WORKGEO_ID'].map(un_inverted)
od['Work Place'] = od['WORKGEO_ID'].map(p_inverted)

In [195]:
od['Home County'] = od['Home County'].str.get(0)
od['Home Incorporated'] = od['Home Incorporated'].str.get(0)
od['Home Place'] = od['Home Place'].str.get(0)

od['Work County'] = od['Work County'].str.get(0)
od['Work Incorporated'] = od['Work Incorporated'].str.get(0)
od['Work Place'] = od['Work Place'].str.get(0)

In [196]:
test = od['Home County'].str.split(pat = ",", expand = True)
od['Home County'] = test[0]
test = od['Work County'].str.split(pat = ",", expand = True)
od['Work County'] = test[0]

In [197]:
test = od['Home Place'].str.split(pat = ",", expand = True)
od['Home Place'] = test[0]
test = od['Work Place'].str.split(pat = ",", expand = True)
od['Work Place'] = test[0]

In [204]:
od = od.replace({'Adams city': 'Adams', 'Ashland City town': 'Ashland City', 'Belle Meade city': 'Belle Meade', 
                                  'Berry Hill city': 'Berry Hill', 'Brentwood city': 'Brentwood', 'Burns town': 'Burns', 
                                  'Cedar Hill city': 'Cedar Hill', 'Charlotte town': 'Charlotte', 'Clarksville city': 'Clarksville', 
                                  'Columbia city': 'Columbia', 'Coopertown town': 'Coopertown', 'Cross Plains city': 'Cross Plains', 
                                  'Cumberland City town': 'Cumberland City', 'Dickson city': 'Dickson', 'Dover city': 'Dover', 
                                  'Eagleville city': 'Eagleville', 'Erin city': 'Erin', 'Fairview city': 'Fairview', 
                                  'Forest Hills city': 'Forest Hills', 'Franklin city': 'Franklin', 'Gallatin city': 'Gallatin', 
                                  'Goodlettsville city': 'Goodlettsville', 'Greenbrier town': 'Greenbrier', 
                                  'Hendersonville city': 'Hendersonville', 'Kingston Springs town': 'Kingston Springs', 
                                  'La Vergne city': 'La Vergne', 'Lafayette city': 'Lafayette', 'Lebanon city': 'Lebanon', 
                                  'McEwen city': 'McEwen', 'Millersville city': 'Millersville', 'Mitchellville city': 'Mitchellville', 
                                  'Mount Juliet city': 'Mount Juliet', 'Mount Pleasant city': 'Mount Pleasant', 
                                  'Murfreesboro city': 'Murfreesboro', 'Nashville-Davidson metropolitan government (balance)': 'Nashville', 
                                  'New Johnsonville city': 'New Johnsonville', 'Nolensville town': 'Nolensville', 
                                  'Oak Hill city': 'Oak Hill', 'Pegram town': 'Pegram', 'Pleasant View city': 'Pleasant View', 
                                  'Portland city': 'Portland', 'Ridgetop city': 'Ridgetop', 'Slayden town': 'Slayden', 
                                  'Smyrna town': 'Smyrna', 'Spring Hill city': 'Spring Hill', 'Springfield city': 'Springfield', 
                                  'Tennessee Ridge town': 'Tennessee Ridge', "Thompson's Station town": "Thompson's Station", 
                                  'Vanleer town': 'Vanleer', 'Watertown city': 'Watertown', 'Waverly city': 'Waverly', 
                                  'Westmoreland town': 'Westmoreland', 'White Bluff town': 'White Bluff', 
                                  'White House city': 'White House', 'Orlinda city': 'Orlinda'})

In [208]:
od.tail()

,WORKGEO_ID,HOMEGEO_ID,Total Jobs,Age:Workers 29 or Younger,Age:Workers 30 to 54,Age:Workers 55 Older,Earnings:1250mo or Less,Earnings:1251 to 3333mo,Earnings:Greater Than 3333mo,Sector:Goods Producing,"Sector:Trade, Transportation & Utilities",Sector:All Other Services,Home County,Home Incorporated,Home Place,Work County,Work Incorporated,Work Place
2273806,471890310004055,471890310002017,1,1,0,0,1,0,0,0,1,0,Wilson County,None,NaN,Wilson County,NaN,Watertown
2273807,471890310004055,471890310002089,1,0,0,1,1,0,0,0,0,1,Wilson County,None,NaN,Wilson County,NaN,Watertown
2273808,471890310004055,471890310002120,1,1,0,0,0,1,0,0,1,0,Wilson County,None,NaN,Wilson County,NaN,Watertown
2273809,471890310004055,471890310003068,1,0,0,1,0,1,0,0,1,0,Wilson County,NaN,Watertown,Wilson County,NaN,Watertown
2273810,471890310004055,471890310004038,1,0,1,0,1,0,0,0,1,0,Wilson County,NaN,Watertown,Wilson County,NaN,Watertown

In [210]:
od = od.drop(columns = 'createdate')

In [211]:
od.head()

,WORKGEO_ID,HOMEGEO_ID,Total Jobs,Age:Workers 29 or Younger,Age:Workers 30 to 54,Age:Workers 55 Older,Earnings:1250mo or Less,Earnings:1251 to 3333mo,Earnings:Greater Than 3333mo,Sector:Goods Producing,"Sector:Trade, Transportation & Utilities",Sector:All Other Services,Home County,Home Incorporated,Home Place,Work County,Work Incorporated,Work Place
0,470010201001000,470010201001063,2,1,1,0,0,1,1,0,0,2,Anderson County,NaN,Oak Ridge city,Anderson County,NaN,Oak Ridge city
1,470010201001000,470010201002013,1,0,0,1,1,0,0,0,0,1,Anderson County,NaN,Oak Ridge city,Anderson County,NaN,Oak Ridge city
2,470010201001000,470010201002017,1,1,0,0,0,1,0,0,0,1,Anderson County,NaN,Oak Ridge city,Anderson County,NaN,Oak Ridge city
3,470010201001000,470010201002021,1,1,0,0,0,1,0,0,0,1,Anderson County,NaN,Oak Ridge city,Anderson County,NaN,Oak Ridge city
4,470010201001000,470010202023018,1,0,0,1,0,0,1,0,0,1,Anderson County,NaN,Oak Ridge city,Anderson County,NaN,Oak Ridge city

In [212]:
od.to_feather('../../Outputs/LEHD_OD')