In [1]:
import pandas as pd
import numpy as np
import requests
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.width', 150)
from warnings import simplefilter
simplefilter(action="ignore", category=pd.errors.PerformanceWarning)

In [2]:
def percent(x, y):
    return (x/y)*100

# Selecting LEHD datasets: 

https://lehd.ces.census.gov/data/lodes/LODES7/LODESTechDoc7.5.pdf  

Pages 5 & 6 of this document outlines the file structure for Origin-Destination data. This data is limited to disaggregations by the following categories:  
+ age (29 and younger, 30 to 54, and 55 or older)  
+ earnings (1,250 a month or less, 1,251 to 3,333 a month, and greater than 3,333 a month)  
+ Goods-Producing versus Trade, Transportation & Utilities, versus All Other Services industry sectors  

The earnings breakout is kind of useless so we'll only use the age and industry sector data.  

Page 7 of this document outlines the file structure for the Residence Area Characteristics data. This shows the same totals for age and earnings listed above, but further disaggregates the industry component into 2-digit NAICS codes. It also disaggregates job counts by race, Hispanic or Latino ethnicity, sex, and educational attainment (High School or Equivalent, Some college or Associate degree, Bachelor's degree or advanced degree). 

Page 8 of this document outlines the file structure for the Workplace Area Characteristics. This shows all of the same information as the RAC but also firm age and size. 

This data package also has a geography crosswalk which will be helpful in aggregating all of these numbers to a place and county level.

## Geography Crosswalk  
What we need from the geography crosswalk:  
+ a list of block groups in the GNRC region to narrow down the WAC and RAC preliminarily (we'll only be looking at the region here, not the state, because we're simply looking at in vs out instead of flow)  
+ a way to tag county and place to WAC, RAC, and OD block codes so that we can aggregate everything available by county, place, and unincorporated areas - dictionaries for now

In [3]:
url = 'https://lehd.ces.census.gov/data/lodes/LODES7/tn/tn_xwalk.csv.gz'
geo = pd.read_csv(url, dtype = str)
print('Your file is ready.')

Your file is ready.

In [4]:
#rename and drop unneeded columns
geocols = {'tabblk2010': 'Block Code', 'st': 'StateFIPS', 'stusps': 'StateUSPS', 'stname': 'State', 'cty': 'CountyFIPS', 'ctyname': 'County', 
           'trct': 'TractCODE', 'trctname': 'Tract', 'bgrp': 'BlockgroupCODE', 'bgrpname': 'Blockgroup', 'cbsa': 'CBSACODE', 'cbsaname': 'CBSA', 
           'zcta': 'ZCTACODE', 'zctaname': 'ZCTA', 'stplc': 'PlaceCODE', 'stplcname': 'Place', 'stwib': 'WIBCODE', 'stwibname': 'WIB', 
           'blklatdd': 'Lat', 'blklondd': 'Lon'}
geo.rename(columns = geocols, inplace = True)
cols = ['ctycsub', 'ctycsubname', 'stcd116', 'stcd116name', 'stsldl', 'stsldlname', 'stsldu', 'stslduname', 'stschool',
       'stschoolname', 'stsecon', 'stseconname', 'trib', 'tribname', 'tsub', 'tsubname', 'stanrc', 'stanrcname', 'necta', 'nectaname', 'mil',
       'milname']
geo = geo.drop(columns = cols)

In [5]:
geo.head()

,Block Code,StateFIPS,StateUSPS,State,CountyFIPS,County,TractCODE,Tract,BlockgroupCODE,Blockgroup,CBSACODE,CBSA,ZCTACODE,ZCTA,PlaceCODE,Place,WIBCODE,WIB,Lat,Lon,createdate
0,470279550001069,47,TN,Tennessee,47027,"Clay County, TN",47027955000,"9550 (Clay, TN)",470279550001,"1 (Tract 9550, Clay, TN)",99999,NaN,38551,38551,9999999,NaN,47LWIA07,07 Local Workforce Investment Area,36.5522497,-85.4519031,20211018
1,470059630002096,47,TN,Tennessee,47005,"Benton County, TN",47005963000,"9630 (Benton, TN)",470059630002,"2 (Tract 9630, Benton, TN)",99999,NaN,38221,38221,9999999,NaN,47LWIA11,11 Local Workforce Investment Area,36.2107573,-88.1373529,20211018
2,470059630002091,47,TN,Tennessee,47005,"Benton County, TN",47005963000,"9630 (Benton, TN)",470059630002,"2 (Tract 9630, Benton, TN)",99999,NaN,38221,38221,9999999,NaN,47LWIA11,11 Local Workforce Investment Area,36.1901840,-88.0977486,20211018
3,470059631001043,47,TN,Tennessee,47005,"Benton County, TN",47005963100,"9631 (Benton, TN)",470059631001,"1 (Tract 9631, Benton, TN)",99999,NaN,38320,38320,9999999,NaN,47LWIA11,11 Local Workforce Investment Area,36.0788357,-88.0445962,20211018
4,470059630001061,47,TN,Tennessee,47005,"Benton County, TN",47005963000,"9630 (Benton, TN)",470059630001,"1 (Tract 9630, Benton, TN)",99999,NaN,38221,38221,9999999,NaN,47LWIA11,11 Local Workforce Investment Area,36.3057522,-88.0285893,20211018

In [6]:
GNRCREGION = ['47161', #Stewart
            '47125', #Montgomery
            '47083', #Houston
            '47085', #Humphreys
            '47043', #Dickson
            '47021', #Cheatham
            '47147', #Robertson
            '47165', #Sumner
            '47037', #Davidson
            '47189', #Wilson
            '47169', #Trousdale
            '47187', #Williamson
            '47149', #Rutherford
            '47119'] #Maury

In [7]:
#make a list of block codes in the GNRC region by listing county FIPS, indexing to only block codes in that list, and the creating a list of those values
thelist = ['47161', '47125', '47083', '47085', '47043', '47021', '47147', '47165', '47037', '47189', '47169', '47187', '47149', '47119']
bg = geo.loc[geo['CountyFIPS'].isin(thelist)]
blockcodegnrcregion = list(bg['Block Code'].values)
#blockcodegnrcregion

In [8]:
#create a dictionary of county names to a list of their block codes
tncounties = list(geo['County'].unique())
c = {}
for i in tncounties:
    c['{}'.format(i)] = list(geo.loc[geo['County'] == '{}'.format(i), 'Block Code'])
#c

In [9]:
#invert that dictionary so that we can map it later
c_inverted = {}
for k,v in c.items():
    for x in v:
        c_inverted.setdefault(x,[]).append(k)
#c_inverted

In [10]:
#create a dictionary of place names to a list of their block codes
tnplace = geo[~geo['Place'].str.contains('CDP', na = True)]
tnplace = list(tnplace['Place'].unique())
p = {}
for i in tnplace:
    p['{}'.format(i)] = list(geo.loc[geo['Place'] == '{}'.format(i), 'Block Code'])
#p

In [11]:
#invert that dictionary so that we can map it later
p_inverted = {}
for k,v in p.items():
    for x in v:
        p_inverted.setdefault(x,[]).append(k)
#p_inverted

In [12]:
#create a tag for unincorporated block codes to use later per county
geo['Place'] = geo['Place'].fillna('None')
tnunincorporated = geo[(geo['Place'].str.contains('CDP'))|(geo['Place'] == 'None')]
test = list(tnunincorporated['Place'].unique())
un = {}
for i in test:
    un['{}'.format(i)] = list(geo.loc[geo['Place'] == '{}'.format(i), 'Block Code'])
#un

In [13]:
#invert that dictionary so that we can map it later
un_inverted = {}
for k,v in un.items():
    for x in v:
        un_inverted.setdefault(x,[]).append(k)
#un_inverted

## Residence Area Characteristics

In [48]:
#all primary jobs
url = 'https://lehd.ces.census.gov/data/lodes/LODES7/tn/rac/tn_rac_S000_JT01_2019.csv.gz'
rac = pd.read_csv(url)
print('Your file is ready.')

Your file is ready.

In [49]:
raccols = {'h_geocode': 'GEO_ID', 'C000': 'Total Jobs', 'CA01': 'Age:Workers 29 or Younger', 'CA02': 'Age:Workers 30 to 54', 
           'CA03': 'Age:Workers 55 Older', 'CE01': 'Earnings:1250mo or Less', 'CE02': 'Earnings:1251 to 3333mo', 
           'CE03': 'Earnings:Greater Than 3333mo', 'CNS01': 'NAICS:11Agriculture, Forestry, Fishing & Hunting', 
           'CNS02': 'NAICS:21Mining, Quarrying, Oil & Gas', 'CNS03': 'NAICS:22Utilities', 'CNS04': 'NAICS:23Construction', 'CNS05':'NAICS:31to33Manufacturing',
           'CNS06': 'NAICS:42Wholesale Trade', 'CNS07': 'NAICS:44to45Retail Trade', 'CNS08': 'NAICS:48to49Transportation & Warehousing',
           'CNS09': 'NAICS:51Information', 'CNS10': 'NAICS:52Finance & Insurance', 'CNS11': 'NAICS:53Real Estate & Rental & Leasing', 
           'CNS12': 'NAICS:54Professional, Scientific, & Technical Services', 'CNS13': 'NAICS:55Management of Companies & Enterprises', 
           'CNS14': 'NAICS:56Administrative & Support & Waste Management & Remediation Services', 'CNS15': 'NAICS:61Educational Services', 
           'CNS16': 'NAICS:62Healthcare & Social Assistance', 'CNS17': 'NAICS:71Arts, Entertainment, & Recreation', 'CNS18': 'NAICS:72Accommodation & Food Services', 
           'CNS19': 'NAICS:81Other Services (Except Public Administration)', 'CNS20': 'NAICS:92Public Administration', 
           'CR01': 'Race:White Alone', 'CR02': 'Race:Black or African American Alone', 'CR03': 'Race:American Indian or Alaska Native Alone', 
           'CR04': 'Race:Asian Alone', 'CR05': 'Race:Native Hawaiian or Other Pacific Islander Alone', 'CR07': 'Race:Two or More Races', 
           'CT01': 'Ethnicity:Not Hispanic or Latino', 'CT02': 'Ethnicity:Hispanic or Latino', 'CD01':'Ed:Less than High School', 
           'CD02': 'Ed:High School or Equivalent', 'CD03': 'Ed:Some College or Associates', 'CD04': 'Ed:Bachelors or Advanced Degree', 'CS01': 'Sex:Male', 
           'CS02': 'Sex:Female'}

In [50]:
rac.rename(columns = raccols, inplace = True)

In [51]:
rac = rac.set_index('GEO_ID')
rac = rac.add_prefix('RAC:')

In [52]:
rac.head()

,RAC:Total Jobs,RAC:Age:Workers 29 or Younger,RAC:Age:Workers 30 to 54,RAC:Age:Workers 55 Older,RAC:Earnings:1250mo or Less,RAC:Earnings:1251 to 3333mo,RAC:Earnings:Greater Than 3333mo,"RAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","RAC:NAICS:21Mining, Quarrying, Oil & Gas",RAC:NAICS:22Utilities,RAC:NAICS:23Construction,RAC:NAICS:31to33Manufacturing,RAC:NAICS:42Wholesale Trade,RAC:NAICS:44to45Retail Trade,RAC:NAICS:48to49Transportation & Warehousing,RAC:NAICS:51Information,RAC:NAICS:52Finance & Insurance,RAC:NAICS:53Real Estate & Rental & Leasing,"RAC:NAICS:54Professional, Scientific, & Technical Services",RAC:NAICS:55Management of Companies & Enterprises,RAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,RAC:NAICS:61Educational Services,RAC:NAICS:62Healthcare & Social Assistance,"RAC:NAICS:71Arts, Entertainment, & Recreation",RAC:NAICS:72Accommodation & Food Services,RAC:NAICS:81Other Services (Except Public Administration),RAC:NAICS:92Public Administration,RAC:Race:White Alone,RAC:Race:Black or African American Alone,RAC:Race:American Indian or Alaska Native Alone,RAC:Race:Asian Alone,RAC:Race:Native Hawaiian or Other Pacific Islander Alone,RAC:Race:Two or More Races,RAC:Ethnicity:Not Hispanic or Latino,RAC:Ethnicity:Hispanic or Latino,RAC:Ed:Less than High School,RAC:Ed:High School or Equivalent,RAC:Ed:Some College or Associates,RAC:Ed:Bachelors or Advanced Degree,RAC:Sex:Male,RAC:Sex:Female,RAC:createdate
GEO_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
470010201001006,76,28,39,9,15,31,30,0,0,0,3,6,2,6,1,2,5,1,9,0,9,7,12,0,9,3,1,66,7,2,1,0,0,66,10,8,17,16,7,40,36,20211018
470010201001015,125,46,61,18,26,49,50,0,0,0,1,15,4,21,1,1,4,4,13,3,11,8,14,1,18,4,2,91,15,0,14,0,5,117,8,6,27,26,20,66,59,20211018
470010201001057,8,2,5,1,1,4,3,0,0,0,0,1,0,2,1,0,0,0,1,0,1,0,0,0,0,0,2,7,1,0,0,0,0,8,0,0,2,2,2,5,3,20211018
470010201001062,95,32,41,22,18,39,38,0,0,0,3,10,5,14,1,1,3,2,11,4,11,5,10,1,11,3,0,82,6,0,5,0,2,92,3,3,17,16,27,49,46,20211018
470010201001063,80,19,44,17,16,32,32,0,0,0,1,9,1,11,2,0,4,2,6,3,5,7,8,1,14,4,2,61,8,0,8,0,3,78,2,12,13,20,16,35,45,20211018

## Workplace Area Characteristics

In [53]:
#all primary jobs
url = 'https://lehd.ces.census.gov/data/lodes/LODES7/tn/wac/tn_wac_S000_JT01_2019.csv.gz'
wac = pd.read_csv(url)
print('Your file is ready.')

Your file is ready.

In [54]:
waccols = {'w_geocode': 'GEO_ID', 'C000': 'Total Jobs', 'CA01': 'Age:Workers 29 or Younger', 'CA02': 'Age:Workers 30 to 54', 
           'CA03': 'Age:Workers 55 Older', 'CE01': 'Earnings:1250mo or Less', 'CE02': 'Earnings:1251 to 3333mo', 
           'CE03': 'Earnings:Greater Than 3333mo', 'CNS01': 'NAICS:11Agriculture, Forestry, Fishing & Hunting', 
           'CNS02': 'NAICS:21Mining, Quarrying, Oil & Gas', 'CNS03': 'NAICS:22Utilities', 'CNS04': 'NAICS:23Construction', 'CNS05':'NAICS:31to33Manufacturing',
           'CNS06': 'NAICS:42Wholesale Trade', 'CNS07': 'NAICS:44to45Retail Trade', 'CNS08': 'NAICS:48to49Transportation & Warehousing',
           'CNS09': 'NAICS:51Information', 'CNS10': 'NAICS:52Finance & Insurance', 'CNS11': 'NAICS:53Real Estate & Rental & Leasing', 
           'CNS12': 'NAICS:54Professional, Scientific, & Technical Services', 'CNS13': 'NAICS:55Management of Companies & Enterprises', 
           'CNS14': 'NAICS:56Administrative & Support & Waste Management & Remediation Services', 'CNS15': 'NAICS:61Educational Services', 
           'CNS16': 'NAICS:62Healthcare & Social Assistance', 'CNS17': 'NAICS:71Arts, Entertainment, & Recreation', 'CNS18': 'NAICS:72Accommodation & Food Services', 
           'CNS19': 'NAICS:81Other Services (Except Public Administration)', 'CNS20': 'NAICS:92Public Administration', 
           'CR01': 'Race:White Alone', 'CR02': 'Race:Black or African American Alone', 'CR03': 'Race:American Indian or Alaska Native Alone', 
           'CR04': 'Race:Asian Alone', 'CR05': 'Race:Native Hawaiian or Other Pacific Islander Alone', 'CR07': 'Race:Two or More Races', 
           'CT01': 'Ethnicity:Not Hispanic or Latino', 'CT02': 'Ethnicity:Hispanic or Latino', 'CD01':'Ed:Less than High School', 
           'CD02': 'Ed:High School or Equivalent', 'CD03': 'Ed:Some College or Associates', 'CD04': 'Ed:Bachelors or Advanced Degree', 'CS01': 'Sex:Male', 
           'CS02': 'Sex:Female', 'CFA01': 'FirmAge:0 to 1 Year', 'CFA02': 'FirmAge:2 to 3 Years', 'CFA03': 'FirmAge:4 to 5 Years', 'CFA04': 'FirmAge:6 to 10 Years',
           'CFA05': 'FirmAge:11 or More Years', 'CFS01': 'FirmSize:0 to 19 Employees', 'CFS02': 'FirmSize:20 to 49 Employees', 
           'CFS03': 'FirmSize:50 to 249 Employees', 'CFS04': 'FirmSize:250 to 499 Employees', 'CFS05': 'FirmSize:500 or More Employees'}

In [55]:
wac.rename(columns = waccols, inplace = True)

In [56]:
wac = wac.set_index('GEO_ID')
wac = wac.add_prefix('WAC:')

In [57]:
wac.head()

,WAC:Total Jobs,WAC:Age:Workers 29 or Younger,WAC:Age:Workers 30 to 54,WAC:Age:Workers 55 Older,WAC:Earnings:1250mo or Less,WAC:Earnings:1251 to 3333mo,WAC:Earnings:Greater Than 3333mo,"WAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","WAC:NAICS:21Mining, Quarrying, Oil & Gas",WAC:NAICS:22Utilities,WAC:NAICS:23Construction,WAC:NAICS:31to33Manufacturing,WAC:NAICS:42Wholesale Trade,WAC:NAICS:44to45Retail Trade,WAC:NAICS:48to49Transportation & Warehousing,WAC:NAICS:51Information,WAC:NAICS:52Finance & Insurance,WAC:NAICS:53Real Estate & Rental & Leasing,"WAC:NAICS:54Professional, Scientific, & Technical Services",WAC:NAICS:55Management of Companies & Enterprises,WAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,WAC:NAICS:61Educational Services,WAC:NAICS:62Healthcare & Social Assistance,"WAC:NAICS:71Arts, Entertainment, & Recreation",WAC:NAICS:72Accommodation & Food Services,WAC:NAICS:81Other Services (Except Public Administration),WAC:NAICS:92Public Administration,WAC:Race:White Alone,WAC:Race:Black or African American Alone,WAC:Race:American Indian or Alaska Native Alone,WAC:Race:Asian Alone,WAC:Race:Native Hawaiian or Other Pacific Islander Alone,WAC:Race:Two or More Races,WAC:Ethnicity:Not Hispanic or Latino,WAC:Ethnicity:Hispanic or Latino,WAC:Ed:Less than High School,WAC:Ed:High School or Equivalent,WAC:Ed:Some College or Associates,WAC:Ed:Bachelors or Advanced Degree,WAC:Sex:Male,WAC:Sex:Female,WAC:FirmAge:0 to 1 Year,WAC:FirmAge:2 to 3 Years,WAC:FirmAge:4 to 5 Years,WAC:FirmAge:6 to 10 Years,WAC:FirmAge:11 or More Years,WAC:FirmSize:0 to 19 Employees,WAC:FirmSize:20 to 49 Employees,WAC:FirmSize:50 to 249 Employees,WAC:FirmSize:250 to 499 Employees,WAC:FirmSize:500 or More Employees,WAC:createdate
GEO_ID,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
470010201001000,97,35,42,20,30,48,19,0,0,0,1,0,0,11,0,0,21,0,1,0,0,0,16,11,16,20,0,91,3,0,1,0,2,93,4,7,19,23,13,29,68,0,0,0,0,0,0,0,0,0,0,20211018
470010201001005,38,7,14,17,9,23,6,0,0,0,0,0,0,5,0,0,2,0,6,0,0,0,0,0,25,0,0,30,2,1,4,0,1,38,0,2,10,12,7,8,30,0,0,0,0,0,0,0,0,0,0,20211018
470010201001006,3,0,1,2,0,3,0,0,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,0,0,0,0,3,0,0,0,0,0,3,0,0,3,0,0,0,3,0,0,0,0,0,0,0,0,0,0,20211018
470010201001009,176,39,93,44,6,94,76,0,0,0,0,0,0,0,0,0,166,0,0,0,0,0,0,0,10,0,0,161,7,0,5,0,3,169,7,12,43,44,38,44,132,0,0,0,0,0,0,0,0,0,0,20211018
470010201001010,4,1,3,0,1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,4,0,0,0,0,0,4,0,0,4,0,1,0,1,1,2,2,0,0,0,0,0,0,0,0,0,0,20211018

### Join RAC and WAC

In [58]:
#reset index to join on GEO_ID and filter both to only include the GNRC region
rac = rac.reset_index(drop = False)
rac['GEO_ID'] = rac['GEO_ID'].astype(str)
rac = rac.loc[rac['GEO_ID'].isin(blockcodegnrcregion)]
wac = wac.reset_index(drop = False)
wac['GEO_ID'] = wac['GEO_ID'].astype(str)
wac = wac.loc[wac['GEO_ID'].isin(blockcodegnrcregion)]

In [59]:
df = pd.merge(left = wac, right = rac, on = 'GEO_ID', how = 'outer')

In [60]:
#make dataframes grouped by both county and place to concatenate later
county = df
place = df

In [61]:
county.head()

,GEO_ID,WAC:Total Jobs,WAC:Age:Workers 29 or Younger,WAC:Age:Workers 30 to 54,WAC:Age:Workers 55 Older,WAC:Earnings:1250mo or Less,WAC:Earnings:1251 to 3333mo,WAC:Earnings:Greater Than 3333mo,"WAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","WAC:NAICS:21Mining, Quarrying, Oil & Gas",WAC:NAICS:22Utilities,WAC:NAICS:23Construction,WAC:NAICS:31to33Manufacturing,WAC:NAICS:42Wholesale Trade,WAC:NAICS:44to45Retail Trade,WAC:NAICS:48to49Transportation & Warehousing,WAC:NAICS:51Information,WAC:NAICS:52Finance & Insurance,WAC:NAICS:53Real Estate & Rental & Leasing,"WAC:NAICS:54Professional, Scientific, & Technical Services",WAC:NAICS:55Management of Companies & Enterprises,WAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,WAC:NAICS:61Educational Services,WAC:NAICS:62Healthcare & Social Assistance,"WAC:NAICS:71Arts, Entertainment, & Recreation",WAC:NAICS:72Accommodation & Food Services,WAC:NAICS:81Other Services (Except Public Administration),WAC:NAICS:92Public Administration,WAC:Race:White Alone,WAC:Race:Black or African American Alone,WAC:Race:American Indian or Alaska Native Alone,WAC:Race:Asian Alone,WAC:Race:Native Hawaiian or Other Pacific Islander Alone,WAC:Race:Two or More Races,WAC:Ethnicity:Not Hispanic or Latino,WAC:Ethnicity:Hispanic or Latino,WAC:Ed:Less than High School,WAC:Ed:High School or Equivalent,WAC:Ed:Some College or Associates,WAC:Ed:Bachelors or Advanced Degree,WAC:Sex:Male,WAC:Sex:Female,WAC:FirmAge:0 to 1 Year,WAC:FirmAge:2 to 3 Years,WAC:FirmAge:4 to 5 Years,WAC:FirmAge:6 to 10 Years,WAC:FirmAge:11 or More Years,WAC:FirmSize:0 to 19 Employees,WAC:FirmSize:20 to 49 Employees,WAC:FirmSize:50 to 249 Employees,WAC:FirmSize:250 to 499 Employees,WAC:FirmSize:500 or More Employees,WAC:createdate,RAC:Total Jobs,RAC:Age:Workers 29 or Younger,RAC:Age:Workers 30 to 54,RAC:Age:Workers 55 Older,RAC:Earnings:1250mo or Less,RAC:Earnings:1251 to 3333mo,RAC:Earnings:Greater Than 3333mo,"RAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","RAC:NAICS:21Mining, Quarrying, Oil & Gas",RAC:NAICS:22Utilities,RAC:NAICS:23Construction,RAC:NAICS:31to33Manufacturing,RAC:NAICS:42Wholesale Trade,RAC:NAICS:44to45Retail Trade,RAC:NAICS:48to49Transportation & Warehousing,RAC:NAICS:51Information,RAC:NAICS:52Finance & Insurance,RAC:NAICS:53Real Estate & Rental & Leasing,"RAC:NAICS:54Professional, Scientific, & Technical Services",RAC:NAICS:55Management of Companies & Enterprises,RAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,RAC:NAICS:61Educational Services,RAC:NAICS:62Healthcare & Social Assistance,"RAC:NAICS:71Arts, Entertainment, & Recreation",RAC:NAICS:72Accommodation & Food Services,RAC:NAICS:81Other Services (Except Public Administration),RAC:NAICS:92Public Administration,RAC:Race:White Alone,RAC:Race:Black or African American Alone,RAC:Race:American Indian or Alaska Native Alone,RAC:Race:Asian Alone,RAC:Race:Native Hawaiian or Other Pacific Islander Alone,RAC:Race:Two or More Races,RAC:Ethnicity:Not Hispanic or Latino,RAC:Ethnicity:Hispanic or Latino,RAC:Ed:Less than High School,RAC:Ed:High School or Equivalent,RAC:Ed:Some College or Associates,RAC:Ed:Bachelors or Advanced Degree,RAC:Sex:Male,RAC:Sex:Female,RAC:createdate
0,470210701021001,7.0,1.0,2.0,4.0,1.0,4.0,2.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,1.0,0.0,0.0,0.0,0.0,7.0,0.0,1.0,4.0,0.0,1.0,6.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20211018.0,34.0,11.0,15.0,8.0,3.0,17.0,14.0,0.0,0.0,1.0,1.0,6.0,0.0,7.0,0.0,1.0,0.0,0.0,2.0,0.0,2.0,2.0,7.0,1.0,3.0,0.0,1.0,32.0,1.0,0.0,0.0,1.0,0.0,34.0,0.0,7.0,4.0,7.0,5.0,20.0,14.0,20211018.0
1,470210701021002,67.0,12.0,38.0,17.0,8.0,33.0,26.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,62.0,0.0,0.0,0.0,5.0,57.0,6.0,3.0,0.0,0.0,1.0,64.0,3.0,5.0,18.0,16.0,16.0,11.0,56.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20211018.0,89.0,23.0,41.0,25.0,18.0,26.0,45.0,0.0,0.0,0.0,10.0,10.0,2.0,10.0,3.0,3.0,4.0,1.0,3.0,2.0,8.0,4.0,17.0,1.0,6.0,1.0,4.0,84.0,1.0,0.0,2.0,0.0,2.0,88.0,1.0,7.0,20.0,20.0,19.0,55.0,34.0,20211018.0
2,470210701021006,5.0,0.0,4.0,1.0,1.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,0.0,0.0,0.0,0.0,5.0,0.0,1.0,2.0,2.0,0.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20211018.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,470210701021008,16.0,5.0,8.0,3.0,2.0,3.0,11.0,0.0,0.0,0.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,0.0,0.0,0.0,0.0,0.0,16.0,0.0,2.0,1.0,4.0,4.0,12.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20211018.0,150.0,25.0,88.0,37.0,29.0,42.0,79.0,0.0,0.0,1.0,14.0,19.0,8.0,13.0,5.0,3.0,6.0,0.0,10.0,1.0,10.0,18.0,16.0,0.0,9.0,6.0,11.0,142.0,2.0,0.0,0.0,0.0,6.0,146.0,4.0,14.0,37.0,38.0,36.0,77.0,73.0,20211018.0
4,470210701021018,2.0,0.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,20211018.0,32.0,9.0,18.0,5.0,4.0,10.0,18.0,0.0,0.0,1.0,2.0,3.0,1.0,4.0,3.0,0.0,0.0,0.0,3.0,0.0,2.0,2.0,2.0,0.0,3.0,1.0,5.0,31.0,1.0,0.0,0.0,0.0,0.0,31.0,1.0,3.0,7.0,8.0,5.0,16.0,16.0,20211018.0

In [62]:
#add columns with county name and place name respectively
county['County'] = county['GEO_ID'].map(c_inverted)
county['Incorporated'] = county['GEO_ID'].map(un_inverted)
place['Place'] = place['GEO_ID'].map(p_inverted)

In [63]:
county['County'] = county['County'].str.get(0)
county['Incorporated'] = county['Incorporated'].str.get(0)
place['Place'] = place['Place'].str.get(0)

In [64]:
county = county.drop(columns = ['GEO_ID'])
place = place.drop(columns = ['GEO_ID'])

In [65]:
countywacrac = county.groupby('County').sum()

In [66]:
placewacrac = place.groupby('Place').sum()

In [67]:
unwacrac = county.groupby(['Incorporated', 'County']).sum()

In [68]:
unwacrac = unwacrac.groupby('County').sum()

In [69]:
unwacrac = unwacrac.transpose()

In [70]:
unwacrac.head()

County,"Cheatham County, TN","Dickson County, TN","Houston County, TN","Humphreys County, TN","Maury County, TN","Montgomery County, TN","Robertson County, TN","Rutherford County, TN","Stewart County, TN","Sumner County, TN","Williamson County, TN","Wilson County, TN"
WAC:Total Jobs,1532.0,3572.0,288.0,3244.0,9456.0,7766.0,3392.0,11723.0,659.0,2574.0,5770.0,6669.0
WAC:Age:Workers 29 or Younger,405.0,1027.0,74.0,557.0,1814.0,2119.0,851.0,2217.0,177.0,670.0,1579.0,1648.0
WAC:Age:Workers 30 to 54,796.0,1791.0,141.0,1778.0,5007.0,4367.0,1799.0,6366.0,346.0,1266.0,3037.0,3556.0
WAC:Age:Workers 55 Older,331.0,754.0,73.0,909.0,2635.0,1280.0,742.0,3140.0,136.0,638.0,1154.0,1465.0
WAC:Earnings:1250mo or Less,328.0,792.0,58.0,482.0,837.0,1060.0,559.0,1856.0,147.0,514.0,1060.0,1155.0

In [71]:
unwacrac = unwacrac.rename(columns = {'Cheatham County, TN': 'Cheatham Unincorporated', 
                                      'Dickson County, TN': 'Dickson Unincorporated', 
                                      'Houston County, TN': 'Houston Unincorporated',
                                      'Humphreys County, TN': 'Humphreys Unincorporated', 
                                      'Maury County, TN': 'Maury Unincorporated',
                                      'Montgomery County, TN': 'Montgomery Unincorporated', 
                                      'Robertson County, TN': 'Robertson Unincorporated',
                                      'Rutherford County, TN': 'Rutherford Unincorporated', 
                                      'Stewart County, TN': 'Stewart Unincorporated', 
                                      'Sumner County, TN': 'Sumner Unincorporated',
                                      'Williamson County, TN': 'Williamson Unincorporated', 
                                      'Wilson County, TN': 'Wilson Unincorporated'})

In [72]:
unwacrac = unwacrac.transpose()

In [73]:
wacrac = countywacrac.append(placewacrac)
data = wacrac.append(unwacrac)

C:\Users\jmccall\AppData\Local\Temp\ipykernel_5544\3254936776.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  wacrac = countywacrac.append(placewacrac)
C:\Users\jmccall\AppData\Local\Temp\ipykernel_5544\3254936776.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = wacrac.append(unwacrac)

In [80]:
wacrac = data

In [81]:
wacrac = wacrac.drop(columns = ['RAC:createdate', 'WAC:createdate'])

In [82]:
wacrac.tail()

,WAC:Total Jobs,WAC:Age:Workers 29 or Younger,WAC:Age:Workers 30 to 54,WAC:Age:Workers 55 Older,WAC:Earnings:1250mo or Less,WAC:Earnings:1251 to 3333mo,WAC:Earnings:Greater Than 3333mo,"WAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","WAC:NAICS:21Mining, Quarrying, Oil & Gas",WAC:NAICS:22Utilities,WAC:NAICS:23Construction,WAC:NAICS:31to33Manufacturing,WAC:NAICS:42Wholesale Trade,WAC:NAICS:44to45Retail Trade,WAC:NAICS:48to49Transportation & Warehousing,WAC:NAICS:51Information,WAC:NAICS:52Finance & Insurance,WAC:NAICS:53Real Estate & Rental & Leasing,"WAC:NAICS:54Professional, Scientific, & Technical Services",WAC:NAICS:55Management of Companies & Enterprises,WAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,WAC:NAICS:61Educational Services,WAC:NAICS:62Healthcare & Social Assistance,"WAC:NAICS:71Arts, Entertainment, & Recreation",WAC:NAICS:72Accommodation & Food Services,WAC:NAICS:81Other Services (Except Public Administration),WAC:NAICS:92Public Administration,WAC:Race:White Alone,WAC:Race:Black or African American Alone,WAC:Race:American Indian or Alaska Native Alone,WAC:Race:Asian Alone,WAC:Race:Native Hawaiian or Other Pacific Islander Alone,WAC:Race:Two or More Races,WAC:Ethnicity:Not Hispanic or Latino,WAC:Ethnicity:Hispanic or Latino,WAC:Ed:Less than High School,WAC:Ed:High School or Equivalent,WAC:Ed:Some College or Associates,WAC:Ed:Bachelors or Advanced Degree,WAC:Sex:Male,WAC:Sex:Female,WAC:FirmAge:0 to 1 Year,WAC:FirmAge:2 to 3 Years,WAC:FirmAge:4 to 5 Years,WAC:FirmAge:6 to 10 Years,WAC:FirmAge:11 or More Years,WAC:FirmSize:0 to 19 Employees,WAC:FirmSize:20 to 49 Employees,WAC:FirmSize:50 to 249 Employees,WAC:FirmSize:250 to 499 Employees,WAC:FirmSize:500 or More Employees,RAC:Total Jobs,RAC:Age:Workers 29 or Younger,RAC:Age:Workers 30 to 54,RAC:Age:Workers 55 Older,RAC:Earnings:1250mo or Less,RAC:Earnings:1251 to 3333mo,RAC:Earnings:Greater Than 3333mo,"RAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","RAC:NAICS:21Mining, Quarrying, Oil & Gas",RAC:NAICS:22Utilities,RAC:NAICS:23Construction,RAC:NAICS:31to33Manufacturing,RAC:NAICS:42Wholesale Trade,RAC:NAICS:44to45Retail Trade,RAC:NAICS:48to49Transportation & Warehousing,RAC:NAICS:51Information,RAC:NAICS:52Finance & Insurance,RAC:NAICS:53Real Estate & Rental & Leasing,"RAC:NAICS:54Professional, Scientific, & Technical Services",RAC:NAICS:55Management of Companies & Enterprises,RAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,RAC:NAICS:61Educational Services,RAC:NAICS:62Healthcare & Social Assistance,"RAC:NAICS:71Arts, Entertainment, & Recreation",RAC:NAICS:72Accommodation & Food Services,RAC:NAICS:81Other Services (Except Public Administration),RAC:NAICS:92Public Administration,RAC:Race:White Alone,RAC:Race:Black or African American Alone,RAC:Race:American Indian or Alaska Native Alone,RAC:Race:Asian Alone,RAC:Race:Native Hawaiian or Other Pacific Islander Alone,RAC:Race:Two or More Races,RAC:Ethnicity:Not Hispanic or Latino,RAC:Ethnicity:Hispanic or Latino,RAC:Ed:Less than High School,RAC:Ed:High School or Equivalent,RAC:Ed:Some College or Associates,RAC:Ed:Bachelors or Advanced Degree,RAC:Sex:Male,RAC:Sex:Female
Rutherford Unincorporated,11723.0,2217.0,6366.0,3140.0,1856.0,3395.0,6472.0,38.0,19.0,21.0,1252.0,1178.0,242.0,505.0,325.0,45.0,39.0,55.0,207.0,131.0,1499.0,2403.0,3043.0,109.0,404.0,208.0,0.0,9327.0,1817.0,62.0,339.0,11.0,167.0,11246.0,477.0,881.0,2331.0,3083.0,3211.0,6116.0,5607.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,46630.0,10325.0,27109.0,9196.0,6670.0,12365.0,27595.0,55.0,26.0,279.0,2530.0,6225.0,2164.0,4834.0,2690.0,1033.0,2117.0,702.0,2647.0,1055.0,3093.0,4390.0,5689.0,523.0,3485.0,1070.0,2023.0,40267.0,4526.0,132.0,1152.0,25.0,528.0,44893.0,1737.0,3994.0,10343.0,11698.0,10270.0,24257.0,22373.0
Stewart Unincorporated,659.0,177.0,346.0,136.0,147.0,331.0,181.0,2.0,0.0,8.0,96.0,52.0,5.0,161.0,0.0,0.0,16.0,0.0,24.0,0.0,7.0,0.0,39.0,15.0,64.0,26.0,144.0,623.0,10.0,6.0,11.0,1.0,8.0,633.0,26.0,61.0,166.0,167.0,88.0,350.0,309.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3869.0,931.0,2043.0,895.0,774.0,1452.0,1643.0,3.0,25.0,50.0,274.0,552.0,120.0,524.0,128.0,52.0,99.0,34.0,159.0,21.0,179.0,474.0,477.0,24.0,331.0,90.0,253.0,3696.0,83.0,12.0,33.0,1.0,44.0,3784.0,85.0,299.0,979.0,980.0,680.0,1933.0,1936.0
Sumner Unincorporated,2574.0,670.0,1266.0,638.0,514.0,968.0,1092.0,22.0,0.0,0.0,600.0,318.0,98.0,81.0,120.0,7.0,78.0,23.0,97.0,3.0,369.0,7.0,261.0,32.0,359.0,99.0,0.0,2304.0,170.0,12.0,47.0,2.0,39.0,2446.0,128.0,264.0,669.0,583.0,388.0,1565.0,1009.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27039.0,5712.0,14605.0,6722.0,4309.0,8166.0,14564.0,32.0,11.0,174.0,1736.0,3188.0,1481.0,2934.0,1533.0,408.0,1068.0,404.0,1606.0,610.0,1441.0,2545.0,3320.0,344.0,2106.0,698.0,1400.0,24948.0,1467.0,67.0,267.0,24.0,266.0,26247.0,792.0,2273.0,6426.0,6914.0,5714.0,13872.0,13167.0
Williamson Unincorporated,5770.0,1579.0,3037.0,1154.0,1060.0,1520.0,3190.0,119.0,0.0,19.0,744.0,182.0,320.0,323.0,126.0,158.0,1121.0,196.0,496.0,10.0,427.0,284.0,330.0,244.0,399.0,272.0,0.0,5201.0,352.0,32.0,110.0,9.0,66.0,5453.0,317.0,478.0,1090.0,1342.0,1281.0,3292.0,2478.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24603.0,4561.0,13596.0,6446.0,3960.0,4914.0,15729.0,58.0,16.0,108.0,1129.0,1452.0,1120.0,2350.0,820.0,730.0,1534.0,525.0,2468.0,937.0,1421.0,2506.0,3281.0,480.0,1942.0,775.0,951.0,22699.0,998.0,61.0,613.0,12.0,220.0,23925.0,678.0,1819.0,5038.0,6101.0,7084.0,13062.0,11541.0
Wilson Unincorporated,6669.0,1648.0,3556.0,1465.0,1155.0,2396.0,3118.0,5.0,67.0,63.0,1028.0,1053.0,265.0,358.0,1601.0,94.0,76.0,115.0,226.0,35.0,420.0,140.0,427.0,95.0,391.0,197.0,13.0,5665.0,694.0,34.0,184.0,6.0,86.0,6267.0,402.0,680.0,1647.0,1591.0,1103.0,4059.0,2610.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34673.0,7052.0,19021.0,8600.0,5458.0,9147.0,20068.0,29.0,53.0,224.0,2023.0,3034.0,1980.0,3661.0,2290.0,789.0,1525.0,584.0,2402.0,788.0,2164.0,2884.0,4307.0,460.0,2748.0,930.0,1798.0,31460.0,2245.0,110.0,439.0,19.0,400.0,33677.0,996.0,2739.0,8013.0,8879.0,7990.0,17879.0,16794.0

In [83]:
wacrac['WAC:Age%:Workers 29 or Younger'] = percent(wacrac['WAC:Age:Workers 29 or Younger'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Age%:Workers 30 to 54'] = percent(wacrac['WAC:Age:Workers 30 to 54'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Age%:Workers 55 Older'] = percent(wacrac['WAC:Age:Workers 55 Older'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Earnings%:1250mo or Less'] = percent(wacrac['WAC:Earnings:1250mo or Less'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Earnings%:1251 to 3333mo'] = percent(wacrac['WAC:Earnings:1251 to 3333mo'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Earnings%:Greater Than 3333mo'] = percent(wacrac['WAC:Earnings:Greater Than 3333mo'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:11Agriculture, Forestry, Fishing & Hunting'] = percent(wacrac['WAC:NAICS:11Agriculture, Forestry, Fishing & Hunting'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:21Mining, Quarrying, Oil & Gas'] = percent(wacrac['WAC:NAICS:21Mining, Quarrying, Oil & Gas'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:22Utilities'] = percent(wacrac['WAC:NAICS:22Utilities'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:23Construction'] = percent(wacrac['WAC:NAICS:23Construction'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:31to33Manufacturing'] = percent(wacrac['WAC:NAICS:31to33Manufacturing'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:42Wholesale Trade'] = percent(wacrac['WAC:NAICS:42Wholesale Trade'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:44to45Retail Trade'] = percent(wacrac['WAC:NAICS:44to45Retail Trade'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:48to49Transportation & Warehousing'] = percent(wacrac['WAC:NAICS:48to49Transportation & Warehousing'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:51Information'] = percent(wacrac['WAC:NAICS:51Information'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:52Finance & Insurance'] = percent(wacrac['WAC:NAICS:52Finance & Insurance'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:48to49Transportation & Warehousing'] = percent(wacrac['WAC:NAICS:48to49Transportation & Warehousing'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:51Information'] = percent(wacrac['WAC:NAICS:51Information'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:52Finance & Insurance'] = percent(wacrac['WAC:NAICS:52Finance & Insurance'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:53Real Estate & Rental & Leasing'] = percent(wacrac['WAC:NAICS:53Real Estate & Rental & Leasing'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:54Professional, Scientific, & Technical Services'] = percent(wacrac['WAC:NAICS:54Professional, Scientific, & Technical Services'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:55Management of Companies & Enterprises'] = percent(wacrac['WAC:NAICS:55Management of Companies & Enterprises'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:56Administrative & Support & Waste Management & Remediation Services'] = percent(wacrac['WAC:NAICS:56Administrative & Support & Waste Management & Remediation Services'], 
                                                                                             wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:61Educational Services'] = percent(wacrac['WAC:NAICS:61Educational Services'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:62Healthcare & Social Assistance'] = percent(wacrac['WAC:NAICS:62Healthcare & Social Assistance'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:71Arts, Entertainment, & Recreation'] = percent(wacrac['WAC:NAICS:71Arts, Entertainment, & Recreation'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:72Accommodation & Food Services'] = percent(wacrac['WAC:NAICS:72Accommodation & Food Services'], wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:81Other Services (Except Public Administration)'] = percent(wacrac['WAC:NAICS:81Other Services (Except Public Administration)'], 
                                                                               wacrac['WAC:Total Jobs'])
wacrac['WAC:NAICS%:92Public Administration'] = percent(wacrac['WAC:NAICS:92Public Administration'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Race%:White Alone'] = percent(wacrac['WAC:Race:White Alone'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Race%:Black or African American Alone'] = percent(wacrac['WAC:Race:Black or African American Alone'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Race%:American Indian or Alaska Native Alone'] = percent(wacrac['WAC:Race:American Indian or Alaska Native Alone'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Race%:Asian Alone'] = percent(wacrac['WAC:Race:Asian Alone'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Race%:Native Hawaiian or Other Pacific Islander Alone'] = percent(wacrac['WAC:Race:Native Hawaiian or Other Pacific Islander Alone'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Race%:Two or More Races'] = percent(wacrac['WAC:Race:Two or More Races'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Ethnicity%:Not Hispanic or Latino'] = percent(wacrac['WAC:Ethnicity:Not Hispanic or Latino'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Ethnicity%:Hispanic or Latino'] = percent(wacrac['WAC:Ethnicity:Hispanic or Latino'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Ed%:Less than High School'] = percent(wacrac['WAC:Ed:Less than High School'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Ed%:High School or Equivalent'] = percent(wacrac['WAC:Ed:High School or Equivalent'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Ed%:Some College or Associates'] = percent(wacrac['WAC:Ed:Some College or Associates'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Ed%:Bachelors or Advanced Degree'] = percent(wacrac['WAC:Ed:Bachelors or Advanced Degree'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Sex%:Male'] = percent(wacrac['WAC:Sex:Male'], wacrac['WAC:Total Jobs'])
wacrac['WAC:Sex%:Female'] = percent(wacrac['WAC:Sex:Female'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmAge%:0 to 1 Year'] = percent(wacrac['WAC:FirmAge:0 to 1 Year'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmAge%:2 to 3 Years'] = percent(wacrac['WAC:FirmAge:2 to 3 Years'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmAge%:4 to 5 Years'] = percent(wacrac['WAC:FirmAge:4 to 5 Years'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmAge%:6 to 10 Years'] = percent(wacrac['WAC:FirmAge:6 to 10 Years'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmAge%:11 or More Years'] = percent(wacrac['WAC:FirmAge:11 or More Years'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmSize%:0 to 19 Employees'] = percent(wacrac['WAC:FirmSize:0 to 19 Employees'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmSize%:20 to 49 Employees'] = percent(wacrac['WAC:FirmSize:20 to 49 Employees'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmSize%:50 to 249 Employees'] = percent(wacrac['WAC:FirmSize:50 to 249 Employees'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmSize%:250 to 499 Employees'] = percent(wacrac['WAC:FirmSize:250 to 499 Employees'], wacrac['WAC:Total Jobs'])
wacrac['WAC:FirmSize%:500 or More Employees'] = percent(wacrac['WAC:FirmSize:500 or More Employees'], wacrac['WAC:Total Jobs'])

In [84]:
wacrac['RAC:Age%:Workers 29 or Younger'] = percent(wacrac['RAC:Age:Workers 29 or Younger'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Age%:Workers 30 to 54'] = percent(wacrac['RAC:Age:Workers 30 to 54'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Age%:Workers 55 Older'] = percent(wacrac['RAC:Age:Workers 55 Older'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Earnings%:1250mo or Less'] = percent(wacrac['RAC:Earnings:1250mo or Less'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Earnings%:1251 to 3333mo'] = percent(wacrac['RAC:Earnings:1251 to 3333mo'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Earnings%:Greater Than 3333mo'] = percent(wacrac['RAC:Earnings:Greater Than 3333mo'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:11Agriculture, Forestry, Fishing & Hunting'] = percent(wacrac['RAC:NAICS:11Agriculture, Forestry, Fishing & Hunting'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:21Mining, Quarrying, Oil & Gas'] = percent(wacrac['RAC:NAICS:21Mining, Quarrying, Oil & Gas'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:22Utilities'] = percent(wacrac['RAC:NAICS:22Utilities'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:23Construction'] = percent(wacrac['RAC:NAICS:23Construction'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:31to33Manufacturing'] = percent(wacrac['RAC:NAICS:31to33Manufacturing'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:42Wholesale Trade'] = percent(wacrac['RAC:NAICS:42Wholesale Trade'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:44to45Retail Trade'] = percent(wacrac['RAC:NAICS:44to45Retail Trade'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:48to49Transportation & Warehousing'] = percent(wacrac['RAC:NAICS:48to49Transportation & Warehousing'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:51Information'] = percent(wacrac['RAC:NAICS:51Information'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:52Finance & Insurance'] = percent(wacrac['RAC:NAICS:52Finance & Insurance'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:48to49Transportation & Warehousing'] = percent(wacrac['RAC:NAICS:48to49Transportation & Warehousing'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:51Information'] = percent(wacrac['RAC:NAICS:51Information'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:52Finance & Insurance'] = percent(wacrac['RAC:NAICS:52Finance & Insurance'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:53Real Estate & Rental & Leasing'] = percent(wacrac['RAC:NAICS:53Real Estate & Rental & Leasing'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:54Professional, Scientific, & Technical Services'] = percent(wacrac['RAC:NAICS:54Professional, Scientific, & Technical Services'], 
                                                                                wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:55Management of Companies & Enterprises'] = percent(wacrac['RAC:NAICS:55Management of Companies & Enterprises'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:56Administrative & Support & Waste Management & Remediation Services'] = percent(wacrac['RAC:NAICS:56Administrative & Support & Waste Management & Remediation Services'], 
                                                                                             wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:61Educational Services'] = percent(wacrac['RAC:NAICS:61Educational Services'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:62Healthcare & Social Assistance'] = percent(wacrac['RAC:NAICS:62Healthcare & Social Assistance'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:71Arts, Entertainment, & Recreation'] = percent(wacrac['RAC:NAICS:71Arts, Entertainment, & Recreation'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:72Accommodation & Food Services'] = percent(wacrac['RAC:NAICS:72Accommodation & Food Services'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:81Other Services (Except Public Administration)'] = percent(wacrac['RAC:NAICS:81Other Services (Except Public Administration)'], wacrac['RAC:Total Jobs'])
wacrac['RAC:NAICS%:92Public Administration'] = percent(wacrac['RAC:NAICS:92Public Administration'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Race%:White Alone'] = percent(wacrac['RAC:Race:White Alone'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Race%:Black or African American Alone'] = percent(wacrac['RAC:Race:Black or African American Alone'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Race%:American Indian or Alaska Native Alone'] = percent(wacrac['RAC:Race:American Indian or Alaska Native Alone'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Race%:Asian Alone'] = percent(wacrac['RAC:Race:Asian Alone'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Race%:Native Hawaiian or Other Pacific Islander Alone'] = percent(wacrac['RAC:Race:Native Hawaiian or Other Pacific Islander Alone'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Race%:Two or More Races'] = percent(wacrac['RAC:Race:Two or More Races'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Ethnicity%:Not Hispanic or Latino'] = percent(wacrac['RAC:Ethnicity:Not Hispanic or Latino'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Ethnicity%:Hispanic or Latino'] = percent(wacrac['RAC:Ethnicity:Hispanic or Latino'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Ed%:Less than High School'] = percent(wacrac['RAC:Ed:Less than High School'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Ed%:High School or Equivalent'] = percent(wacrac['RAC:Ed:High School or Equivalent'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Ed%:Some College or Associates'] = percent(wacrac['RAC:Ed:Some College or Associates'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Ed%:Bachelors or Advanced Degree'] = percent(wacrac['RAC:Ed:Bachelors or Advanced Degree'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Sex%:Male'] = percent(wacrac['RAC:Sex:Male'], wacrac['RAC:Total Jobs'])
wacrac['RAC:Sex%:Female'] = percent(wacrac['RAC:Sex:Female'], wacrac['RAC:Total Jobs'])

In [85]:
wacrac.head()

,WAC:Total Jobs,WAC:Age:Workers 29 or Younger,WAC:Age:Workers 30 to 54,WAC:Age:Workers 55 Older,WAC:Earnings:1250mo or Less,WAC:Earnings:1251 to 3333mo,WAC:Earnings:Greater Than 3333mo,"WAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","WAC:NAICS:21Mining, Quarrying, Oil & Gas",WAC:NAICS:22Utilities,WAC:NAICS:23Construction,WAC:NAICS:31to33Manufacturing,WAC:NAICS:42Wholesale Trade,WAC:NAICS:44to45Retail Trade,WAC:NAICS:48to49Transportation & Warehousing,WAC:NAICS:51Information,WAC:NAICS:52Finance & Insurance,WAC:NAICS:53Real Estate & Rental & Leasing,"WAC:NAICS:54Professional, Scientific, & Technical Services",WAC:NAICS:55Management of Companies & Enterprises,WAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,WAC:NAICS:61Educational Services,WAC:NAICS:62Healthcare & Social Assistance,"WAC:NAICS:71Arts, Entertainment, & Recreation",WAC:NAICS:72Accommodation & Food Services,WAC:NAICS:81Other Services (Except Public Administration),WAC:NAICS:92Public Administration,WAC:Race:White Alone,WAC:Race:Black or African American Alone,WAC:Race:American Indian or Alaska Native Alone,WAC:Race:Asian Alone,WAC:Race:Native Hawaiian or Other Pacific Islander Alone,WAC:Race:Two or More Races,WAC:Ethnicity:Not Hispanic or Latino,WAC:Ethnicity:Hispanic or Latino,WAC:Ed:Less than High School,WAC:Ed:High School or Equivalent,WAC:Ed:Some College or Associates,WAC:Ed:Bachelors or Advanced Degree,WAC:Sex:Male,WAC:Sex:Female,WAC:FirmAge:0 to 1 Year,WAC:FirmAge:2 to 3 Years,WAC:FirmAge:4 to 5 Years,WAC:FirmAge:6 to 10 Years,WAC:FirmAge:11 or More Years,WAC:FirmSize:0 to 19 Employees,WAC:FirmSize:20 to 49 Employees,WAC:FirmSize:50 to 249 Employees,WAC:FirmSize:250 to 499 Employees,WAC:FirmSize:500 or More Employees,RAC:Total Jobs,RAC:Age:Workers 29 or Younger,RAC:Age:Workers 30 to 54,RAC:Age:Workers 55 Older,RAC:Earnings:1250mo or Less,RAC:Earnings:1251 to 3333mo,RAC:Earnings:Greater Than 3333mo,"RAC:NAICS:11Agriculture, Forestry, Fishing & Hunting","RAC:NAICS:21Mining, Quarrying, Oil & Gas",RAC:NAICS:22Utilities,RAC:NAICS:23Construction,RAC:NAICS:31to33Manufacturing,RAC:NAICS:42Wholesale Trade,RAC:NAICS:44to45Retail Trade,RAC:NAICS:48to49Transportation & Warehousing,RAC:NAICS:51Information,RAC:NAICS:52Finance & Insurance,RAC:NAICS:53Real Estate & Rental & Leasing,"RAC:NAICS:54Professional, Scientific, & Technical Services",RAC:NAICS:55Management of Companies & Enterprises,RAC:NAICS:56Administrative & Support & Waste Management & Remediation Services,RAC:NAICS:61Educational Services,RAC:NAICS:62Healthcare & Social Assistance,"RAC:NAICS:71Arts, Entertainment, & Recreation",RAC:NAICS:72Accommodation & Food Services,RAC:NAICS:81Other Services (Except Public Administration),RAC:NAICS:92Public Administration,RAC:Race:White Alone,RAC:Race:Black or African American Alone,RAC:Race:American Indian or Alaska Native Alone,RAC:Race:Asian Alone,RAC:Race:Native Hawaiian or Other Pacific Islander Alone,RAC:Race:Two or More Races,RAC:Ethnicity:Not Hispanic or Latino,RAC:Ethnicity:Hispanic or Latino,RAC:Ed:Less than High School,RAC:Ed:High School or Equivalent,RAC:Ed:Some College or Associates,RAC:Ed:Bachelors or Advanced Degree,RAC:Sex:Male,RAC:Sex:Female,WAC:Age%:Workers 29 or Younger,WAC:Age%:Workers 30 to 54,WAC:Age%:Workers 55 Older,WAC:Earnings%:1250mo or Less,WAC:Earnings%:1251 to 3333mo,WAC:Earnings%:Greater Than 3333mo,"WAC:NAICS%:11Agriculture, Forestry, Fishing & Hunting","WAC:NAICS%:21Mining, Quarrying, Oil & Gas",WAC:NAICS%:22Utilities,WAC:NAICS%:23Construction,WAC:NAICS%:31to33Manufacturing,WAC:NAICS%:42Wholesale Trade,WAC:NAICS%:44to45Retail Trade,WAC:NAICS%:48to49Transportation & Warehousing,WAC:NAICS%:51Information,WAC:NAICS%:52Finance & Insurance,WAC:NAICS%:53Real Estate & Rental & Leasing,"WAC:NAICS%:54Professional, Scientific, & Technical Services",WAC:NAICS%:55Management of Companies & Enterprises,WAC:NAICS%:56Administrative & Support & Waste Management & Remediation Services,WAC:NAICS%:61Educational Services,WAC:NAICS%:62Healthcare & Social Assistance,"WAC:NAICS%:71Arts, Entertainment, & Recreation",WAC:NAICS%:72Accommodation & Food Services,WAC:NAICS%:81Other Services (Except Public Administration),WAC:NAICS%:92Public Administration,WAC:Race%:White Alone,WAC:Race%:Black or African American Alone,WAC:Race%:American Indian or Alaska Native Alone,WAC:Race%:Asian Alone,WAC:Race%:Native Hawaiian or Other Pacific Islander Alone,WAC:Race%:Two or More Races,WAC:Ethnicity%:Not Hispanic or Latino,WAC:Ethnicity%:Hispanic or Latino,WAC:Ed%:Less than High School,WAC:Ed%:High School or Equivalent,WAC:Ed%:Some College or Associates,WAC:Ed%:Bachelors or Advanced Degree,WAC:Sex%:Male,WAC:Sex%:Female,WAC:FirmAge%:0 to 1 Year,WAC:FirmAge%:2 to 3 Years,WAC:FirmAge%:4 to 5 Years,WAC:FirmAge%:6 to 10 Years,WAC:FirmAge%:11 or More Years,WAC:FirmSize%:0 to 19 Employees,WAC:FirmSize%:20 to 49 Employees,WAC:FirmSize%:50 to 249 Employees,WAC:FirmSize%:250 to 499 Employees,WAC:FirmSize%:500 or More Employees,RAC:Age%:Workers 29 or Younger,RAC:Age%:Workers 30 to 54,RAC:Age%:Workers 55 Older,RAC:Earnings%:1250mo or Less,RAC:Earnings%:1251 to 3333mo,RAC:Earnings%:Greater Than 3333mo,"RAC:NAICS%:11Agriculture, Forestry, Fishing & Hunting","RAC:NAICS%:21Mining, Quarrying, Oil & Gas",RAC:NAICS%:22Utilities,RAC:NAICS%:23Construction,RAC:NAICS%:31to33Manufacturing,RAC:NAICS%:42Wholesale Trade,RAC:NAICS%:44to45Retail Trade,RAC:NAICS%:48to49Transportation & Warehousing,RAC:NAICS%:51Information,RAC:NAICS%:52Finance & Insurance,RAC:NAICS%:53Real Estate & Rental & Leasing,"RAC:NAICS%:54Professional, Scientific, & Technical Services",RAC:NAICS%:55Management of Companies & Enterprises,RAC:NAICS%:56Administrative & Support & Waste Management & Remediation Services,RAC:NAICS%:61Educational Services,RAC:NAICS%:62Healthcare & Social Assistance,"RAC:NAICS%:71Arts, Entertainment, & Recreation",RAC:NAICS%:72Accommodation & Food Services,RAC:NAICS%:81Other Services (Except Public Administration),RAC:NAICS%:92Public Administration,RAC:Race%:White Alone,RAC:Race%:Black or African American Alone,RAC:Race%:American Indian or Alaska Native Alone,RAC:Race%:Asian Alone,RAC:Race%:Native Hawaiian or Other Pacific Islander Alone,RAC:Race%:Two or More Races,RAC:Ethnicity%:Not Hispanic or Latino,RAC:Ethnicity%:Hispanic or Latino,RAC:Ed%:Less than High School,RAC:Ed%:High School or Equivalent,RAC:Ed%:Some College or Associates,RAC:Ed%:Bachelors or Advanced Degree,RAC:Sex%:Male,RAC:Sex%:Female
Cheatham County,7918.0,1949.0,4255.0,1714.0,1433.0,2789.0,3696.0,4.0,0.0,44.0,784.0,2290.0,76.0,820.0,382.0,20.0,165.0,69.0,263.0,2.0,393.0,960.0,447.0,62.0,600.0,172.0,365.0,7053.0,638.0,30.0,103.0,13.0,81.0,7482.0,436.0,784.0,1981.0,1833.0,1371.0,4295.0,3623.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19706.0,4446.0,10549.0,4711.0,3016.0,6117.0,10573.0,25.0,11.0,133.0,1584.0,1888.0,951.0,2087.0,999.0,405.0,781.0,312.0,1245.0,388.0,1186.0,1545.0,2556.0,269.0,1518.0,605.0,1218.0,18645.0,599.0,67.0,162.0,11.0,222.0,19050.0,656.0,1601.0,4477.0,4908.0,4274.0,10195.0,9511.0,24.614802,53.738318,21.646881,18.098005,35.223541,46.678454,0.050518,0.000000,0.555696,9.901490,28.921445,0.959838,10.356151,4.824451,0.252589,2.083860,0.871432,3.321546,0.025259,4.963375,12.124274,5.645365,0.783026,7.577671,2.172266,4.609750,89.075524,8.057590,0.378884,1.300834,0.164183,1.022986,94.493559,5.506441,9.901490,25.018944,23.149785,17.314979,54.243496,45.756504,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.561656,53.531919,23.906424,15.304983,31.041307,53.653710,0.126865,0.055821,0.674921,8.038161,9.580838,4.825941,10.590683,5.069522,2.055212,3.963260,1.583274,6.317873,1.968943,6.018472,7.840252,12.970669,1.365066,7.703238,3.070131,6.180859,94.615853,3.039683,0.339998,0.822085,0.055821,1.126560,96.671065,3.328935,8.124429,22.718969,24.906120,21.688826,51.735512,48.264488
Davidson County,502956.0,122426.0,272971.0,107559.0,75893.0,147811.0,279252.0,261.0,182.0,1465.0,23603.0,21374.0,24395.0,42556.0,26896.0,14044.0,23276.0,10106.0,39811.0,10440.0,42852.0,35732.0,79295.0,9913.0,48083.0,16092.0,32580.0,379502.0,98611.0,1672.0,15302.0,378.0,7491.0,478049.0,24907.0,44391.0,102707.0,120150.0,113282.0,254052.0,248904.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,320699.0,89080.0,166883.0,64736.0,53939.0,101707.0,165053.0,274.0,114.0,619.0,11347.0,17313.0,12571.0,29901.0,15791.0,9440.0,15869.0,6404.0,25659.0,9120.0,27696.0,24984.0,47647.0,6292.0,34436.0,10274.0,14948.0,217362.0,84986.0,1035.0,11809.0,239.0,5268.0,301251.0,19448.0,29154.0,63582.0,72691.0,66192.0,157008.0,163691.0,24.341294,54.273336,21.385370,15.089392,29.388455,55.522153,0.051893,0.036186,0.291278,4.692856,4.249676,4.850325,8.461178,5.347585,2.792292,4.627840,2.009321,7.915404,2.075728,8.520030,7.104399,15.765793,1.970948,9.560081,3.199485,6.477704,75.454314,19.606288,0.332435,3.042413,0.075156,1.489395,95.047877,4.952123,8.826021,20.420673,23.888770,22.523243,50.511774,49.488226,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,27.776825,52.037269,20.185906,16.819198,31.714162,51.466640,0.085438,0.035547,0.193016,3.538209,5.398520,3.919875,9.323696,4.923932,2.943570,4.948254,1.996888,8.000960,2.843788,8.636135,7.790483,14.857234,1.961964,10.737795,3.203627,4.661068,67.777573,26.500239,0.322733,3.682269,0.074525,1.642662,93.935747,6.064253,9.090767,19.826067,22.666426,20.639915,48.958057,51.041943
Dickson County,16461.0,4195.0,8556.0,3710.0,3524.0,6460.0,6477.0,26.0,21.0,236.0,1022.0,3763.0,733.0,2226.0,178.0,105.0,441.0,85.0,246.0,130.0,1076.0,1017.0,2395.0,64.0,1574.0,367.0,756.0,14622.0,1379.0,58.0,206.0,10.0,186.0,15922.0,539.0,1554.0,4400.0,3842.0,2470.0,8593.0,7868.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23414.0,5599.0,12454.0,5361.0,4159.0,7975.0,11280.0,32.0,35.0,269.0,1905.0,3320.0,1018.0,2709.0,818.0,343.0,795.0,284.0,1153.0,367.0,1354.0,1511.0,3198.0,235.0,2118.0,639.0,1311.0,21510.0,1319.0,60.0,231.0,17.0,277.0,22660.0,754.0,1999.0,5609.0,5802.0,4405.0,12065.0,11349.0,25.484478,51.977401,22.538120,21.408177,39.244274,39.347549,0.157949,0.127574,1.433692,6.208614,22.860094,4.452949,13.522872,1.081344,0.637871,2.679060,0.516372,1.494441,0.789745,6.536662,6.178239,14.549541,0.388798,9.561995,2.229512,4.592674,88.828139,8.377377,0.352348,1.251443,0.060750,1.129944,96.725594,3.274406,9.440496,26.729846,23.340016,15.005164,52.202175,47.797825,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.913043,53.190399,22.896558,17.762877,34.060818,48.176305,0.136670,0.149483,1.148885,8.136158,14.179551,4.347826,11.570001,3.493636,1.464936,3.395404,1.212950,4.924404,1.567438,5.782865,6.453404,13.658495,1.003673,9.045870,2.729136,5.599214,91.868113,5.633382,0.256257,0.986589,0.072606,1.183053,96.779704,3.220296,8.537627,23.955753,24.780046,18.813530,51.529000,48.471000
Houston County,1272.0,274.0,669.0,329.0,316.0,524.0,432.0,5.0,0.0,5.0,101.0,170.0,0.0,154.0,4.0,10.0,42.0,3.0,27.0,0.0,2.0,221.0,313.0,0.0,90.0,13.0,112.0,1171.0,63.0,2.0,21.0,1.0,14.0,1249.0,23.0,95.0,360.0,338.0,205.0,502.0,770.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2915.0,690.0,1555.0,670.0,531.0,1161.0,1223.0,5.0,18.0,21.0,274.0,630.0,73.0,320.0,69.0,35.0,79.0,34.0,83.0,22.0,115.0,285.0,415.0,11.0,220.0,49.0,157.0,2734.0,109.0,8.0,27.0,1.0,36.0,2851.0,64.0,239.0,802.0,731.0,453.0,1490.0,1425.0,21.540881,52.594340,25.864780,24.842767,41.194969,33.962264,0.393082,0.000000,0.393082,7.940252,13.364780,0.000000,12.106918,0.314465,0.786164,3.301887,0.235849,2.122642,0.000000,0.157233,17.374214,24.606918,0.000000,7.075472,1.022013,8.805031,92.059748,4.952830,0.157233,1.650943,0.078616,1.100629,98.191824,1.808176,7.468553,28.301887,26.572327,16.116352,39.465409,60.534591,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.670669,53.344768,22.984563,18.216123,39.828473,41.955403,0.171527,0.617496,0.720412,9.399657,21.612350,2.504288,10.977702,2.367067,1.200686,2.710120,1.166381,2.847341,0.754717,3.945111,9.777015,14.236707,0.377358,7.547170,1.680961,5.385935,93.790738,3.739280,0.274443,0.926244,0.034305,1.234991,97.804460,2.195540,8.198971,27.512864,25.077187,15.540309,51.114923,48.885077
Humphreys County,5620.0,1225.0,2919.0,1476.0,1112.0,1828.0,2680.0,8.0,31.0,32.0,538.0,1566.0,88.0,627.0,336.0,16.0,94.0,6.0,85.0,0.0,162.0,577.0,512.0,14.0,490.0,184.0,254.0,5139.0,363.0,23.0,34.0,8.0,53.0,5500.0,120.0,447.0,1628.0,1416.0,904.0,3286.0,2334.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6743.0,1571.0,3559.0,1613.0,1233.0,2646.0,2864.0,17.0,28.0,35.0,493.0,1651.0,188.0,816.0,262.0,62.0,181.0,36.0,178.0,49.0,285.0,639.0,794.0,26.0,486.0,140.0,377.0,6363.0,248.0,25.0,38.0,7.0,62.0,6597.0,146.0,587.0,1840.0,1680.0,1065.0,3566.0,3177.0,21.797153,51.939502,26.263345,19.786477,32.526690,47.686833,0.142349,0.551601,0.569395,9.572954,27.864769,1.565836,11.156584,5.978648,0.284698,1.672598,0.106762,1.512456,0.000000,2.882562,10.266904,9.110320,0.249110,8.718861,3.274021,4.519573,91.441281,6.459075,0.409253,0.604982,0.142349,0.943060,97.864769,2.135231,7.953737,28.967972,25.195730,16.085409,58.469751,41.530249,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23.298235,52.780661,23.921103,18.285630,39.240694,42.473676,0.252113,0.415245,0.519057,7.311286,24.484651,2.788077,12.101439,3.885511,0.919472,2.684265,0.533887,2.639775,0.726680,4.226605,9.476494,11.775174,0.385585,7.207474,2.076227,5.590983,94.364526,3.677888,0.370755,0.563547,0.103811,0.919472,97.834792,2.165208,8.705324,27.287557,24.914726,15.794157,52.884473,47.115527

In [86]:
wacrac = wacrac.transpose()
#rename geographies dict
wacrac = wacrac.rename(columns = {'Cheatham County, TN': 'Cheatham County', 'Davidson County, TN': 'Davidson County', 
                                  'Dickson County, TN': 'Dickson County', 'Houston County, TN': 'Houston County', 
                                  'Humphreys County, TN': 'Humphreys County', 'Maury County, TN': 'Maury County', 
                                  'Montgomery County, TN': 'Montgomery County', 'Robertson County, TN': 'Robertson County', 
                                  'Rutherford County, TN': 'Rutherford County', 'Stewart County, TN': 'Stewart County', 
                                  'Sumner County, TN': 'Sumner County', 'Trousdale County, TN': 'Trousdale County', 
                                  'Williamson County, TN': 'Williamson County', 'Wilson County, TN': 'Wilson County', 
                                  'Adams city, TN': 'Adams', 'Ashland City town, TN': 'Ashland City', 'Belle Meade city, TN': 'Belle Meade', 
                                  'Berry Hill city, TN': 'Berry Hill', 'Brentwood city, TN': 'Brentwood', 'Burns town, TN': 'Burns', 
                                  'Cedar Hill city, TN': 'Cedar Hill', 'Charlotte town, TN': 'Charlotte', 'Clarksville city, TN': 'Clarksville', 
                                  'Columbia city, TN': 'Columbia', 'Coopertown town, TN': 'Coopertown', 'Cross Plains city, TN': 'Cross Plains', 
                                  'Cumberland City town, TN': 'Cumberland City', 'Dickson city, TN': 'Dickson', 'Dover city, TN': 'Dover', 
                                  'Eagleville city, TN': 'Eagleville', 'Erin city, TN': 'Erin', 'Fairview city, TN': 'Fairview', 
                                  'Forest Hills city, TN': 'Forest Hills', 'Franklin city, TN': 'Franklin', 'Gallatin city, TN': 'Gallatin', 
                                  'Goodlettsville city, TN': 'Goodlettsville', 'Greenbrier town, TN': 'Greenbrier', 
                                  'Hendersonville city, TN': 'Hendersonville', 'Kingston Springs town, TN': 'Kingston Springs', 
                                  'La Vergne city, TN': 'La Vergne', 'Lafayette city, TN': 'Lafayette', 'Lebanon city, TN': 'Lebanon', 
                                  'McEwen city, TN': 'McEwen', 'Millersville city, TN': 'Millersville', 'Mitchellville city, TN': 'Mitchellville', 
                                  'Mount Juliet city, TN': 'Mount Juliet', 'Mount Pleasant city, TN': 'Mount Pleasant', 
                                  'Murfreesboro city, TN': 'Murfreesboro', 'Nashville-Davidson metropolitan government (balance)': 'Nashville', 
                                  'New Johnsonville city, TN': 'New Johnsonville', 'Nolensville town, TN': 'Nolensville', 
                                  'Oak Hill city, TN': 'Oak Hill', 'Pegram town, TN': 'Pegram', 'Pleasant View city, TN': 'Pleasant View', 
                                  'Portland city, TN': 'Portland', 'Ridgetop city, TN': 'Ridgetop', 'Slayden town, TN': 'Slayden', 
                                  'Smyrna town, TN': 'Smyrna', 'Spring Hill city, TN': 'Spring Hill', 'Springfield city, TN': 'Springfield', 
                                  'Tennessee Ridge town, TN': 'Tennessee Ridge', "Thompson's Station town, TN": "Thompson's Station", 
                                  'Vanleer town, TN': 'Vanleer', 'Watertown city, TN': 'Watertown', 'Waverly city, TN': 'Waverly', 
                                  'Westmoreland town, TN': 'Westmoreland', 'White Bluff town, TN': 'White Bluff', 
                                  'White House city, TN': 'White House', 'Orlinda city, TN': 'Orlinda'})
wacrac = wacrac.transpose().reset_index(drop = False)

In [87]:
wacrac = wacrac.rename(columns = {'index':'NAME'})

In [88]:
wacrac.to_csv('../../Outputs/wacrac.csv', index = False)

## Origin-Destination

In [122]:
#all primary jobs
url = 'https://lehd.ces.census.gov/data/lodes/LODES7/tn/od/tn_od_main_JT01_2019.csv.gz'
od = pd.read_csv(url)
print('Your file is ready.')

Your file is ready.

In [123]:
odcols = {'h_geocode': 'HOMEGEO_ID', 'w_geocode': 'WORKGEO_ID', 'S000': 'Total Jobs', 'SA01': 'Age:Workers 29 or Younger', 'SA02': 'Age:Workers 30 to 54', 
          'SA03': 'Age:Workers 55 Older', 'SE01': 'Earnings:1250mo or Less', 'SE02': 'Earnings:1251 to 3333mo', 'SE03': 'Earnings:Greater Than 3333mo', 
          'SI01': 'Sector:Goods Producing', 'SI02': 'Sector:Trade, Transportation & Utilities', 'SI03': 'Sector:All Other Services'}

In [124]:
od.rename(columns = odcols, inplace = True)

In [125]:
od.head()

,WORKGEO_ID,HOMEGEO_ID,Total Jobs,Age:Workers 29 or Younger,Age:Workers 30 to 54,Age:Workers 55 Older,Earnings:1250mo or Less,Earnings:1251 to 3333mo,Earnings:Greater Than 3333mo,Sector:Goods Producing,"Sector:Trade, Transportation & Utilities",Sector:All Other Services,createdate
0,470010201001000,470010201001063,2,1,1,0,0,1,1,0,0,2,20211018
1,470010201001000,470010201002013,1,0,0,1,1,0,0,0,0,1,20211018
2,470010201001000,470010201002017,1,1,0,0,0,1,0,0,0,1,20211018
3,470010201001000,470010201002021,1,1,0,0,0,1,0,0,0,1,20211018
4,470010201001000,470010202023018,1,0,0,1,0,0,1,0,0,1,20211018

In [126]:
od['WORKGEO_ID'] = od['WORKGEO_ID'].astype(str)
od['HOMEGEO_ID'] = od['HOMEGEO_ID'].astype(str)

In [127]:
#add columns with county name and place name respectively
od['Home County'] = od['HOMEGEO_ID'].map(c_inverted)
od['Home Incorporated'] = od['HOMEGEO_ID'].map(un_inverted)
od['Home Place'] = od['HOMEGEO_ID'].map(p_inverted)

od['Work County'] = od['WORKGEO_ID'].map(c_inverted)
od['Work Incorporated'] = od['WORKGEO_ID'].map(un_inverted)
od['Work Place'] = od['WORKGEO_ID'].map(p_inverted)

In [128]:
od['Home County'] = od['Home County'].str.get(0)
od['Home Incorporated'] = od['Home Incorporated'].str.get(0)
od['Home Place'] = od['Home Place'].str.get(0)

od['Work County'] = od['Work County'].str.get(0)
od['Work Incorporated'] = od['Work Incorporated'].str.get(0)
od['Work Place'] = od['Work Place'].str.get(0)

In [129]:
test = od['Home County'].str.split(pat = ",", expand = True)
od['Home County'] = test[0]
test = od['Work County'].str.split(pat = ",", expand = True)
od['Work County'] = test[0]

In [130]:
test = od['Home Place'].str.split(pat = ",", expand = True)
od['Home Place'] = test[0]
test = od['Work Place'].str.split(pat = ",", expand = True)
od['Work Place'] = test[0]

In [131]:
od = od.replace({'Adams city': 'Adams', 'Ashland City town': 'Ashland City', 'Belle Meade city': 'Belle Meade', 
                                  'Berry Hill city': 'Berry Hill', 'Brentwood city': 'Brentwood', 'Burns town': 'Burns', 
                                  'Cedar Hill city': 'Cedar Hill', 'Charlotte town': 'Charlotte', 'Clarksville city': 'Clarksville', 
                                  'Columbia city': 'Columbia', 'Coopertown town': 'Coopertown', 'Cross Plains city': 'Cross Plains', 
                                  'Cumberland City town': 'Cumberland City', 'Dickson city': 'Dickson', 'Dover city': 'Dover', 
                                  'Eagleville city': 'Eagleville', 'Erin city': 'Erin', 'Fairview city': 'Fairview', 
                                  'Forest Hills city': 'Forest Hills', 'Franklin city': 'Franklin', 'Gallatin city': 'Gallatin', 
                                  'Goodlettsville city': 'Goodlettsville', 'Greenbrier town': 'Greenbrier', 
                                  'Hendersonville city': 'Hendersonville', 'Kingston Springs town': 'Kingston Springs', 
                                  'La Vergne city': 'La Vergne', 'Lafayette city': 'Lafayette', 'Lebanon city': 'Lebanon', 
                                  'McEwen city': 'McEwen', 'Millersville city': 'Millersville', 'Mitchellville city': 'Mitchellville', 
                                  'Mount Juliet city': 'Mount Juliet', 'Mount Pleasant city': 'Mount Pleasant', 
                                  'Murfreesboro city': 'Murfreesboro', 'Nashville-Davidson metropolitan government (balance)': 'Nashville', 
                                  'New Johnsonville city': 'New Johnsonville', 'Nolensville town': 'Nolensville', 
                                  'Oak Hill city': 'Oak Hill', 'Pegram town': 'Pegram', 'Pleasant View city': 'Pleasant View', 
                                  'Portland city': 'Portland', 'Ridgetop city': 'Ridgetop', 'Slayden town': 'Slayden', 
                                  'Smyrna town': 'Smyrna', 'Spring Hill city': 'Spring Hill', 'Springfield city': 'Springfield', 
                                  'Tennessee Ridge town': 'Tennessee Ridge', "Thompson's Station town": "Thompson's Station", 
                                  'Vanleer town': 'Vanleer', 'Watertown city': 'Watertown', 'Waverly city': 'Waverly', 
                                  'Westmoreland town': 'Westmoreland', 'White Bluff town': 'White Bluff', 
                                  'White House city': 'White House', 'Orlinda city': 'Orlinda'})

In [132]:
od = od.drop(columns = 'createdate')

In [136]:
od.head()

,WORKGEO_ID,HOMEGEO_ID,Total Jobs,Age:Workers 29 or Younger,Age:Workers 30 to 54,Age:Workers 55 Older,Earnings:1250mo or Less,Earnings:1251 to 3333mo,Earnings:Greater Than 3333mo,Sector:Goods Producing,"Sector:Trade, Transportation & Utilities",Sector:All Other Services,Home Incorporated,Home Place,Work County,Work Incorporated,Work Place
Home County,,,,,,,,,,,,,,,,,
Anderson County,470010201001000,470010201001063,2,1,1,0,0,1,1,0,0,2,NaN,Oak Ridge city,Anderson County,NaN,Oak Ridge city
Anderson County,470010201001000,470010201002013,1,0,0,1,1,0,0,0,0,1,NaN,Oak Ridge city,Anderson County,NaN,Oak Ridge city
Anderson County,470010201001000,470010201002017,1,1,0,0,0,1,0,0,0,1,NaN,Oak Ridge city,Anderson County,NaN,Oak Ridge city
Anderson County,470010201001000,470010201002021,1,1,0,0,0,1,0,0,0,1,NaN,Oak Ridge city,Anderson County,NaN,Oak Ridge city
Anderson County,470010201001000,470010202023018,1,0,0,1,0,0,1,0,0,1,NaN,Oak Ridge city,Anderson County,NaN,Oak Ridge city

In [120]:
# od['Age%:Workers 29 or Younger'] = percent(od['Age:Workers 29 or Younger'], od['Total Jobs'])
# od['Age%:Workers 30 to 54'] = percent(od['Age:Workers 30 to 54'], od['Total Jobs'])
# od['Age%:Workers 55 Older'] = percent(od['Age:Workers 55 Older'], od['Total Jobs'])
# od['Earnings%:1250mo or Less'] = percent(od['Earnings:1250mo or Less'], od['Total Jobs'])
# od['Earnings%:1251 to 3333mo'] = percent(od['Earnings:1251 to 3333mo'], od['Total Jobs'])
# od['Earnings%:Greater Than 3333mo'] = percent(od['Earnings:Greater Than 3333mo'], od['Total Jobs'])
# od['Sector%:Goods Producing'] = percent(od['Sector:Goods Producing'], od['Total Jobs'])
# od['Sector%:Trade, Transportation & Utilities'] = percent(od['Sector:Trade, Transportation & Utilities'], od['Total Jobs'])
# od['Sector%:All Other Services'] = percent(od['Sector:All Other Services'], od['Total Jobs'])

In [121]:
od.to_csv('../../Outputs/od.csv', index = False)